<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Notifications;
use App\Application\Audit\AuditWriter;use App\Application\Operations\NotificationDeliveryService;use App\Models\NotificationDelivery;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class NotificationController{
public function template(Request$r,AuditWriter$a){$d=$r->validate(['code'=>'required|string|max:80','locale'=>'required|in:en,fr','purpose'=>'required|in:TRANSACTIONAL,CLAIMS,RENEWALS,MARKETING,SECURITY','channel'=>'required|in:SMS,EMAIL,PUSH,WHATSAPP','subject'=>'nullable|string|max:200','body'=>'required|string|max:10000','required_variables'=>'array']);$t=app(\App\Domain\Tenancy\TenantContext::class)->id();$v=(int)DB::table('notification_templates')->where(['tenant_id'=>$t,'code'=>$d['code'],'locale'=>$d['locale'],'channel'=>$d['channel']])->max('version')+1;$id=(string)Str::uuid();DB::table('notification_templates')->insert([...$d,'required_variables'=>json_encode($d['required_variables']??[]),'id'=>$id,'tenant_id'=>$t,'version'=>$v,'status'=>'DRAFT','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$a->record('notification.template.created','notification_template',$id,['version'=>$v]);return response()->json(['data'=>['id'=>$id,'version'=>$v,'status'=>'DRAFT']],201);}
public function approveTemplate(Request$r,string$template,AuditWriter$a){$t=app(\App\Domain\Tenancy\TenantContext::class)->id();return DB::transaction(function()use($r,$template,$a,$t){$o=DB::table('notification_templates')->where(['id'=>$template,'tenant_id'=>$t])->lockForUpdate()->first();abort_unless($o,404);abort_unless($o->status==='DRAFT'&&$o->created_by!==$r->user()->id,422);DB::table('notification_templates')->where(['tenant_id'=>$t,'code'=>$o->code,'locale'=>$o->locale,'channel'=>$o->channel,'status'=>'ACTIVE'])->update(['status'=>'RETIRED','updated_at'=>now()]);DB::table('notification_templates')->where('id',$template)->update(['status'=>'ACTIVE','approved_by'=>$r->user()->id,'approved_at'=>now(),'updated_at'=>now()]);$a->record('notification.template.approved','notification_template',$template,['version'=>$o->version]);return response()->json(['data'=>['id'=>$template,'status'=>'ACTIVE']]);});}
public function preference(Request$r,AuditWriter$a){$d=$r->validate(['party_id'=>'required|uuid|exists:parties,id','purpose'=>'required|in:TRANSACTIONAL,CLAIMS,RENEWALS,MARKETING,SECURITY','channel'=>'required|in:SMS,EMAIL,PUSH,WHATSAPP','enabled'=>'required|boolean']);$t=app(\App\Domain\Tenancy\TenantContext::class)->id();abort_unless(DB::table('tenant_customers')->where(['tenant_id'=>$t,'party_id'=>$d['party_id']])->exists(),404);/* S6: SELF_SERVICE preferences are the caller's own; staff need customers.manage to change another customer's. */abort_unless($d['party_id']===$r->user()->party_id||$r->user()->hasPermission('customers.manage'),404);abort_if(in_array($d['purpose'],['TRANSACTIONAL','SECURITY'],true)&&!$d['enabled'],422);DB::table('communication_preferences')->upsert([['id'=>(string)Str::uuid(),...$d,'source'=>'SELF_SERVICE','changed_at'=>now(),'created_at'=>now(),'updated_at'=>now()]],['party_id','purpose','channel'],['enabled','source','changed_at','updated_at']);$a->record('communication.preference.changed','party',$d['party_id'],$d);return response()->json(['data'=>$d]);}
public function queue(Request$r,NotificationDeliveryService$s){$d=$r->validate(['party_id'=>'required|uuid|exists:parties,id','template_id'=>'required|uuid|exists:notification_templates,id','destination'=>'required|string|max:190','variables'=>'required|array','idempotency_key'=>'required|string|max:100']);$out=$s->queue(app(\App\Domain\Tenancy\TenantContext::class)->id(),$d);return response()->json(['data'=>$out['delivery']],$out['created']?202:200);}
public function retry(string$d,NotificationDeliveryService$s){return response()->json(['data'=>$s->retry($this->owned($d))]);}public function cancel(string$d,NotificationDeliveryService$s){return response()->json(['data'=>$s->cancel($this->owned($d))]);}private function owned(string$id):NotificationDelivery{return NotificationDelivery::where(['id'=>$id,'tenant_id'=>app(\App\Domain\Tenancy\TenantContext::class)->id()])->firstOrFail();}}
