<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Attribution;
use App\Application\Customers\AttributionService;use App\Models\AttributionDispute;use App\Models\CustomerAttribution;use App\Models\Partner;use App\Models\Party;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;
final class AttributionController
{
public function store(Request$r,AttributionService$s):JsonResponse{$d=$r->validate(['party_id'=>'required|uuid|exists:parties,id','partner_id'=>'nullable|required_unless:origin_type,SYSTEM|uuid|exists:partners,id','origin_type'=>'required|in:SYSTEM,AGENT,BROKER','terms_version'=>'required|string|max:32','evidence_reference'=>'required|string|max:255']);$party=Party::findOrFail($d['party_id']);$this->authorizeParty($r,$party);$a=$s->lock($party,isset($d['partner_id'])?Partner::findOrFail($d['partner_id']):null,$d['origin_type'],$d['terms_version'],$d['evidence_reference'],$r->user());return response()->json(['data'=>$a],201);}
public function show(Request$r,CustomerAttribution$attribution):JsonResponse{$this->authorizeParty($r,$attribution->party);return response()->json(['data'=>$attribution->load('party','partner.party','disputes')]);}
public function dispute(Request$r,CustomerAttribution$attribution,AttributionService$s):JsonResponse{$this->authorizeParty($r,$attribution->party);$d=$r->validate(['raised_by_partner_id'=>'nullable|uuid|exists:partners,id','reason_code'=>'required|in:WRONG_ORIGIN,DUPLICATE_CLIENT,CONSENT_WITHDRAWN,CONTRACT_ENDED,FRAUD_SUSPECTED,OTHER','description'=>'required|string|min:20|max:4000','evidence'=>'sometimes|array|max:20']);$dispute=$s->openDispute($attribution,isset($d['raised_by_partner_id'])?Partner::findOrFail($d['raised_by_partner_id']):null,$d['reason_code'],$d['description'],$d['evidence']??[],$r->user());return response()->json(['data'=>$dispute],201);}
public function resolve(Request$r,AttributionDispute$dispute,AttributionService$s):JsonResponse{$this->authorizeParty($r,$dispute->attribution->party);$d=$r->validate(['resolution_code'=>'required|in:UPHELD,REASSIGNED,REJECTED','resolution_notes'=>'required|string|min:20|max:4000','reassign_partner_id'=>'nullable|required_if:resolution_code,REASSIGNED|uuid|exists:partners,id']);$resolved=$s->resolve($dispute,$d['resolution_code'],$d['resolution_notes'],$r->user(),isset($d['reassign_partner_id'])?Partner::findOrFail($d['reassign_partner_id']):null);return response()->json(['data'=>$resolved]);}
private function authorizeParty(Request$r,Party$party):void{$global=$r->user()->memberships()->where('status','ACTIVE')->whereIn('role_code',['SYSTEM_ADMIN','PLATFORM_ADMIN','COMPLIANCE_ADMIN'])->exists();abort_unless($global||$party->customers()->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->exists(),404);}
}
