<?php
namespace App\Filament\Admin\Resources\Consents;
use App\Application\Privacy\ConsentService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\Consents\Pages;use App\Models\Consent;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Infolists;use Filament\Notifications\Notification;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class ConsentResource extends Resource
{
protected static?string$model=Consent::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedShieldCheck;protected static string|\UnitEnum|null$navigationGroup='Customers & partners';protected static?int$navigationSort=22;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Affirmative consent')->columnSpanFull()->description('Record only consent supported by a displayed notice and affirmative action.')->columns(2)->schema([Forms\Components\Select::make('party_id')->relationship('party','display_name')->searchable()->preload()->required(),Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload(),Forms\Components\Select::make('purpose')->options(['INSURANCE_SERVICES'=>'Insurance services','MARKETING'=>'Marketing communications','DATA_SHARING'=>'Authorized data sharing','CLAIMS_PROCESSING'=>'Claims processing'])->required()->native(false),Forms\Components\TextInput::make('notice_version')->required()->maxLength(32),Forms\Components\Select::make('channel')->options(['WEB'=>'Web','ASSISTED'=>'Assisted','PAPER'=>'Paper','API'=>'API'])->required()->native(false),Forms\Components\TextInput::make('evidence_reference')->required()->maxLength(255),Forms\Components\Toggle::make('affirmed')->label('The person affirmatively agreed')->required()->accepted()])]);}
public static function infolist(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Affirmative consent')->columnSpanFull()->columns(2)->schema([Infolists\Components\TextEntry::make('party.display_name')->label('Person / organization'),Infolists\Components\TextEntry::make('tenant.legal_name')->label('Organization')->placeholder('Platform-wide'),Infolists\Components\TextEntry::make('purpose')->badge(),Infolists\Components\TextEntry::make('channel')->badge(),Infolists\Components\TextEntry::make('notice_version')->label('Notice version'),Infolists\Components\TextEntry::make('status')->badge()->color(fn(string$state)=>match($state){'GRANTED'=>'success','WITHDRAWN'=>'danger',default=>'gray'}),Infolists\Components\TextEntry::make('evidence.reference')->label('Evidence reference')->placeholder('—'),Infolists\Components\IconEntry::make('evidence.affirmed')->label('Affirmatively agreed')->boolean(),Infolists\Components\TextEntry::make('given_at')->label('Given')->dateTime(),Infolists\Components\TextEntry::make('withdrawn_at')->label('Withdrawn')->dateTime()->placeholder('—')])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('party.display_name')->label('Person / organization')->searchable(),Tables\Columns\TextColumn::make('purpose')->badge(),Tables\Columns\TextColumn::make('notice_version')->label('Notice'),Tables\Columns\TextColumn::make('channel')->badge(),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'GRANTED'=>'success','WITHDRAWN'=>'danger',default=>'gray'}),Tables\Columns\TextColumn::make('given_at')->dateTime()])->filters([Tables\Filters\SelectFilter::make('status')->options(['GRANTED'=>'Granted','WITHDRAWN'=>'Withdrawn','EXPIRED'=>'Expired'])])->recordActions([Actions\ViewAction::make(),Actions\Action::make('withdraw')->color('danger')->requiresConfirmation()->visible(fn(Consent$c)=>$c->status==='GRANTED')->schema([Forms\Components\Select::make('reason')->options(['CUSTOMER_REQUEST'=>'Customer request','PURPOSE_ENDED'=>'Purpose ended','ERROR_CORRECTION'=>'Recorded in error'])->required(),Forms\Components\Textarea::make('notes')->required()->minLength(10)])->action(function(Consent$c,array$data){if(ServiceValidation::run(fn()=>app(ConsentService::class)->withdraw($c,$data['reason'],['notes'=>$data['notes']],auth()->user()))===null)return;Notification::make()->title('Consent withdrawn')->success()->send();})])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No consent records')->emptyStateDescription('Capture purpose-specific, versioned consent with verifiable evidence.')->emptyStateIcon(Heroicon::OutlinedShieldCheck);}
public static function getPages():array{return['index'=>Pages\ListConsents::route('/'),'create'=>Pages\CreateConsent::route('/create'),'view'=>Pages\ViewConsent::route('/{record}')];}}
