<?php
namespace App\Filament\Admin\Resources\Proposals;use App\Domain\Tenancy\TenantContext;use App\Filament\Admin\Resources\Proposals\Pages;use App\Models\Proposal;use BackedEnum;use Filament\Actions;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
final class ProposalResource extends Resource{protected static?string$model=Proposal::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedClipboardDocumentCheck;protected static string|\UnitEnum|null$navigationGroup='Sales workspace';protected static?int$navigationSort=42;public static function getEloquentQuery():Builder{return parent::getEloquentQuery()->where('tenant_id',app(TenantContext::class)->id());}public static function form(Schema$s):Schema{return$s->components([]);}
    public static function infolist(Schema $s): Schema { return $s->components(\App\Filament\Shared\Components\RecordShell::detailTabs('proposal', self::overview(), null, true)); }
    /** Overview tab (CoreRecordOverview pattern). */
    public static function overview(): array { $o = \App\Filament\Shared\Components\CoreRecordOverview::class; return [
        $o::section('proposal', [$o::text('proposal_number', 'number')->copyable(), $o::status(), $o::text('party.display_name', 'customer'), $o::text('offer.product.name', 'product'), $o::text('offer.carrier.cima_code', 'carrier'), $o::money('terms_snapshot.total_minor', 'terms_snapshot.currency', 'total'), $o::text('version')]),
        $o::section('lifecycle', [$o::date('submitted_at', 'submitted', true), $o::text('submission_count'), $o::date('decided_at', 'decided', true), $o::date('withdrawn_at', 'withdrawn', true)]),
    ]; }
    public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('proposal_number')->label('Proposal')->searchable()->copyable(),Tables\Columns\TextColumn::make('party.display_name')->label('Customer')->searchable(),Tables\Columns\TextColumn::make('offer.product.name')->label('Product'),Tables\Columns\TextColumn::make('terms_snapshot.total_minor')->label('Total')->formatStateUsing(fn($state)=>\App\Application\WebExperiences\Money::display($state===null?null:(int)$state,'XAF')),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'PAYMENT_PENDING','APPROVED'=>'success','UNDER_REVIEW'=>'warning','DECLINED'=>'danger',default=>'info'}),Tables\Columns\TextColumn::make('submitted_at')->dateTime()->placeholder('Not submitted')])->recordActions([Actions\ViewAction::make()])->emptyStateHeading('No insurance proposals')->emptyStateDescription('Proposals begin from a customer-accepted quote offer.')->emptyStateIcon(Heroicon::OutlinedClipboardDocumentCheck);}public static function getPages():array{return['index'=>Pages\ListProposals::route('/'),'view'=>Pages\ViewProposal::route('/{record}')];}}
