<?php
namespace App\Filament\Admin\Resources\Proposals;use App\Domain\Tenancy\TenantContext;use App\Filament\Admin\Resources\Proposals\Pages;use App\Models\Proposal;use BackedEnum;use Filament\Actions;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
final class ProposalResource extends \App\Filament\Shared\LocalizedResource{protected static?string$model=Proposal::class;protected static string|BackedEnum|null$navigationIcon='lucide-clipboard-check';protected static string|\UnitEnum|null$navigationGroup='Sales workspace';protected static?int$navigationSort=42;public static function getEloquentQuery():Builder{/* P5 2026-09-29: in a portal, the caller's book only (no-op in admin) */return \App\Application\WebExperiences\PortalScope::narrowTable(parent::getEloquentQuery()->where('tenant_id',app(TenantContext::class)->id()),'proposals');}public static function form(Schema$s):Schema{return$s->components([]);}
    public static function infolist(Schema $s): Schema { return $s->components(\App\Filament\Shared\Components\RecordShell::detailTabs('proposal', self::overview(), null, true)); }
    /** Overview tab (CoreRecordOverview pattern). */
    public static function overview(): array { $o = \App\Filament\Shared\Components\CoreRecordOverview::class; return [
        $o::section('proposal', [$o::text('proposal_number', 'number')->copyable(), $o::status(), $o::text('party.display_name', 'customer'), $o::text('offer.product.name', 'product'), $o::text('offer.carrier.cima_code', 'carrier'), $o::money('terms_snapshot.total_minor', 'terms_snapshot.currency', 'total'), $o::text('version')]),
        $o::section('lifecycle', [$o::date('submitted_at', 'submitted', true), $o::text('submission_count'), $o::date('decided_at', 'decided', true), $o::date('withdrawn_at', 'withdrawn', true)]),
    ]; }
    public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('proposal_number')->label('Proposal')->searchable()->copyable(),Tables\Columns\TextColumn::make('party.display_name')->label('Customer')->searchable(),Tables\Columns\TextColumn::make('offer.product.name')->label('Product'),\App\Filament\Shared\Columns::money('terms_snapshot.total_minor')->label('Total'),\App\Filament\Shared\Columns::status('status'),\App\Filament\Shared\Columns::date('submitted_at')->placeholder('Not submitted')])->recordActions([Actions\ViewAction::make()])->emptyStateHeading('No insurance proposals')->emptyStateDescription('Proposals begin from a customer-accepted quote offer.')->emptyStateIcon('lucide-clipboard-check');}public static function getPages():array{return['index'=>Pages\ListProposals::route('/'),'view'=>Pages\ViewProposal::route('/{record}')];}}
