/**
 * Pure helpers for the in-app document viewer (app/documents/view.tsx).
 * No React Native imports so node tests can load it.
 */

import { PDFJS_LIB_SOURCE, PDFJS_VERSION as BUNDLED_PDFJS_VERSION, PDFJS_WORKER_SOURCE } from "./vendor/pdfjs.ts";

/**
 * pdf.js is bundled with the app (src/lib/vendor/pdfjs.ts, generated by
 * scripts/vendor-pdfjs.mjs from the pinned pdfjs-dist devDependency): no CDN,
 * works offline, ships over the air. It is >= 4.2.67 and runs with
 * isEvalSupported:false (CVE-2024-4367).
 */
export const PDFJS_VERSION = BUNDLED_PDFJS_VERSION;

/** Fixed origin the WebView fallback runs under (its blob: URLs inherit it). */
export const VIEWER_BASE_URL = "https://insurance.opesdatacenter.tech/";

export type ViewerSource =
  | { kind: "url"; url: string }
  | { kind: "quote"; quoteId: string };

/** Route params for /documents/view. `source` is url:<https…> or quote:<id>. */
export function viewerParams(source: ViewerSource, title: string, fileName?: string) {
  return {
    source: source.kind === "url" ? `url:${source.url}` : `quote:${source.quoteId}`,
    title,
    ...(fileName ? { fileName } : {}),
  };
}

/**
 * Hosts a url: viewer source may point at: the API host (documents carry the
 * bearer token or a signed link from it). Anything else is rejected so a
 * crafted deep link cannot make the viewer fetch arbitrary content.
 */
export function allowedDocumentHosts(apiBaseUrl: string | null | undefined): string[] {
  try {
    return apiBaseUrl ? [new URL(apiBaseUrl).host.toLowerCase()] : [];
  } catch {
    return [];
  }
}

/** True when `url` is an https URL (http only when the API itself is http) on an allowed document host. */
export function isAllowedDocumentUrl(url: string, apiBaseUrl: string | null | undefined): boolean {
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  if (u.username || u.password) return false;
  let apiProtocol = "https:";
  try {
    if (apiBaseUrl) apiProtocol = new URL(apiBaseUrl).protocol;
  } catch {
    // keep https
  }
  if (u.protocol !== "https:" && !(u.protocol === "http:" && apiProtocol === "http:")) return false;
  return allowedDocumentHosts(apiBaseUrl).includes(u.host.toLowerCase());
}

export function parseViewerSource(raw: string | undefined | null, apiBaseUrl?: string | null): ViewerSource | null {
  const v = String(raw ?? "");
  if (v.startsWith("url:")) {
    const url = v.slice(4);
    return isAllowedDocumentUrl(url, apiBaseUrl) ? { kind: "url", url } : null;
  }
  if (v.startsWith("quote:") && v.length > 6) return { kind: "quote", quoteId: v.slice(6) };
  return null;
}

/** "Policy schedule POL-2026-000002" -> "Policy-schedule-POL-2026-000002.pdf" */
export function safeFileName(title: string | undefined | null, fallback = "document"): string {
  const base = String(title ?? "")
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^A-Za-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  const name = base || fallback;
  return /\.pdf$/i.test(name) ? name : `${name}.pdf`;
}

/** True when the URL is served by our API and must carry the bearer token. */
export function needsBearer(url: string, apiBaseUrl: string): boolean {
  if (!apiBaseUrl) return false;
  const base = apiBaseUrl.replace(/\/+$/, "");
  return url.startsWith(`${base}/`) || url === base;
}

/** API-relative path for an absolute URL under the API base (for api({ raw })). */
export function apiPathFor(url: string, apiBaseUrl: string): string {
  return url.slice(apiBaseUrl.replace(/\/+$/, "").length);
}

/** "1.2 MB" style size for the header. */
export function formatBytes(bytes: number | null | undefined): string | null {
  if (!bytes || bytes <= 0) return null;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** The pdf.js WebView may only ever show its own inline page: no navigation anywhere. */
export function viewerAllowsNavigation(url: string): boolean {
  return url === "about:blank" || url === VIEWER_BASE_URL || url === VIEWER_BASE_URL.slice(0, -1);
}

/** A JS string literal that is safe inside an inline <script> (no "</script", "<!--"). */
export function scriptLiteral(value: string): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

let pdfjsLiterals: { lib: string; worker: string } | null = null;
/** Escaped once per app run: the bundled library is ~1.8 MB. */
function bundledPdfjs() {
  pdfjsLiterals ??= { lib: scriptLiteral(PDFJS_LIB_SOURCE), worker: scriptLiteral(PDFJS_WORKER_SOURCE) };
  return pdfjsLiterals;
}

/**
 * Content-Security-Policy of the viewer page: no network at all. Scripts are
 * the inline bootstrap plus the blob: modules it creates from the bundled
 * pdf.js; the PDF bytes arrive inline.
 */
export const VIEWER_CSP =
  "default-src 'none'; script-src 'unsafe-inline' blob:; worker-src blob:; style-src 'unsafe-inline'; img-src data: blob:; font-src data: blob:; connect-src blob: data:; base-uri 'none'; form-action 'none'";

/**
 * Self-contained HTML that renders a base64 PDF with the bundled pdf.js,
 * every page stacked and scaled to the viewport width (device-pixel-ratio
 * aware so text stays crisp), pinch-zoom enabled. Posts {type:"pages"|"error"} to RN.
 */
export function viewerHtml(
  base64: string,
  options: { background?: string; accent?: string; loadingLabel?: string } = {},
): string {
  const bg = options.background ?? "#FAF7F2";
  const accent = options.accent ?? "#35419F";
  const loading = (options.loadingLabel ?? "Loading…").replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
  const pdfjs = bundledPdfjs();
  return `<!doctype html><html><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${VIEWER_CSP}">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=4, user-scalable=yes">
<style>
  html,body{margin:0;padding:0;background:${bg};}
  #pages{padding:8px;display:flex;flex-direction:column;gap:10px;align-items:center;}
  canvas{display:block;width:100%;height:auto;background:#fff;border-radius:6px;box-shadow:0 1px 4px rgba(15,21,53,.12);}
  .page{width:100%;max-width:900px;}
  #status{font:14px/20px -apple-system,Roboto,Inter,sans-serif;color:#57526A;text-align:center;padding:24px 16px;}
  #bar{position:fixed;left:0;top:0;height:3px;width:0;background:${accent};transition:width .2s;}
</style></head><body>
<div id="bar"></div><div id="status">${loading}</div><div id="pages"></div>
<script>window.__pdfjs={lib:${pdfjs.lib},worker:${pdfjs.worker}};</script>
<script>
(function(){
  var post=function(m){try{window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify(m));}catch(e){}};
  var fail=function(e){post({type:"error",message:String(e&&e.message||e)});};
  try{
    var src=window.__pdfjs;window.__pdfjs=null;
    var blobUrl=function(code){return URL.createObjectURL(new Blob([code],{type:"text/javascript"}));};
    var libUrl=blobUrl(src.lib),workerUrl=blobUrl(src.worker);src=null;
    var b64=${scriptLiteral(base64)};
    var bin=atob(b64),len=bin.length,bytes=new Uint8Array(len);
    for(var i=0;i<len;i++)bytes[i]=bin.charCodeAt(i);
    import(libUrl).then(function(pdfjsLib){
      pdfjsLib.GlobalWorkerOptions.workerSrc=workerUrl;
      return pdfjsLib.getDocument({data:bytes,isEvalSupported:false,enableXfa:false}).promise;
    }).then(function(pdf){
      var pages=document.getElementById("pages"),status=document.getElementById("status"),bar=document.getElementById("bar");
      var width=Math.min(pages.clientWidth-16,900),dpr=Math.min(window.devicePixelRatio||1,3);
      var n=pdf.numPages,done=0;
      post({type:"pages",count:n});
      var render=function(i){
        return pdf.getPage(i).then(function(page){
          var vp=page.getViewport({scale:1});var scale=width/vp.width;var v=page.getViewport({scale:scale*dpr});
          var wrap=document.createElement("div");wrap.className="page";
          var c=document.createElement("canvas");c.width=v.width;c.height=v.height;wrap.appendChild(c);pages.appendChild(wrap);
          return page.render({canvasContext:c.getContext("2d"),viewport:v}).promise.then(function(){
            done++;bar.style.width=Math.round(done/n*100)+"%";if(done===n){status.remove();setTimeout(function(){bar.remove();},300);}
          });
        });
      };
      var chain=Promise.resolve();
      for(var p=1;p<=n;p++){(function(i){chain=chain.then(function(){return render(i);});})(p);}
      chain.catch(function(e){post({type:"error",message:String(e&&e.message||e)});});
    }).catch(function(e){post({type:"error",message:String(e&&e.message||e)});});
  }catch(e){post({type:"error",message:String(e&&e.message||e)});}
})();
</script></body></html>`;
}

export type DocumentKind = "pdf" | "image" | "html" | "unknown";

/** Detect the payload kind from base64 magic bytes, falling back to the MIME type. */
export function detectKind(base64: string | null | undefined, mime?: string | null): DocumentKind {
  const head = String(base64 ?? "").slice(0, 16);
  if (head.startsWith("JVBER")) return "pdf";
  if (head.startsWith("iVBOR") || head.startsWith("/9j/") || head.startsWith("R0lGOD") || head.startsWith("UklGR")) return "image";
  const m = String(mime ?? "").toLowerCase();
  if (m.includes("pdf")) return "pdf";
  if (m.startsWith("image/")) return "image";
  if (m.includes("html")) return "html";
  return "unknown";
}

/** MIME for a detected image payload (for data: URIs). */
export function imageMime(base64: string): string {
  if (base64.startsWith("iVBOR")) return "image/png";
  if (base64.startsWith("R0lGOD")) return "image/gif";
  if (base64.startsWith("UklGR")) return "image/webp";
  return "image/jpeg";
}

/**
 * Stable offline-cache file name for a viewer source. The URL's query string
 * (signatures, expiry) is dropped so a re-signed link hits the same entry.
 */
export function cacheKey(source: ViewerSource): string {
  const raw = source.kind === "quote" ? `quote:${source.quoteId}` : `url:${source.url.split("?")[0]}`;
  let h = 5381;
  for (let i = 0; i < raw.length; i++) h = ((h << 5) + h + raw.charCodeAt(i)) >>> 0;
  return `doc-${h.toString(36)}`;
}

/** "3 / 7" page indicator text. */
export function pageIndicator(page: number, total: number): string {
  return total > 0 ? `${Math.min(Math.max(page, 1), total)} / ${total}` : "";
}

/** GET quotes/{id}/document answers 422 until the quote is generated: a "being prepared" state, not a load failure. */
export function quoteNotReady(source: ViewerSource | null | undefined, error: unknown): boolean {
  return source?.kind === "quote" && (error as { status?: number } | null)?.status === 422;
}
