<?php
declare(strict_types=1);namespace App\Interfaces\Http\Controllers\Api\V1\Policies;
use App\Application\Identity\OwnershipScope;use App\Application\Policies\{PolicyIssuanceService,PolicyServicingService};use App\Domain\Tenancy\TenantContext;use App\Models\{PaymentIntentRecord,Policy,PolicyIssuanceRequest,PolicyTransaction,Proposal,Tenant};use Illuminate\Http\{JsonResponse,Request};
final class PolicyController{
 public function __construct(private OwnershipScope $own) {}
 /* Customers only ever resolve their own policies (audit A1); anything foreign is a 404. */
 private function policy(string$id):Policy{return $this->own->apply(Policy::where('tenant_id',app(TenantContext::class)->id()),request()->user())->findOrFail($id);}
 private function transaction(string$policy,string$id):PolicyTransaction{$this->policy($policy);return PolicyTransaction::where(['policy_id'=>$policy,'tenant_id'=>app(TenantContext::class)->id()])->findOrFail($id);}
 private function issuance(string$id):PolicyIssuanceRequest{return PolicyIssuanceRequest::where('tenant_id',app(TenantContext::class)->id())->findOrFail($id);}
 public function index(Request$r):JsonResponse{$this->own->requireTenantWide($r->user(),'policies.read');$q=$this->own->apply(Policy::where('tenant_id',app(TenantContext::class)->id()),$r->user());if($r->filled('status'))$q->where('status',$r->string('status'));if($r->filled('party_id'))$q->where('party_id',$r->string('party_id'));return response()->json(['data'=>$q->latest()->paginate(25)]);}
 public function requestIssuance(Request$r,PolicyIssuanceService$s,TenantContext$c):JsonResponse{$d=$r->validate(['proposal_id'=>'required|uuid|exists:proposals,id','payment_intent_id'=>'required|uuid|exists:payment_intents,id','delegated_authority_agreement_id'=>'nullable|uuid|exists:delegated_authority_agreements,id','territory'=>'required|string|max:80','coverage_starts_at'=>'required|date','coverage_ends_at'=>'required|date|after:coverage_starts_at']);$p=Proposal::where('tenant_id',$c->id())->findOrFail($d['proposal_id']);$pay=PaymentIntentRecord::where('tenant_id',$c->id())->findOrFail($d['payment_intent_id']);return response()->json(['data'=>$s->request(Tenant::findOrFail($c->id()),$p,$pay,$d,$r->user())],201);}
 public function approveIssuance(Request$r,string$issuance,PolicyIssuanceService$s):JsonResponse{$d=$r->validate(['policy_number'=>'nullable|string|max:100','carrier_reference'=>'required_without:policy_number|nullable|string|max:160','previous_policy_id'=>'nullable|uuid|exists:policies,id']);/* REQ-SET-006: the server allocates policy_number; a supplied one only falls back as carrier_reference */$d['carrier_reference']=$d['carrier_reference']??$d['policy_number'];unset($d['policy_number']);return response()->json(['data'=>$s->approve($this->issuance($issuance),$d,$r->user())],201);}
 public function rejectIssuance(Request$r,string$issuance,PolicyIssuanceService$s):JsonResponse{$d=$r->validate(['reason'=>'required|string|min:20|max:2000']);return response()->json(['data'=>$s->reject($this->issuance($issuance),$d['reason'],$r->user())]);}
 public function show(string$policy):JsonResponse{return response()->json(['data'=>$this->policy($policy)->load(['transactions','certificates','renewals'])]);}
 public function requestService(Request$r,string$policy,PolicyServicingService$s):JsonResponse{$p=$this->policy($policy);$d=$r->validate(['type'=>'required|in:ENDORSEMENT,CANCELLATION,REINSTATEMENT','effective_at'=>'required|date','requested_changes'=>'sometimes|array','premium_delta_minor'=>'required|integer','reason_code'=>'required|string|max:64','notes'=>'nullable|string|max:2000','endorsement_type'=>'sometimes|string|max:32','service_request_id'=>'sometimes|uuid']);return response()->json(['data'=>$s->request($p,$d,$r->user())],201);}
 public function requestServicePayment(Request$r,string$policy,string$transaction,PolicyServicingService$s):JsonResponse{$t=$this->transaction($policy,$transaction);$d=$r->validate(['provider'=>'required|in:fake,maviance,campay,mtn_momo,orange_money','payer_phone_e164'=>['required','regex:/^\+[1-9]\d{7,14}$/'],'idempotency_key'=>'required|string|min:16|max:128']);\App\Application\Demo\DemoPersonas::assertProviderAllowed($d['provider'],$r->user());return response()->json(['data'=>$s->requestPayment($t,$d,$r->user())],201);}
 public function linkServicePayment(Request$r,string$policy,string$transaction,PolicyServicingService$s):JsonResponse{$t=$this->transaction($policy,$transaction);$d=$r->validate(['payment_intent_id'=>'required|uuid|exists:payment_intents,id']);$pay=$this->own->applyVia(PaymentIntentRecord::where('tenant_id',app(TenantContext::class)->id()),$r->user(),'proposal')->findOrFail($d['payment_intent_id']);return response()->json(['data'=>$s->linkPayment($t,$pay)]);}
 public function approveService(Request$r,string$policy,string$transaction,PolicyServicingService$s):JsonResponse{return response()->json(['data'=>$s->approve($this->transaction($policy,$transaction),$r->user())]);}
 public function rejectService(Request$r,string$policy,string$transaction,PolicyServicingService$s):JsonResponse{$d=$r->validate(['reason'=>'required|string|min:20|max:2000']);return response()->json(['data'=>$s->reject($this->transaction($policy,$transaction),$d['reason'],$r->user())]);}
}
