<?php
namespace App\Filament\Admin\Resources\Invitations;
use App\Application\Identity\InvitationService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\Invitations\Pages;use App\Models\TenantInvitation;use BackedEnum;use Filament\Actions;use Filament\Notifications\Notification;use Filament\Forms;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class InvitationResource extends Resource
{
protected static?string$model=TenantInvitation::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedEnvelope;protected static?string$navigationLabel='Invitations';protected static?int$navigationSort=14;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Invite colleague')->columnSpanFull()->columns(2)->schema([Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload()->required(),Forms\Components\TextInput::make('recipient_email')->email()->live(onBlur:true)->visible(fn($get)=>blank($get('recipient_phone_e164'))),Forms\Components\TextInput::make('recipient_phone_e164')->tel()->live(onBlur:true)->visible(fn($get)=>blank($get('recipient_email'))),Forms\Components\Select::make('role_code')->options(\App\Application\Identity\RoleCatalogue::invitableOptions())->required()->native(false)->live(),Forms\Components\Select::make('carrier_id')->label('Insurer')->options(fn()=>\App\Models\Carrier::with('party')->get()->mapWithKeys(fn($c)=>[$c->id=>($c->party?->display_name??$c->cima_code)])->all())->searchable()->visible(fn($get)=>in_array($get('role_code'),\App\Application\Identity\RoleCatalogue::CARRIER_ROLES,true))->required(fn($get)=>in_array($get('role_code'),\App\Application\Identity\RoleCatalogue::CARRIER_ROLES,true)),Forms\Components\TextInput::make('ttl_hours')->numeric()->minValue(1)->maxValue(168)->default(72)->required()])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('recipient_email')->label('Recipient')->placeholder(fn(TenantInvitation$i)=>$i->recipient_phone_e164),Tables\Columns\TextColumn::make('tenant.legal_name')->label('Organization'),Tables\Columns\TextColumn::make('role_code')->label('Role')->badge(),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'ACCEPTED'=>'success','PENDING'=>'warning','REVOKED'=>'danger',default=>'gray'}),Tables\Columns\TextColumn::make('expires_at')->dateTime()->since()->label('Expires')])->filters([Tables\Filters\SelectFilter::make('status')->options(['PENDING'=>'Pending','ACCEPTED'=>'Accepted','REVOKED'=>'Revoked'])])->recordActions([Actions\Action::make('revoke')->color('danger')->requiresConfirmation()->visible(fn(TenantInvitation$i)=>$i->status==='PENDING')->action(function(TenantInvitation$i){if(ServiceValidation::run(fn()=>app(InvitationService::class)->revoke($i))===null)return;Notification::make()->title('Invitation revoked')->success()->send();})])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No invitations')->emptyStateDescription('Invite staff without sharing passwords or creating accounts for them.')->emptyStateIcon(Heroicon::OutlinedEnvelope);}
public static function getPages():array{return['index'=>Pages\ListInvitations::route('/'),'create'=>Pages\CreateInvitation::route('/create')];}}
