<?php
namespace App\Filament\Admin\Resources\Invitations;
use App\Application\Identity\InvitationService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\Invitations\Pages;use App\Models\TenantInvitation;use BackedEnum;use Filament\Actions;use Filament\Notifications\Notification;use Filament\Forms;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Tables;use Filament\Tables\Table;
final class InvitationResource extends \App\Filament\Shared\LocalizedResource
{
protected static?string$model=TenantInvitation::class;protected static string|BackedEnum|null$navigationIcon='lucide-mail';protected static?string$navigationLabel='Invitations';protected static?int$navigationSort=14;protected static string|\UnitEnum|null$navigationGroup='Administration';
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Invite colleague')->columnSpanFull()->columns(2)->schema([Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload()->required(fn()=>!self::inPortal())->hidden(fn()=>self::inPortal()),Forms\Components\TextInput::make('recipient_email')->email()->live(onBlur:true)->visible(fn($get)=>blank($get('recipient_phone_e164'))),Forms\Components\TextInput::make('recipient_phone_e164')->tel()->live(onBlur:true)->visible(fn($get)=>blank($get('recipient_email'))),Forms\Components\Select::make('role_code')->options(fn()=>self::inPortal()?array_intersect_key(\App\Application\Identity\RoleCatalogue::invitableOptions(),array_flip(\App\Application\WebExperiences\PortalAccess::roles('insurer'))):\App\Application\Identity\RoleCatalogue::invitableOptions())->required()->native(false)->live(),Forms\Components\Select::make('carrier_id')->label('Insurer')->options(fn()=>\App\Models\Carrier::with('party')->get()->mapWithKeys(fn($c)=>[$c->id=>($c->party?->display_name??$c->cima_code)])->all())->searchable()->visible(fn($get)=>!self::inPortal()&&in_array($get('role_code'),\App\Application\Identity\RoleCatalogue::CARRIER_LINKABLE_ROLES,true))->required(fn($get)=>in_array($get('role_code'),\App\Application\Identity\RoleCatalogue::CARRIER_ROLES,true)),Forms\Components\TextInput::make('ttl_hours')->numeric()->minValue(1)->maxValue(168)->default(72)->required()])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('recipient_email')->label('Recipient')->placeholder(fn(TenantInvitation$i)=>$i->recipient_phone_e164),Tables\Columns\TextColumn::make('tenant.legal_name')->label('Organization'),Tables\Columns\TextColumn::make('role_code')->label('Role')->badge(),\App\Filament\Shared\Columns::status('status'),\App\Filament\Shared\Columns::date('expires_at')->since()->label('Expires')])->filters([Tables\Filters\SelectFilter::make('status')->options(['PENDING'=>'Pending','ACCEPTED'=>'Accepted','REVOKED'=>'Revoked'])])->recordActions([Actions\Action::make('revoke')->color('danger')->requiresConfirmation()->visible(fn(TenantInvitation$i)=>$i->status==='PENDING'&&\Illuminate\Support\Facades\Gate::allows('update',$i))->action(function(TenantInvitation$i){if(ServiceValidation::run(fn()=>app(InvitationService::class)->revoke($i))===null)return;Notification::make()->title('Invitation revoked')->success()->send();})])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No invitations')->emptyStateDescription('Invite staff without sharing passwords or creating accounts for them.')->emptyStateIcon('lucide-mail');}
/**
 * P4 (owner 2026-09-29): /insurer staff invitations — tenant and carrier are fixed to the caller's own (never a form
 * value), role list limited to the insurer portal roles, rows limited to the portal tenant; permission identity.invite
 * (TenantInvitationPolicy). Outside a portal nothing changes.
 */
public static function inPortal():bool{return \App\Application\WebExperiences\PortalScope::panel()==='insurer';}
public static function getEloquentQuery():\Illuminate\Database\Eloquent\Builder{$q=parent::getEloquentQuery();return self::inPortal()?$q->where('tenant_id',rescue(fn()=>app(\App\Domain\Tenancy\TenantContext::class)->id(),'',false)??'')->where('carrier_id',\App\Application\WebExperiences\PortalScope::carrierId()??''):$q;} // R7: own carrier's invitations only
public static function getNavigationGroup():?string{return self::inPortal()?__('insurer_portal_ops.nav.organisation'):'Administration';}
public static function getNavigationLabel():string{return self::inPortal()?__('insurer_portal_ops.nav.invitations'):'Invitations';}
public static function getPages():array{return['index'=>Pages\ListInvitations::route('/'),'create'=>Pages\CreateInvitation::route('/create'), 'view' => Pages\ViewInvitation::route('/{record}')];}}
