<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Trust;use App\Application\Compliance\{ComplianceCaseService,RegulatoryReportingService};use App\Application\Privacy\DataSubjectRequestService;use App\Application\Security\PrivilegedAccessService;use App\Application\Trust\FraudReviewService;use App\Domain\Tenancy\TenantContext;use App\Interfaces\Http\Controllers\Concerns\AuthorizesSensitiveActions;use App\Models\{ComplianceCase,DataSubjectRequest,FraudRuleVersion,PrivilegedAccessGrant,RegulatoryReportDefinition,RegulatoryReportRun,RiskAlert,User};use Illuminate\Http\{JsonResponse,Request};
final class Wave9Controller{use AuthorizesSensitiveActions;private function tenant():string{return app(TenantContext::class)->id();}private function owns(object$x):void{if(isset($x->tenant_id)&&$x->tenant_id!==$this->tenant())abort(404);}

public function alert(Request$r,FraudReviewService$s):JsonResponse{$this->authorizePermission('trust.fraud-alerts.create','risk_alert');$d=$r->validate(['subject_type'=>'required|string|max:64','subject_id'=>'required|uuid','alert_type'=>'required|string|max:64','severity'=>'required|in:LOW,MEDIUM,HIGH,CRITICAL','signals'=>'required|array','fraud_rule_version_id'=>'required|uuid','idempotency_key'=>'required|string|max:100','review_due_at'=>'nullable|date']);$x=$this->auditedCall(fn()=>$s->alert($this->tenant(),$d,$r->user()),'trust.fraud-alerts.create','risk_alert',null);return response()->json($x,201);}

public function decide(Request$r,RiskAlert$x,FraudReviewService$s):JsonResponse{$this->authorizePermission('trust.fraud-alerts.decide','risk_alert',$x->id);$this->owns($x);$d=$r->validate(['decision'=>'required|in:CLEARED,CONFIRMED,ESCALATED','notes'=>'required|string|max:4000']);return response()->json($this->auditedCall(fn()=>$s->decide($x,$d['decision'],$d['notes'],$r->user()),'trust.fraud-alerts.decide','risk_alert',$x->id));}

public function openCase(Request$r,ComplianceCaseService$s):JsonResponse{$this->authorizePermission('trust.compliance-cases.create','compliance_case');$d=$r->validate(['type'=>'required|string|max:48','subject_type'=>'required|string|max:64','subject_id'=>'required|uuid','severity'=>'required|in:LOW,MEDIUM,HIGH,CRITICAL','owner_id'=>'nullable|uuid','review_due_on'=>'nullable|date','findings'=>'array','idempotency_key'=>'required|string|max:100']);return response()->json($this->auditedCall(fn()=>$s->open($this->tenant(),$d,$r->user()),'trust.compliance-cases.create','compliance_case',null),201);}

public function caseTransition(Request$r,ComplianceCase$x,ComplianceCaseService$s):JsonResponse{$this->authorizePermission('trust.compliance-cases.transition','compliance_case',$x->id);$this->owns($x);$d=$r->validate(['to_status'=>'required|in:UNDER_REVIEW,REMEDIATION,CLOSED,REOPENED','reason_code'=>'required|string|max:64','findings'=>'array']);return response()->json($this->auditedCall(fn()=>$s->transition($x,$d['to_status'],$d['reason_code'],$d['findings']??[],$r->user()),'trust.compliance-cases.transition','compliance_case',$x->id));}

public function dsr(Request$r,DataSubjectRequestService$s):JsonResponse{$this->authorizePermission('trust.dsr.receive','data_subject_request');$d=$r->validate(['party_id'=>'required|uuid','type'=>'required|in:ACCESS,CORRECTION,ERASURE,RESTRICTION,PORTABILITY,OBJECTION','due_on'=>'required|date','assigned_to'=>'nullable|uuid','idempotency_key'=>'required|string|max:100']);return response()->json($this->auditedCall(fn()=>$s->receive($this->tenant(),$d,$r->user()),'trust.dsr.receive','data_subject_request',null),201);}

public function verifyDsr(Request$r,DataSubjectRequest$x,DataSubjectRequestService$s):JsonResponse{$this->authorizePermission('trust.dsr.verify','data_subject_request',$x->id);$this->owns($x);$d=$r->validate(['identity_evidence'=>'required|string|min:20']);return response()->json($this->auditedCall(fn()=>$s->verify($x,$d['identity_evidence'],$r->user()),'trust.dsr.verify','data_subject_request',$x->id));}

public function resolveDsr(Request$r,DataSubjectRequest$x,DataSubjectRequestService$s):JsonResponse{$this->authorizePermission('trust.dsr.resolve','data_subject_request',$x->id);$this->owns($x);$d=$r->validate(['decision'=>'required|string|max:64','notes'=>'required|string|max:4000']);return response()->json($this->auditedCall(fn()=>$s->resolve($x,$d['decision'],$d['notes'],$r->user()),'trust.dsr.resolve','data_subject_request',$x->id));}

public function access(Request$r,PrivilegedAccessService$s):JsonResponse{$this->authorizePermission('trust.privileged-access.request','privileged_access_grant');$d=$r->validate(['user_id'=>'required|uuid','purpose'=>'required|string|max:64','justification'=>'required|string|min:20|max:2000','starts_at'=>'required|date','expires_at'=>'required|date','scope'=>'required|array|min:1']);return response()->json($this->auditedCall(fn()=>$s->request($this->tenant(),User::findOrFail($d['user_id']),$d,$r->user()),'trust.privileged-access.request','privileged_access_grant',null),201);}

public function approveAccess(Request$r,PrivilegedAccessGrant$x,PrivilegedAccessService$s):JsonResponse{$this->authorizePermission('trust.privileged-access.approve','privileged_access_grant',$x->id);$this->owns($x);return response()->json($this->auditedCall(fn()=>$s->approve($x,$r->user()),'trust.privileged-access.approve','privileged_access_grant',$x->id));}

public function revokeAccess(Request$r,PrivilegedAccessGrant$x,PrivilegedAccessService$s):JsonResponse{$this->authorizePermission('trust.privileged-access.revoke','privileged_access_grant',$x->id);$this->owns($x);$d=$r->validate(['reason'=>'required|string|max:2000']);return response()->json($this->auditedCall(fn()=>$s->revoke($x,$d['reason'],$r->user()),'trust.privileged-access.revoke','privileged_access_grant',$x->id));}

public function prepareReport(Request$r,RegulatoryReportDefinition$d,RegulatoryReportingService$s):JsonResponse{$this->authorizePermission('trust.regulatory-reports.prepare','regulatory_report_run');$in=$r->validate(['period_key'=>'required|string|max:40','payload'=>'required|array','idempotency_key'=>'required|string|max:100']);return response()->json($this->auditedCall(fn()=>$s->prepare($this->tenant(),$d,$in,$r->user()),'trust.regulatory-reports.prepare','regulatory_report_run',null),201);}

public function approveReport(Request$r,RegulatoryReportRun$x,RegulatoryReportingService$s):JsonResponse{$this->authorizePermission('trust.regulatory-reports.approve','regulatory_report_run',$x->id);$this->owns($x);return response()->json($this->auditedCall(fn()=>$s->approve($x,$r->user()),'trust.regulatory-reports.approve','regulatory_report_run',$x->id));}

public function submitReport(Request$r,RegulatoryReportRun$x,RegulatoryReportingService$s):JsonResponse{$this->authorizePermission('trust.regulatory-reports.submit','regulatory_report_run',$x->id);$this->owns($x);return response()->json($this->auditedCall(fn()=>$s->submit($x),'trust.regulatory-reports.submit','regulatory_report_run',$x->id));}

public function reportFailure(Request$r,RegulatoryReportRun$x,RegulatoryReportingService$s):JsonResponse{$this->authorizePermission('trust.regulatory-reports.submit','regulatory_report_run',$x->id);$this->owns($x);$d=$r->validate(['reason'=>'required|string|max:2000']);return response()->json($this->auditedCall(fn()=>$s->fail($x,$d['reason']),'trust.regulatory-reports.submit','regulatory_report_run',$x->id));}

public function acknowledgeReport(Request$r,RegulatoryReportRun$x,RegulatoryReportingService$s):JsonResponse{$this->authorizePermission('trust.regulatory-reports.acknowledge','regulatory_report_run',$x->id);$this->owns($x);$d=$r->validate(['external_reference'=>'required|string|max:255']);return response()->json($this->auditedCall(fn()=>$s->acknowledge($x,$d['external_reference']),'trust.regulatory-reports.acknowledge','regulatory_report_run',$x->id));}
}
