<?php
declare(strict_types=1);
namespace App\Application\Catalogue;
use App\Application\Audit\AuditWriter;use App\Application\Events\OutboxWriter;use App\Application\Regulatory\CimaPublicationGuard;use App\Models\CoverageDefinition;use App\Models\ExclusionDefinition;use App\Models\InsuranceLine;use App\Models\InsuranceProduct;use App\Models\User;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class CatalogueService
{
public function __construct(private readonly AuditWriter$audit,private readonly OutboxWriter$outbox){}
public function createLine(array$data,User$actor):InsuranceLine{$line=InsuranceLine::create([...$data,'status'=>'ACTIVE']);$this->audit->record('catalogue.line.created','insurance_line',$line->id,['code'=>$line->code]);return$line;}
public function createCoverage(InsuranceLine$line,array$data,User$actor):CoverageDefinition{$coverage=$line->coverages()->create([...$data,'status'=>'ACTIVE']);$this->audit->record('catalogue.coverage.created','coverage_definition',$coverage->id,['line_code'=>$line->code]);return$coverage;}
public function createExclusion(InsuranceLine$line,array$data,User$actor):ExclusionDefinition{$exclusion=$line->exclusions()->create([...$data,'status'=>'ACTIVE']);$this->audit->record('catalogue.exclusion.created','exclusion_definition',$exclusion->id,['line_code'=>$line->code]);return$exclusion;}
public function createProduct(array$data,User$actor):InsuranceProduct{return DB::transaction(function()use($data,$actor){$line=InsuranceLine::where('code',$data['line_code'])->where('status','ACTIVE')->firstOrFail();$coverageIds=collect($data['coverage_ids'])->unique()->values();$coverages=CoverageDefinition::whereIn('id',$coverageIds)->where('insurance_line_id',$line->id)->where('status','ACTIVE')->get();if($coverages->count()!==$coverageIds->count())throw ValidationException::withMessages(['coverage_ids'=>__('wave2.coverage_line_mismatch')]);$missing=$line->coverages()->where('mandatory',true)->where('status','ACTIVE')->whereNotIn('id',$coverageIds)->pluck('code');if($missing->isNotEmpty())throw ValidationException::withMessages(['coverage_ids'=>__('wave2.mandatory_coverages',['codes'=>$missing->join(', ')])]);$exclusionIds=collect($data['exclusion_ids']??[])->unique()->values();if(ExclusionDefinition::whereIn('id',$exclusionIds)->where('insurance_line_id','!=',$line->id)->exists())throw ValidationException::withMessages(['exclusion_ids'=>__('wave2.exclusion_line_mismatch')]);$version=(InsuranceProduct::where(['carrier_id'=>$data['carrier_id'],'code'=>$data['code']])->lockForUpdate()->max('version')??0)+1;$product=InsuranceProduct::create(['carrier_id'=>$data['carrier_id'],'line_code'=>$data['line_code'],'code'=>$data['code'],'name'=>$data['name'],'version'=>$version,'effective_from'=>$data['effective_from'],'effective_until'=>$data['effective_until']??null,'status'=>'DRAFT','coverages'=>[],'eligibility_rules'=>$data['eligibility_rules'],'created_by'=>$actor->id,'regulatory_reference'=>$data['regulatory_reference']??null]);$product->coverageDefinitions()->sync($coverageIds->mapWithKeys(fn($id,$i)=>[$id=>['display_order'=>$i,'configuration'=>'{}']])->all());$product->exclusions()->sync($exclusionIds->mapWithKeys(fn($id)=>[$id=>['configuration'=>'{}']])->all());$this->audit->record('catalogue.product.created','insurance_product',$product->id,['version'=>$version]);$this->outbox->record('catalogue.product.created','insurance_product',$product->id,['product_id'=>$product->id,'version'=>$version]);return$product;});}
public function submit(InsuranceProduct$p,User$actor,string$notes):InsuranceProduct{if($p->status==='DRAFT')app(CimaPublicationGuard::class)->assertPublishable($p);return$this->transition($p,'DRAFT','IN_REVIEW','SUBMITTED_FOR_REVIEW',$notes,$actor);}
public function publish(InsuranceProduct$p,User$actor,string$reason):InsuranceProduct{if($p->status!=='IN_REVIEW')throw ValidationException::withMessages(['status'=>__('wave2.product_not_reviewable')]);if($p->created_by===$actor->id)throw ValidationException::withMessages(['actor'=>__('wave2.maker_checker')]);if(blank($p->regulatory_reference))throw ValidationException::withMessages(['regulatory_reference'=>__('wave2.regulatory_reference_required')]);if(!$p->tariffs()->where('status','APPROVED')->whereDate('effective_from','<=',$p->effective_from)->where(fn($q)=>$q->whereNull('effective_until')->orWhereDate('effective_until','>=',$p->effective_from))->exists())throw ValidationException::withMessages(['tariff'=>__('wave2.approved_tariff_required')]);app(CimaPublicationGuard::class)->assertPublishable($p);app(\App\Application\Documents\Engine\ProductDocumentGate::class)->assertPublishable($p);app(\App\Application\DocumentCatalogue\DocumentPublicationGate::class)->assertPublishable($p);return DB::transaction(function()use($p,$actor,$reason){InsuranceProduct::where(['carrier_id'=>$p->carrier_id,'code'=>$p->code,'status'=>'ACTIVE'])->where('id','!=',$p->id)->get()->each(fn($old)=>$this->transition($old,'ACTIVE','RETIRED','SUPERSEDED_VERSION','Superseded by '.$p->id,$actor));$p->update(['status'=>'ACTIVE','published_by'=>$actor->id,'published_at'=>now()]);$this->history($p,'IN_REVIEW','ACTIVE','PUBLISHED',$reason,$actor);$this->audit->record('catalogue.product.published','insurance_product',$p->id,['version'=>$p->version],$reason);$this->outbox->record('catalogue.product.published','insurance_product',$p->id,['product_id'=>$p->id,'version'=>$p->version]);return$p->refresh();});}
private function transition(InsuranceProduct$p,string$from,string$to,string$reason,string$notes,User$actor):InsuranceProduct{if($p->status!==$from)throw ValidationException::withMessages(['status'=>__('wave2.invalid_product_transition')]);$p->update(['status'=>$to]);$this->history($p,$from,$to,$reason,$notes,$actor);return$p->refresh();}
private function history(InsuranceProduct$p,?string$from,string$to,string$reason,string$notes,User$actor):void{DB::table('product_status_history')->insert(['id'=>(string)Str::uuid(),'insurance_product_id'=>$p->id,'from_status'=>$from,'to_status'=>$to,'reason_code'=>$reason,'notes'=>$notes,'actor_id'=>$actor->id,'occurred_at'=>now()]);}
}
