<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Documents;
use App\Application\Audit\AuditWriter;use App\Application\Documents\Adapters\SignedUrlAdapter;use App\Models\Document;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class DocumentController{
private const ACCESS_TTL_SECONDS=300;

public function register(Request$r,\App\Application\Documents\DocumentRegistrationService$svc){$d=$r->validate(['party_id'=>'nullable|uuid|exists:parties,id','category'=>'required|string|max:48','storage_key'=>'required|string|max:500','mime_type'=>'required|in:application/pdf,image/jpeg,image/png','size_bytes'=>'required|integer|min:1|max:20971520','sha256'=>'required|size:64']);return response()->json(['data'=>$svc->register(app(\App\Domain\Tenancy\TenantContext::class)->id(),$d,$r->user())],201);}
public function review(Request$r,string$document,\App\Application\Documents\DocumentRegistrationService$svc){$d=$r->validate(['scan_status'=>'required|in:CLEAN,INFECTED,FAILED','verification_status'=>'required|in:VERIFIED,REJECTED,NEEDS_REVIEW','ocr_data'=>'sometimes|array','notes'=>'required|string|max:2000']);return response()->json(['data'=>$svc->review(app(\App\Domain\Tenancy\TenantContext::class)->id(),$document,$d['scan_status'],$d['verification_status'],$r->has('ocr_data')?($d['ocr_data']??[]):null)]);}
public function access(Request$r,string$document,SignedUrlAdapter$urls){$d=$r->validate(['purpose'=>'required|string|max:64']);$doc=Document::where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$document)->where('scan_status','CLEAN')->first();abort_unless($doc,404);$signed=$urls->sign($doc,self::ACCESS_TTL_SECONDS);DB::table('document_access_log')->insert(['document_id'=>$document,'actor_id'=>$r->user()->id,'action'=>'READ','purpose'=>$d['purpose'],'request_id'=>$r->header('X-Request-Id',(string)Str::uuid()),'occurred_at'=>now()]);return response()->json(['data'=>['id'=>$document,'url'=>$signed->url,'expires_at'=>$signed->expiresAt,'expires_in_seconds'=>self::ACCESS_TTL_SECONDS]]);}}
