<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Documents;
use App\Application\Audit\AuditWriter;use App\Application\Documents\Adapters\SignedUrlAdapter;use App\Models\Document;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class DocumentController{
private const ACCESS_TTL_SECONDS=300;

public function register(Request$r,AuditWriter$audit){$d=$r->validate(['party_id'=>'nullable|uuid|exists:parties,id','category'=>'required|string|max:48','storage_key'=>'required|string|max:500','mime_type'=>'required|in:application/pdf,image/jpeg,image/png','size_bytes'=>'required|integer|min:1|max:20971520','sha256'=>'required|size:64']);abort_if(DB::table('documents')->where('sha256',$d['sha256'])->exists(),409,'Identical document already registered.');$id=(string)Str::uuid();DB::transaction(function()use($d,$id,$r,$audit){DB::table('documents')->insert([...$d,'id'=>$id,'tenant_id'=>app(\App\Domain\Tenancy\TenantContext::class)->id(),'scan_status'=>'PENDING','verification_status'=>'UNVERIFIED','ocr_data'=>'{}','created_at'=>now(),'updated_at'=>now()]);DB::table('document_versions')->insert(['id'=>(string)Str::uuid(),'document_id'=>$id,'version'=>1,'storage_key'=>$d['storage_key'],'sha256'=>$d['sha256'],'size_bytes'=>$d['size_bytes'],'mime_type'=>$d['mime_type'],'uploaded_by'=>$r->user()->id,'created_at'=>now()]);$audit->record('document.registered','document',$id,['category'=>$d['category']]);});return response()->json(['data'=>['id'=>$id,'scan_status'=>'PENDING']],201);}
public function review(Request$r,string$document,AuditWriter$audit){$d=$r->validate(['scan_status'=>'required|in:CLEAN,INFECTED,FAILED','verification_status'=>'required|in:VERIFIED,REJECTED,NEEDS_REVIEW','ocr_data'=>'sometimes|array','notes'=>'required|string|max:2000']);$doc=DB::table('documents')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$document)->first();abort_unless($doc,404);abort_if($d['scan_status']!=='CLEAN'&&$d['verification_status']==='VERIFIED',422,'An unclean document cannot be verified.');DB::table('documents')->where('id',$document)->update(['scan_status'=>$d['scan_status'],'verification_status'=>$d['verification_status'],'ocr_data'=>json_encode($d['ocr_data']??[]),'updated_at'=>now()]);$audit->record('document.reviewed','document',$document,['scan_status'=>$d['scan_status'],'verification_status'=>$d['verification_status']]);return response()->json(['data'=>['id'=>$document,'scan_status'=>$d['scan_status'],'verification_status'=>$d['verification_status']]]);}
public function access(Request$r,string$document,SignedUrlAdapter$urls){$d=$r->validate(['purpose'=>'required|string|max:64']);$doc=Document::where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$document)->where('scan_status','CLEAN')->first();abort_unless($doc,404);$signed=$urls->sign($doc,self::ACCESS_TTL_SECONDS);DB::table('document_access_log')->insert(['document_id'=>$document,'actor_id'=>$r->user()->id,'action'=>'READ','purpose'=>$d['purpose'],'request_id'=>$r->header('X-Request-Id',(string)Str::uuid()),'occurred_at'=>now()]);return response()->json(['data'=>['id'=>$document,'url'=>$signed->url,'expires_at'=>$signed->expiresAt,'expires_in_seconds'=>self::ACCESS_TTL_SECONDS]]);}}
