<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Customers;
use App\Application\Customers\AttributionService;use App\Application\Identity\OwnershipScope;use App\Application\Customers\CustomerService;use App\Application\Customers\PartyService;use App\Application\Privacy\ConsentService;use App\Models\Partner;use App\Models\Party;use App\Models\Tenant;use App\Models\TenantCustomer;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
final class CustomerController
{
public function index(Request$r,OwnershipScope$own):JsonResponse{$own->requireTenantWide($r->user(),'customers.read');$tenant=app(\App\Domain\Tenancy\TenantContext::class)->id();$q=$own->apply(TenantCustomer::with(['party.contacts'])->where('tenant_id',$tenant),$r->user());if($r->filled('search'))$q->whereHas('party',fn($x)=>$x->where('display_name','ilike','%'.str_replace(['%','_'],['\%','\_'],$r->string('search')).'%'));return response()->json(['data'=>$q->latest()->paginate(min($r->integer('per_page',25),100))]);}
public function store(Request$r,PartyService$parties,CustomerService$customers,ConsentService$consents,AttributionService$attributions):JsonResponse{$d=$r->validate(['type'=>'required|in:PERSON,ORGANIZATION','display_name'=>'required|string|max:160','phone_e164'=>['required','regex:/^\+[1-9]\d{7,14}$/'],'email'=>'nullable|email|max:190','identifier_type'=>'nullable|required_with:identifier_value|in:NATIONAL_ID,PASSPORT,RCCM','identifier_value'=>'nullable|required_with:identifier_type|string|max:100','consent'=>'required|accepted','notice_version'=>'required|string|max:32','origin_type'=>'required|in:SYSTEM,AGENT,BROKER','partner_id'=>'nullable|required_unless:origin_type,SYSTEM|uuid|exists:partners,id','evidence_reference'=>'required|string|max:255']);$tenant=Tenant::findOrFail(app(\App\Domain\Tenancy\TenantContext::class)->id());$result=DB::transaction(function()use($d,$r,$parties,$customers,$consents,$attributions,$tenant){$partyId=DB::table('party_contacts')->where(['type'=>'PHONE','normalized_value'=>$d['phone_e164']])->value('party_id');$party=$partyId?Party::findOrFail($partyId):$parties->create($d);$customer=TenantCustomer::where(['tenant_id'=>$tenant->id,'party_id'=>$party->id])->first()??$customers->register($tenant,$party);$consents->grant($party,$tenant,'INSURANCE_SERVICES',$d['notice_version'],'ASSISTED',['affirmed'=>true,'reference'=>$d['evidence_reference']],$r->user());$attribution=$attributions->lockOrPreserve($party,isset($d['partner_id'])?Partner::findOrFail($d['partner_id']):null,$d['origin_type'],$d['notice_version'],$d['evidence_reference'],$r->user());return['id'=>$customer->id,'party_id'=>$party->id,'customer_number'=>$customer->customer_number,'attribution_id'=>$attribution->id,'origin_preserved'=>$attribution->origin_type!==$d['origin_type']||$attribution->partner_id!==($d['partner_id']??null)];});return response()->json(['data'=>$result],201);}
public function show(Request$r,string$customer,OwnershipScope$own):JsonResponse{$own->requireTenantWide($r->user(),'customers.read');$row=$own->apply(TenantCustomer::with(['party.contacts','party.identifiers','party.consents','party.attributions.partner.party'])->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id()),$r->user())->findOrFail($customer);return response()->json(['data'=>$row]);}
public function transition(Request$r,TenantCustomer$customer,CustomerService$s):JsonResponse{abort_unless($customer->tenant_id===app(\App\Domain\Tenancy\TenantContext::class)->id(),404);$d=$r->validate(['status'=>'required|in:ACTIVE,SUSPENDED,ARCHIVED','reason'=>'required|string|max:64','notes'=>'required|string|min:10|max:1000']);return response()->json(['data'=>$s->transition($customer,$d['status'],$d['reason'],$d['notes'],$r->user())]);}
}
