import { create } from 'zustand';
import * as Crypto from 'expo-crypto';
import { InsuranceApi, Payment, Policy, Proposal, Quote, QuoteOffer, TokenVault } from '@/api/client';
type Network='mtn_momo'|'orange_money';
type State={product:string|null;riskFacts:Record<string,unknown>;quote:Quote|null;offers:QuoteOffer[];selectedOffer:QuoteOffer|null;proposal:Proposal|null;payment:Payment|null;policy:Policy|null;busy:boolean;error:string|null;setProduct:(v:string)=>void;setRiskFacts:(v:Record<string,unknown>)=>void;setQuoteResult:(q:Quote,o:QuoteOffer[])=>void;submitQuote:(customerId:string)=>Promise<void>;selectOffer:(v:QuoteOffer)=>Promise<void>;setProposal:(v:Proposal)=>void;requestPayment:(v:Network,p:string)=>Promise<void>;recoverPayment:()=>Promise<Payment|null>;refreshPayment:()=>Promise<Payment>;setPolicy:(v:Policy)=>void;clear:()=>void;clearError:()=>void};
const initial={product:null,riskFacts:{},quote:null,offers:[],selectedOffer:null,proposal:null,payment:null,policy:null,busy:false,error:null};
export const useInsurance=create<State>((set,get)=>({...initial,setProduct:(product)=>set({...initial,product}),setRiskFacts:(riskFacts)=>set({riskFacts}),setQuoteResult:(quote,offers)=>set({quote,offers}),
 async submitQuote(customerId){set({busy:true,error:null});try{const line_code=String(get().product??'').toUpperCase();if(!line_code)throw new Error('Choose an insurance product.');const quote=await InsuranceApi.createQuote({customer_id:customerId,line_code,channel:'B2C',risk_facts:get().riskFacts});const result=await InsuranceApi.rateQuote(quote.id);set({quote:result.quote,offers:result.offers,busy:false});}catch(e){set({busy:false,error:e instanceof Error?e.message:'Quote unavailable.'});throw e;}},
 async selectOffer(selectedOffer){const quote=get().quote;if(!quote)throw new Error('Quote context is missing.');set({busy:true,error:null});try{await InsuranceApi.acceptOffer(quote.id,selectedOffer.id);set({selectedOffer,busy:false});}catch(e){set({busy:false,error:e instanceof Error?e.message:'Offer could not be selected.'});throw e;}},
 setProposal:(proposal)=>set({proposal}),
 async requestPayment(provider,payer_phone_e164){const proposal=get().proposal;if(!proposal)throw new Error('Proposal is not ready for payment.');set({busy:true,error:null});try{const created=await InsuranceApi.createPayment({proposal_id:proposal.id,provider,payer_phone_e164,idempotency_key:Crypto.randomUUID()+Crypto.randomUUID()});await TokenVault.setPendingPayment(created.id);const payment=await InsuranceApi.initiatePayment(created.id);set({payment,busy:false});}catch(e){set({busy:false,error:e instanceof Error?e.message:'Payment request failed.'});throw e;}},
 async recoverPayment(){const id=await TokenVault.pendingPayment();if(!id)return null;const payment=await InsuranceApi.payment(id);set({payment});return payment;},
 async refreshPayment(){const current=get().payment;if(!current)throw new Error('Payment reference is missing.');const payment=await InsuranceApi.payment(current.id);set({payment});if(['FAILED','EXPIRED'].includes(payment.status))await TokenVault.clearPendingPayment();return payment;},
 setPolicy:(policy)=>set({policy}),clear:()=>set(initial),clearError:()=>set({error:null})}));
