<?php
namespace App\Filament\Admin\Resources\Branches;
use App\Filament\Admin\Resources\Branches\Pages;use App\Models\TenantBranch;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class BranchResource extends Resource
{
protected static?string$model=TenantBranch::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedMapPin;protected static?string$navigationLabel='Branches';protected static?int$navigationSort=12;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Branch identity')->columns(2)->schema([Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload()->required(),Forms\Components\TextInput::make('code')->required()->maxLength(40),Forms\Components\TextInput::make('name')->required()->maxLength(160),Forms\Components\Select::make('status')->options(['ACTIVE'=>'Active','SUSPENDED'=>'Suspended','CLOSED'=>'Closed'])->required()->native(false),Forms\Components\Select::make('manager_user_id')->relationship('manager','full_name')->searchable()->preload(),Forms\Components\TextInput::make('timezone')->default('Africa/Douala')->required()]),\Filament\Schemas\Components\Section::make('Contact')->columns(2)->schema([Forms\Components\TextInput::make('phone_e164')->tel(),Forms\Components\TextInput::make('email')->email(),Forms\Components\TextInput::make('address.city')->label('City'),Forms\Components\TextInput::make('address.line1')->label('Street / landmark')])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('name')->searchable()->sortable()->description(fn(TenantBranch$b)=>$b->code),Tables\Columns\TextColumn::make('tenant.legal_name')->label('Organization')->searchable(),Tables\Columns\TextColumn::make('manager.full_name')->label('Manager')->placeholder('Unassigned'),Tables\Columns\TextColumn::make('memberships_count')->counts('memberships')->label('Members'),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'ACTIVE'=>'success','SUSPENDED'=>'warning',default=>'gray'})])->filters([Tables\Filters\SelectFilter::make('status')->options(['ACTIVE'=>'Active','SUSPENDED'=>'Suspended','CLOSED'=>'Closed'])])->recordActions([Actions\ViewAction::make(),Actions\EditAction::make()])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No branches yet')->emptyStateDescription('Create operational offices and assign their managers.')->emptyStateIcon(Heroicon::OutlinedMapPin);}
public static function getPages():array{return['index'=>Pages\ListBranches::route('/'),'create'=>Pages\CreateBranch::route('/create'),'view'=>Pages\ViewBranch::route('/{record}'),'edit'=>Pages\EditBranch::route('/{record}/edit')];}}
