<?php
namespace App\Filament\Admin\Resources\PartnerLicences;
use App\Application\Partners\LicensingService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\PartnerLicences\Pages;use App\Models\Partner;use App\Models\PartnerLicence;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Infolists;use Filament\Notifications\Notification;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class PartnerLicenceResource extends Resource
{
protected static?string$model=PartnerLicence::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedDocumentCheck;protected static string|\UnitEnum|null$navigationGroup='Customers & partners';protected static?string$navigationLabel='Broker & agent licences';protected static?int$navigationSort=23;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Regulatory licence')->columnSpanFull()->columns(2)->schema([Forms\Components\Select::make('partner_id')->relationship('partner','id')->getOptionLabelFromRecordUsing(fn($record)=>$record->party?->display_name.' · '.$record->type)->getSearchResultsUsing(fn(string$search)=>Partner::query()->whereHas('party',fn($q)=>$q->where('display_name','like',"%{$search}%"))->with('party')->limit(50)->get()->mapWithKeys(fn(Partner$p)=>[$p->id=>$p->party?->display_name.' · '.$p->type]))->searchable()->preload()->required(),Forms\Components\TextInput::make('authority')->default('MINFI')->required()->maxLength(64),Forms\Components\Select::make('licence_type')->options(['BROKER'=>'Broker licence','AGENT_MANDATE'=>'Agent mandate','CARRIER_AUTHORIZATION'=>'Carrier authorization'])->required()->native(false),Forms\Components\TextInput::make('licence_number')->required()->maxLength(100),Forms\Components\DatePicker::make('issued_on'),Forms\Components\DatePicker::make('expires_on')->after('issued_on')])]);}
public static function infolist(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Regulatory licence')->columnSpanFull()->columns(2)->schema([Infolists\Components\TextEntry::make('partner.party.display_name')->label('Partner'),Infolists\Components\TextEntry::make('partner.type')->label('Partner type')->badge(),Infolists\Components\TextEntry::make('authority')->badge(),Infolists\Components\TextEntry::make('licence_type')->label('Licence type'),Infolists\Components\TextEntry::make('licence_number')->label('Licence number')->copyable(),Infolists\Components\TextEntry::make('status')->badge()->color(fn(string$state)=>match($state){'VERIFIED'=>'success','PENDING_VERIFICATION'=>'warning','REJECTED'=>'danger',default=>'gray'}),Infolists\Components\TextEntry::make('issued_on')->label('Issued')->date()->placeholder('—'),Infolists\Components\TextEntry::make('expires_on')->label('Expires')->date()->placeholder('—')->color(fn(PartnerLicence$record)=>$record->expires_on?->isPast()?'danger':null),Infolists\Components\TextEntry::make('verification_notes')->label('Verification notes')->placeholder('—')->columnSpanFull()])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('partner.party.display_name')->label('Partner')->searchable(),Tables\Columns\TextColumn::make('partner.type')->label('Type')->badge(),Tables\Columns\TextColumn::make('authority')->badge(),Tables\Columns\TextColumn::make('licence_number')->searchable()->copyable(),Tables\Columns\TextColumn::make('expires_on')->date()->color(fn(PartnerLicence$l)=>$l->expires_on?->isPast()?'danger':null),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'VERIFIED'=>'success','PENDING_VERIFICATION'=>'warning','REJECTED'=>'danger',default=>'gray'})])->filters([Tables\Filters\SelectFilter::make('status')->options(['PENDING_VERIFICATION'=>'Pending verification','VERIFIED'=>'Verified','REJECTED'=>'Rejected'])])->recordActions([Actions\ViewAction::make(),Actions\Action::make('decide')->label('Review licence')->visible(fn(PartnerLicence$l)=>$l->status==='PENDING_VERIFICATION')->schema([Forms\Components\Radio::make('decision')->options(['VERIFIED'=>'Verify','REJECTED'=>'Reject'])->required(),Forms\Components\Textarea::make('notes')->required()->minLength(20)])->action(function(PartnerLicence$l,array$data){if(ServiceValidation::run(fn()=>app(LicensingService::class)->decide($l,$data['decision'],$data['notes'],auth()->user()))===null)return;Notification::make()->title('Licence decision recorded')->success()->send();})])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No licence submissions')->emptyStateDescription('Submit a MINFI/CIMA licence with supporting evidence for independent review.')->emptyStateIcon(Heroicon::OutlinedDocumentCheck);}
public static function getPages():array{return['index'=>Pages\ListPartnerLicences::route('/'),'create'=>Pages\CreatePartnerLicence::route('/create'),'view'=>Pages\ViewPartnerLicence::route('/{record}')];}}
