<?php

declare(strict_types=1);

namespace App\Application\Operations;

use App\Models\RecoveryExercise;
use Illuminate\Routing\Route as RouteDef;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Symfony\Component\Finder\Finder;

/**
 * Agent B6 — REQ-OPS-004 production-readiness report. Only criteria a machine can verify are evaluated; anything
 * needing human judgement is out of scope here and belongs to release sign-off. Result: PASS / FAIL / N/A per
 * criterion, per module (every folder under app/Application) plus platform-level operational criteria.
 */
final class ProductionReadinessReport
{
    public const PASS = 'PASS';

    public const FAIL = 'FAIL';

    public const NA = 'N/A';

    public const MODULE_CRITERIA = [
        'tests' => 'At least one test under tests/ references the module namespace.',
        'routes_permissioned' => 'Every API route served by the module carries a permission: middleware.',
        'audited' => 'Module code writes to the audit log (AuditWriter).',
    ];

    public function __construct(private SystemHealthService $health) {}

    /** @return array{generated_at:string, platform:list<array>, modules:array<string, array<string, array{status:string, detail:string}>>, summary:array} */
    public function build(): array
    {
        $testsBlob = $this->filesBlob(base_path('tests'));
        $routes = collect(Route::getRoutes()->getRoutes())->filter(fn (RouteDef $r) => str_starts_with($r->uri(), 'api/'));
        $modules = [];
        foreach ((new Finder)->directories()->in(app_path('Application'))->depth(0)->sortByName() as $dir) {
            $name = $dir->getFilename();
            $ns = 'App\\Application\\'.$name.'\\';
            $code = $this->filesBlob($dir->getRealPath());
            $modRoutes = $routes->filter(fn (RouteDef $r) => str_starts_with(ltrim($r->getActionName(), '\\'), $ns));
            $unguarded = $modRoutes->reject(fn (RouteDef $r) => collect($r->gatherMiddleware())->contains(fn ($m) => is_string($m) && str_starts_with($m, 'permission:')));
            $modules[$name] = [
                'tests' => str_contains($testsBlob, $ns) || str_contains($testsBlob, 'App\\\\Application\\\\'.$name.'\\\\')
                    ? $this->r(self::PASS, 'referenced by tests') : $this->r(self::FAIL, 'no test references '.$ns),
                'routes_permissioned' => $modRoutes->isEmpty() ? $this->r(self::NA, 'no API routes')
                    : ($unguarded->isEmpty() ? $this->r(self::PASS, $modRoutes->count().' routes guarded') : $this->r(self::FAIL, 'unguarded: '.$unguarded->map(fn ($r) => implode('|', $r->methods()).' '.$r->uri())->take(5)->implode(', '))),
                'audited' => str_contains($code, 'AuditWriter') || str_contains($code, 'auditedCall') ? $this->r(self::PASS, 'uses AuditWriter') : $this->r(self::FAIL, 'no AuditWriter usage'),
            ];
        }

        $platform = $this->platform();
        $all = [...array_column($platform, 'status'), ...collect($modules)->flatMap(fn ($c) => array_column($c, 'status'))->all()];

        return [
            'generated_at' => now()->toIso8601String(),
            'platform' => $platform,
            'modules' => $modules,
            'summary' => ['pass' => count(array_keys($all, self::PASS, true)), 'fail' => count(array_keys($all, self::FAIL, true)), 'na' => count(array_keys($all, self::NA, true))],
        ];
    }

    public function markdown(array $report): string
    {
        $out = ["# Production readiness report", '', '_Generated by `php artisan ops:readiness-report` at '.$report['generated_at'].'. Automatable criteria only (REQ-OPS-004); do not edit by hand._', '',
            sprintf('**Summary:** %d pass, %d fail, %d n/a.', $report['summary']['pass'], $report['summary']['fail'], $report['summary']['na']), '',
            '## Platform', '', '| Criterion | Status | Detail |', '|---|---|---|'];
        foreach ($report['platform'] as $p) {
            $out[] = "| {$p['criterion']} | {$p['status']} | ".$this->cell($p['detail']).' |';
        }
        $out = [...$out, '', '## Modules', '', 'Criteria: '.implode(' ', array_map(fn ($k, $v) => "`{$k}` — {$v}", array_keys(self::MODULE_CRITERIA), self::MODULE_CRITERIA)), '',
            '| Module | '.implode(' | ', array_keys(self::MODULE_CRITERIA)).' |', '|---|'.str_repeat('---|', count(self::MODULE_CRITERIA))];
        foreach ($report['modules'] as $name => $c) {
            $out[] = "| {$name} | ".implode(' | ', array_map(fn ($k) => $c[$k]['status'], array_keys(self::MODULE_CRITERIA))).' |';
        }
        $fails = collect($report['modules'])->flatMap(fn ($c, $m) => collect($c)->filter(fn ($x) => $x['status'] === self::FAIL)->map(fn ($x, $k) => "- **{$m}** `{$k}`: ".$this->cell($x['detail']))->values());
        if ($fails->isNotEmpty()) {
            $out = [...$out, '', '## Module failures', '', ...$fails->all()];
        }

        return implode("\n", $out)."\n";
    }

    private function platform(): array
    {
        $h = $this->health->summary()['checks'];
        $dr = (array) config('operations.dr');
        $maxAge = (int) config('operations.readiness.restore_evidence_max_age_days', 90);
        $restore = Schema::hasTable('recovery_exercises') ? RecoveryExercise::query()->where('exercise_type', 'BACKUP_RESTORE')->where('status', RestoreVerificationService::PASSED)
            ->where('conducted_at', '>=', now()->subDays($maxAge))->latest('conducted_at')->first() : null;

        return [
            $this->p('Database reachable', $h['database']['status'] === SystemHealthService::OK, $h['database']['status']),
            $this->p('No pending migrations', ($h['database']['pending_migrations'] ?? 1) === 0, 'pending: '.($h['database']['pending_migrations'] ?? 'unknown')),
            $this->p('Scheduler heartbeat fresh', $h['scheduler']['status'] === SystemHealthService::OK, $h['scheduler']['reason'] ?? ('age '.($h['scheduler']['age_seconds'] ?? '?').'s')),
            $this->p('Storage writable', $h['storage']['status'] === SystemHealthService::OK, (string) ($h['storage']['disk'] ?? '')),
            $this->p('No failed queue jobs in 24h', ($h['queue']['failed_jobs_24h'] ?? 1) === 0, 'failed 24h: '.($h['queue']['failed_jobs_24h'] ?? 'unknown')),
            $this->p('Mail channel configured', $h['mail']['status'] !== SystemHealthService::NOT_CONFIGURED, $h['mail']['status']),
            $this->p('RPO/RTO targets configured', ($dr['target_rpo_minutes'] ?? null) !== null && ($dr['target_rto_minutes'] ?? null) !== null, 'owner setting OPS_DR_TARGET_RPO_MINUTES / OPS_DR_TARGET_RTO_MINUTES'),
            $this->p("Passed restore verification within {$maxAge} days", $restore !== null, $restore ? 'last passed '.$restore->conducted_at?->toIso8601String() : 'none (run ops:verify-restore)'),
        ];
    }

    private function p(string $criterion, bool $ok, string $detail): array
    {
        return ['criterion' => $criterion, 'status' => $ok ? self::PASS : self::FAIL, 'detail' => $detail];
    }

    private function r(string $status, string $detail): array
    {
        return ['status' => $status, 'detail' => $detail];
    }

    private function cell(string $s): string
    {
        return str_replace(['|', "\n"], ['\\|', ' '], Str::limit($s, 300));
    }

    private function filesBlob(string $dir): string
    {
        $blob = '';
        foreach ((new Finder)->files()->in($dir)->name('*.php') as $f) {
            $blob .= $f->getContents()."\n";
        }

        return $blob;
    }
}
