<?php
namespace App\Filament\Admin\Resources\PaymentRequests;use App\Domain\Tenancy\TenantContext;use App\Filament\Admin\Resources\PaymentRequests\Pages;use App\Models\PaymentIntentRecord;use BackedEnum;use Filament\Actions;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
final class PaymentRequestResource extends Resource{protected static?string$model=PaymentIntentRecord::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedDevicePhoneMobile;protected static string|\UnitEnum|null$navigationGroup='Sales workspace';protected static?int$navigationSort=43;public static function getEloquentQuery():Builder{return parent::getEloquentQuery()->where('tenant_id',app(TenantContext::class)->id());}public static function form(Schema$s):Schema{return$s->components([]);}
    /** Canonical UI handoff: persistent payment state panel (explicit state, network, phone, amount, timeout, recovery guidance). Read-only. */
    public static function infolist(Schema$s):Schema{return$s->components([\App\Filament\Shared\Components\RecordShell::detailHeader(),\App\Filament\Shared\Components\RecordShell::paymentState(fn($r)=>[
        'status'=>(string)$r->status,
        'state'=>match((string)$r->status){'PENDING_CUSTOMER','PENDING','CREATED','INITIATED'=>'PENDING','PROCESSING'=>'PROCESSING','SUCCEEDED'=>'SUCCEEDED','FAILED'=>'FAILED','EXPIRED'=>'EXPIRED','CANCELLED'=>'CANCELLED',default=>'UNKNOWN'},
        'network'=>(string)$r->provider,'phone'=>(string)$r->payer_phone_e164,'reference'=>$r->provider_reference,
        'started_at'=>$r->created_at?->toDateTimeString(),'timeout_at'=>$r->expires_at?->toDateTimeString(),
        'currency'=>(string)$r->currency,'lines'=>['gross_premium'=>(int)$r->amount_minor],'total'=>(int)$r->amount_minor,
    ]),\App\Filament\Shared\Components\RecordShell::timeline('payment_intent')]);}public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('proposal.proposal_number')->label('Proposal')->searchable(),Tables\Columns\TextColumn::make('payer_phone_e164')->label('Payer'),Tables\Columns\TextColumn::make('provider')->badge(),Tables\Columns\TextColumn::make('amount_minor')->money(fn($record)=>$record->currency,divideBy:100),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'SUCCEEDED'=>'success','FAILED','EXPIRED'=>'danger','PENDING_CUSTOMER','PROCESSING'=>'warning',default=>'info'}),Tables\Columns\TextColumn::make('expires_at')->dateTime()])->recordActions([Actions\ViewAction::make()])->emptyStateHeading('No payment requests')->emptyStateDescription('Approved proposals can trigger customer-authorized Mobile Money requests.')->emptyStateIcon(Heroicon::OutlinedDevicePhoneMobile);}public static function getPages():array{return['index'=>Pages\ListPaymentRequests::route('/'),'view'=>Pages\ViewPaymentRequest::route('/{record}')];}}
