import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Check, ShieldAlert } from 'lucide-react-native';
import { AppHeader, Button, Card, Screen, StatusChip } from '@/components/ui';
import { useInsurance } from '@/store/insurance';
import { colors, space, type } from '@/theme/tokens';
export default function Disclosure(){const proposal=useInsurance(s=>s.proposal);const[accepted,setAccepted]=useState(false);if(!proposal)return <Screen><AppHeader title="Proposal" back/><Card><Text style={styles.title}>Proposal context is missing.</Text><Text style={styles.body}>Return to the quote and select a current server offer.</Text></Card></Screen>;const payable=proposal.status==='PAYMENT_PENDING';return <Screen><AppHeader title="Documents & declaration" subtitle="Step 4 of 5 · Server-governed" back/><Card><StatusChip label={proposal.status.replaceAll('_',' ')} tone={payable?'success':'warning'}/><Text style={styles.title}>Proposal {proposal.proposal_number}</Text><Text style={styles.body}>{payable?'Underwriting and required evidence are complete. Review the declaration before payment.':'Laravel has not released this proposal for payment. Complete the required disclosure, evidence and underwriting workflow first.'}</Text></Card>{payable?<><Card><Text style={styles.title}>Your declaration</Text><Pressable accessibilityRole="checkbox" accessibilityState={{checked:accepted}} style={styles.consent} onPress={()=>setAccepted(!accepted)}><View style={[styles.box,accepted&&styles.checked]}>{accepted?<Check size={16} color={colors.white}/>:null}</View><Text style={styles.body}>I confirm the information is accurate and accept the server-versioned proposal, exclusions, privacy notice and policy terms.</Text></Pressable></Card><Button label="Review price and pay" disabled={!accepted} onPress={()=>router.push('/checkout')}/></>:<Card><ShieldAlert size={24} color={colors.warningText}/><Text style={styles.body}>Answer the carrier disclosure questions so underwriting can release this proposal for payment.</Text><Button label="Answer disclosure questions" onPress={()=>router.push({pathname:'/quote/questions',params:{proposalId:proposal.id}})}/></Card>}</Screen>}
const styles=StyleSheet.create({title:{...type.cardTitle,color:colors.navy950},body:{...type.body,color:colors.neutral700,flex:1},consent:{flexDirection:'row',alignItems:'flex-start',gap:space.x3},box:{width:24,height:24,borderRadius:6,borderWidth:1,borderColor:colors.neutral300,alignItems:'center',justifyContent:'center'},checked:{backgroundColor:colors.blue600,borderColor:colors.blue600}});
