import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Info } from 'lucide-react-native';
import { AppHeader, Button, Card, Money, Screen, StatusChip } from '@/components/ui';
import { useInsurance } from '@/store/insurance';
import { InsuranceApi } from '@/api/client';
import { colors, space, type } from '@/theme/tokens';
const major=(n:number)=>n/100;
export default function Offers(){const offers=useInsurance(s=>s.offers);const quote=useInsurance(s=>s.quote);const busy=useInsurance(s=>s.busy);const error=useInsurance(s=>s.error);const choose=useInsurance(s=>s.selectOffer);const setProposal=useInsurance(s=>s.setProposal);const select=async(id:string)=>{const offer=offers.find(o=>o.id===id);if(!offer||!quote)return;try{await choose(offer);setProposal(await InsuranceApi.createProposal({quote_offer_id:offer.id,party_id:quote.party_id}));router.push('/quote/disclosure');}catch{}};return <Screen><AppHeader title="Available offers" subtitle="Step 3 of 5 · Live carrier results" back/><View style={styles.notice}><Info size={17} color={colors.blue700}/><Text style={styles.noticeText}>Compare cover and exclusions—not price alone.</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}{offers.length===0?<Card><Text style={styles.title}>No eligible offer was returned.</Text><Text style={styles.meta}>Change the risk details or contact support. No substitute price will be shown.</Text></Card>:offers.map((o,i)=><Card key={o.id} feature><StatusChip label={i===0?'Lowest returned total':'Eligible offer'} tone={i===0?'success':'info'}/><Text style={styles.carrier}>{o.carrier?.party?.display_name??'Licensed insurance carrier'}</Text><Text style={styles.title}>{o.product?.name??'Insurance offer'}</Text><Money amount={major(o.total_minor)} size="large"/><Text style={styles.meta}>Total payable · valid until {new Date(o.valid_until).toLocaleDateString()}</Text><Button label="Select this offer" loading={busy} onPress={()=>void select(o.id)}/></Card>)}</Screen>}
const styles=StyleSheet.create({notice:{flexDirection:'row',gap:space.x2,backgroundColor:colors.blue50,padding:space.x3,borderRadius:10},noticeText:{...type.meta,color:colors.blue700,flex:1},carrier:{...type.meta,color:colors.neutral600},title:{...type.cardTitle,color:colors.navy950},meta:{...type.meta,color:colors.neutral600},error:{...type.meta,color:colors.dangerText}});
