import React,{useMemo,useState}from'react';import{StyleSheet,Text}from'react-native';import{router}from'expo-router';import{AppHeader,Button,Card,Screen,TextField}from'@/components/ui';import{useInsurance}from'@/store/insurance';import{useSession}from'@/store/session';import{colors,type}from'@/theme/tokens';
type Field={key:string;label:string;placeholder:string;keyboard?:'default'|'number-pad';numeric?:boolean};
const schemas:Record<string,{title:string;fields:Field[]}>= {
 motor:{title:'Tell us about the vehicle',fields:[{key:'registration_number',label:'Registration number',placeholder:'LT 000 AA'},{key:'fiscal_power',label:'Fiscal power (CV)',placeholder:'8',keyboard:'number-pad',numeric:true},{key:'usage_type',label:'Usage type',placeholder:'PRIVATE'},{key:'zone',label:'Rating zone',placeholder:'CAMEROON'}]},
 health:{title:'Tell us who needs cover',fields:[{key:'beneficiary_count',label:'Number of people',placeholder:'1',keyboard:'number-pad',numeric:true},{key:'oldest_age',label:'Age of oldest beneficiary',placeholder:'35',keyboard:'number-pad',numeric:true},{key:'coverage_zone',label:'Coverage zone',placeholder:'CAMEROON'},{key:'plan_type',label:'Plan type',placeholder:'INDIVIDUAL or FAMILY'}]},
 travel:{title:'Tell us about the trip',fields:[{key:'destination_country',label:'Destination country',placeholder:'France'},{key:'departure_date',label:'Departure date',placeholder:'2026-10-15'},{key:'return_date',label:'Return date',placeholder:'2026-10-30'},{key:'traveller_count',label:'Number of travellers',placeholder:'1',keyboard:'number-pad',numeric:true}]},
 home:{title:'Tell us about the property',fields:[{key:'property_type',label:'Property type',placeholder:'HOUSE or APARTMENT'},{key:'occupancy',label:'Occupancy',placeholder:'OWNER_OCCUPIED or RENTED'},{key:'city',label:'City',placeholder:'Douala'},{key:'declared_value_minor',label:'Declared value (FCFA)',placeholder:'25000000',keyboard:'number-pad',numeric:true}]},
 life:{title:'Tell us about the protection needed',fields:[{key:'insured_age',label:'Age of insured person',placeholder:'35',keyboard:'number-pad',numeric:true},{key:'cover_amount_minor',label:'Desired cover (FCFA)',placeholder:'10000000',keyboard:'number-pad',numeric:true},{key:'term_years',label:'Term in years',placeholder:'10',keyboard:'number-pad',numeric:true},{key:'purpose',label:'Protection purpose',placeholder:'FAMILY_PROTECTION'}]}
};
export default function Risk(){const product=useInsurance(s=>s.product);const busy=useInsurance(s=>s.busy);const error=useInsurance(s=>s.error);const setFacts=useInsurance(s=>s.setRiskFacts);const submit=useInsurance(s=>s.submitQuote);const customerId=useSession(s=>s.activeWorkspace?.customer_id);const[values,setValues]=useState<Record<string,string>>({});const schema=product?schemas[product]:undefined;const valid=useMemo(()=>!!schema&&schema.fields.every(f=>values[f.key]?.trim()),[schema,values]);const go=async()=>{if(!customerId||!schema)return;const facts=Object.fromEntries(schema.fields.map(f=>[f.key,f.numeric?Number(values[f.key]):values[f.key]?.trim().toUpperCase()]));setFacts(facts);try{await submit(customerId);router.push('/quote/offers')}catch{}};if(!schema)return <Screen><AppHeader title="Cover details" back/><Card><Text style={styles.title}>Choose a supported insurance product first.</Text></Card><Button label="Choose product" onPress={()=>router.replace('/quote/product')}/></Screen>;return <Screen><AppHeader title={schema.title} subtitle="Step 2 of 5 · Used for live rating" back/>{schema.fields.map(field=><TextField key={field.key} label={field.label} value={values[field.key]??''} onChangeText={value=>setValues(v=>({...v,[field.key]:value}))} placeholder={field.placeholder} keyboardType={field.keyboard} autoCapitalize="characters"/>)}{!customerId?<Text style={styles.error}>This workspace has no server-issued customer identity.</Text>:null}{error?<Text style={styles.error}>{error}</Text>:null}<Text style={styles.note}>The server validates these facts against the active product and tariff version. The app never calculates or invents premiums.</Text><Button label="Get live offers" loading={busy} disabled={!customerId||!valid} onPress={()=>void go()}/></Screen>}
const styles=StyleSheet.create({title:{...type.cardTitle,color:colors.navy950},note:{...type.meta,color:colors.neutral600},error:{...type.meta,color:colors.dangerText}});
