<?php
declare(strict_types=1);
namespace App\Application\Privacy;
use App\Application\Audit\AuditWriter;use App\Application\Events\OutboxWriter;use App\Models\Consent;use App\Models\Party;use App\Models\Tenant;use App\Models\User;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class ConsentService
{
public function __construct(private readonly AuditWriter$audit,private readonly OutboxWriter$outbox){}
public function grant(Party$party,?Tenant$tenant,string$purpose,string$notice,string$channel,array$evidence,?User$actor):Consent{return DB::transaction(function()use($party,$tenant,$purpose,$notice,$channel,$evidence,$actor){Consent::where(['party_id'=>$party->id,'tenant_id'=>$tenant?->id,'purpose'=>$purpose,'status'=>'GRANTED'])->each(fn(Consent$c)=>$this->change($c,'EXPIRED','SUPERSEDED_NOTICE',['new_notice_version'=>$notice],$actor));$hash=$this->hash($evidence);$c=Consent::create(['party_id'=>$party->id,'tenant_id'=>$tenant?->id,'purpose'=>$purpose,'notice_version'=>$notice,'status'=>'GRANTED','channel'=>$channel,'captured_by'=>$actor?->id,'given_at'=>now(),'evidence'=>$evidence,'evidence_hash'=>$hash]);$this->event($c,null,'GRANTED','AFFIRMATIVE_ACTION',$evidence,$actor);$this->audit->record('privacy.consent.granted','consent',$c->id,['party_id'=>$party->id,'purpose'=>$purpose,'notice_version'=>$notice]);$this->outbox->record('privacy.consent.changed','consent',$c->id,['consent_id'=>$c->id,'status'=>'GRANTED','purpose'=>$purpose]);return$c;});}
public function withdraw(Consent$c,string$reason,array$evidence,?User$actor):Consent{if($c->status!=='GRANTED')throw ValidationException::withMessages(['status'=>__('wave1.consent_not_active')]);return DB::transaction(function()use($c,$reason,$evidence,$actor){$this->change($c,'WITHDRAWN',$reason,$evidence,$actor);$this->audit->record('privacy.consent.withdrawn','consent',$c->id,['purpose'=>$c->purpose],$reason);$this->outbox->record('privacy.consent.changed','consent',$c->id,['consent_id'=>$c->id,'status'=>'WITHDRAWN','purpose'=>$c->purpose]);return$c->refresh();});}
private function change(Consent$c,string$to,string$reason,array$evidence,?User$actor):void{$from=$c->status;$c->update(['status'=>$to,'withdrawn_at'=>$to==='WITHDRAWN'?now():$c->withdrawn_at]);$this->event($c,$from,$to,$reason,$evidence,$actor);}
private function event(Consent$c,?string$from,string$to,string$reason,array$evidence,?User$actor):void{$c->events()->create(['from_status'=>$from,'to_status'=>$to,'reason_code'=>$reason,'actor_id'=>$actor?->id,'evidence'=>$evidence,'evidence_hash'=>$this->hash($evidence),'occurred_at'=>now()]);}
private function hash(array$evidence):string{ksort($evidence);return hash('sha256',json_encode($evidence,JSON_THROW_ON_ERROR));}
}
