<?php
use App\Interfaces\Http\Controllers\Api\V1\FinancialDistribution\FinancialDistributionController as F;
use Illuminate\Support\Facades\Route;
Route::prefix('v1')->middleware(['auth:api','tenant'])->group(function():void{
 Route::post('financial-distribution/commission-rules',[F::class,'createRule'])->middleware('permission:commission.manage'); Route::post('financial-distribution/commission-rules/{rule}/approve',[F::class,'approveRule'])->middleware('permission:commission.approve'); Route::post('financial-distribution/commissions/accrue',[F::class,'accrue'])->middleware('permission:commission.accrue'); Route::post('financial-distribution/commissions/{accrual}/vest',[F::class,'vest'])->middleware('permission:commission.vest'); Route::post('financial-distribution/commissions/{accrual}/clawback',[F::class,'clawback'])->middleware('permission:commission.clawback');
 Route::post('partner-statements',[F::class,'prepareStatement'])->middleware('permission:statements.prepare'); Route::post('partner-statements/{statement}/approve',[F::class,'approveStatement'])->middleware('permission:statements.approve'); Route::post('partner-statements/{statement}/publish',[F::class,'publishStatement'])->middleware('permission:statements.publish');
 Route::post('partner-statements/{statement}/payouts',[F::class,'requestPayout'])->middleware('permission:payout.request'); Route::post('partner-payouts/{payout}/approve',[F::class,'approvePayout'])->middleware('permission:payout.approve'); Route::post('partner-payouts/{payout}/process',[F::class,'processPayout'])->middleware('permission:payout.process'); Route::post('partner-payouts/{payout}/complete',[F::class,'completePayout'])->middleware('permission:payout.process'); Route::post('partner-payouts/{payout}/fail',[F::class,'failPayout'])->middleware('permission:payout.process'); Route::post('partner-payouts/{payout}/reverse',[F::class,'reversePayout'])->middleware('permission:payout.reverse');
 Route::post('carrier-settlements',[F::class,'prepareSettlement'])->middleware('permission:settlement.prepare'); Route::post('carrier-settlements/{settlement}/approve',[F::class,'approveSettlement'])->middleware('permission:settlement.approve'); Route::post('carrier-settlements/{settlement}/submit',[F::class,'submitSettlement'])->middleware('permission:settlement.submit'); Route::post('carrier-settlements/{settlement}/paid',[F::class,'paidSettlement'])->middleware('permission:settlement.confirm'); Route::post('carrier-settlements/{settlement}/fail',[F::class,'failSettlement'])->middleware('permission:settlement.confirm'); Route::post('carrier-settlements/{settlement}/reverse',[F::class,'reverseSettlement'])->middleware('permission:settlement.reverse');
 Route::post('bordereaux',[F::class,'prepareBordereau'])->middleware('permission:bordereaux.prepare'); Route::post('bordereaux/{bordereau}/approve',[F::class,'approveBordereau'])->middleware('permission:bordereaux.approve'); Route::post('bordereaux/{bordereau}/submit',[F::class,'submitBordereau'])->middleware('permission:bordereaux.submit'); Route::post('bordereaux/{bordereau}/acknowledge',[F::class,'acknowledgeBordereau'])->middleware('permission:bordereaux.confirm'); Route::post('bordereaux/{bordereau}/reject',[F::class,'rejectBordereau'])->middleware('permission:bordereaux.confirm');
});
