<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Claims;
use App\Application\Claims\{ClaimCarrierExchangeService,ClaimEvidenceService,ClaimLifecycleService,ClaimPaymentService};use App\Models\{Claim,ClaimDecision,ClaimPayment,ClaimReserveChange,Document,User};use Illuminate\Http\Request;
final class ClaimLifecycleController{
public function index(Request$r){return response()->json(['data'=>Claim::where('tenant_id',$this->tenant())->with(['policy','claimant','assignee'])->latest()->paginate(min((int)$r->input('per_page',25),100))]);}
public function show(string$id){$c=$this->claim($id);return response()->json(['data'=>$c->load(['policy','claimant','assignee','reserves','decisions','payments','disputes','recoveries'])]);}
public function fnol(Request$r,ClaimLifecycleService$s){$d=$r->validate(['policy_id'=>'required|uuid','claimant_party_id'=>'required|uuid','loss_occurred_at'=>'required|date|before_or_equal:now','loss_details'=>'required|array','loss_location'=>'nullable|string|max:255','estimated_loss_minor'=>'nullable|integer|min:0','priority'=>'sometimes|in:LOW,NORMAL,HIGH,CRITICAL','idempotency_key'=>'required|string|min:16|max:128']);return response()->json(['data'=>$s->fnol($this->tenant(),$d,$r->user())],201);}
public function assign(Request$r,string$id,ClaimLifecycleService$s){$d=$r->validate(['assignee_id'=>'required|uuid|exists:users,id','reason_code'=>'required|string|max:64']);return response()->json(['data'=>$s->assign($this->claim($id),User::findOrFail($d['assignee_id']),$d['reason_code'],$r->user())]);}
public function transition(Request$r,string$id,ClaimLifecycleService$s){$d=$r->validate(['to_status'=>'required|in:ACKNOWLEDGED,EVIDENCE_PENDING,ASSESSMENT,CARRIER_REVIEW,CLOSED,REOPENED','reason_code'=>'required|string|max:64','details'=>'sometimes|array']);return response()->json(['data'=>$s->transition($this->claim($id),$d['to_status'],$d['reason_code'],$d['details']??[],$r->user())]);}
public function reserve(Request$r,string$id,\App\Application\Claims\Reserves\ClaimReserveService$s){$d=$r->validate(['amount_minor'=>'required|integer|min:0','reason_code'=>'required|string|max:64','notes'=>'nullable|string|max:2000','reserve_type'=>['nullable',\Illuminate\Validation\Rule::in(\App\Application\Claims\ClaimReferenceCodes::RESERVE_TYPES)],'reserve_head'=>['nullable',\Illuminate\Validation\Rule::in(\App\Application\Claims\Reserves\ClaimReserveService::HEADS)],'coverage_code'=>'nullable|string|max:64','final'=>'sometimes|boolean']);if(!empty($d['reserve_head'])||!empty($d['coverage_code'])||!empty($d['final']))$r->validate(['reason_code'=>[\Illuminate\Validation\Rule::in(\App\Application\Claims\Reserves\ClaimReserveService::REASON_CODES)]]);return response()->json(['data'=>$s->request($this->claim($id),$d,$r->user())],201);}
public function approveReserve(Request$r,string$id,string$reserve,\App\Application\Claims\Reserves\ClaimReserveService$s){$x=ClaimReserveChange::where(['id'=>$reserve,'claim_id'=>$this->claim($id)->id])->firstOrFail();$x=$s->approve($x,$r->user());return response()->json(['data'=>$x],$x->status==='REFERRED'?202:200);}
public function decision(Request$r,string$id,ClaimLifecycleService$s){$d=$r->validate(['decision'=>['required',\Illuminate\Validation\Rule::in(\App\Application\Claims\ClaimReferenceCodes::DECISION_INPUTS)],'approved_amount_minor'=>'required|integer|min:0','reason_code'=>'required|string|max:64','rationale'=>'required|string|min:20|max:5000']);$d['decision']=\App\Application\Claims\ClaimReferenceCodes::decisionForApi($d['decision']);return response()->json(['data'=>$s->proposeDecision($this->claim($id),$d,$r->user())],201);}
public function approveDecision(Request$r,string$id,string$decision,ClaimLifecycleService$s){$x=ClaimDecision::where(['id'=>$decision,'claim_id'=>$id])->firstOrFail();return response()->json(['data'=>$s->approveDecision($x,$r->user())]);}
public function evidence(Request$r,string$id,ClaimEvidenceService$s){$d=$r->validate(['document_id'=>'required|uuid','evidence_type'=>'required|string|max:64','purpose'=>'required|string|max:96']);return response()->json(['data'=>$s->attach($this->claim($id),Document::findOrFail($d['document_id']),$d['evidence_type'],$d['purpose'],$r->user())],201);}
public function verifyEvidence(Request$r,string$id,string$document,ClaimEvidenceService$s){$d=$r->validate(['accepted'=>'required|boolean','purpose'=>'required|string|max:96']);$s->verify($this->claim($id),Document::findOrFail($document),$d['accepted'],$d['purpose'],$r->user());return response()->json(['data'=>['status'=>$d['accepted']?'VERIFIED':'REJECTED']]);}
public function dispute(Request$r,string$id,ClaimLifecycleService$s){$d=$r->validate(['reason_code'=>'required|string|max:64','statement'=>'required|string|min:20|max:5000']);return response()->json(['data'=>$s->openDispute($this->claim($id),$d,$r->user())],201);}
public function resolveDispute(Request$r,string$id,string$dispute,ClaimLifecycleService$s){$d=$r->validate(['resolution'=>'required|string|min:20|max:5000','reassess'=>'required|boolean']);$x=\App\Models\ClaimDispute::where(['id'=>$dispute,'claim_id'=>$id])->firstOrFail();return response()->json(['data'=>$s->resolveDispute($x,$d['resolution'],$d['reassess'],$r->user())]);}
public function recovery(Request$r,string$id,ClaimLifecycleService$s){$d=$r->validate(['type'=>['required',\Illuminate\Validation\Rule::in(\App\Application\Claims\ClaimReferenceCodes::RECOVERY_TYPES)],'counterparty_name'=>'required|string|max:255','target_amount_minor'=>'required|integer|min:0','notes'=>'nullable|string|max:2000']);return response()->json(['data'=>$s->recovery($this->claim($id),$d,$r->user())],201);}
public function recordRecovery(Request$r,string$id,string$recovery,ClaimLifecycleService$s){$d=$r->validate(['amount_minor'=>'required|integer|min:1','close'=>'sometimes|boolean']);$x=\App\Models\ClaimRecovery::where(['id'=>$recovery,'claim_id'=>$id])->firstOrFail();return response()->json(['data'=>$s->recordRecovery($x,$d['amount_minor'],$d['close']??false,$r->user())]);}
public function carrier(Request$r,string$id,ClaimCarrierExchangeService$s){$d=$r->validate(['message_type'=>'required|string|max:48','payload'=>'required|array','idempotency_key'=>'required|string|min:16|max:80']);return response()->json(['data'=>$s->queue($this->claim($id),$d['message_type'],$d['payload'],$d['idempotency_key'],$r->user())],202);}
public function carrierFailed(Request$r,string$id,string$message,ClaimCarrierExchangeService$s){$d=$r->validate(['reason'=>'required|string|max:2000']);$s->markFailure($this->claim($id),$message,$d['reason']);return response()->json(['data'=>['status'=>'RETRY_PENDING']]);}
public function carrierAcknowledged(Request$r,string$id,string$message,ClaimCarrierExchangeService$s){$d=$r->validate(['external_reference'=>'required|string|max:255']);$s->acknowledge($this->claim($id),$message,$d['external_reference']);return response()->json(['data'=>['status'=>'ACKNOWLEDGED']]);}
public function payment(Request$r,string$id,string$decision,ClaimPaymentService$s){$d=$r->validate(['payee_party_id'=>'required|uuid','amount_minor'=>'required|integer|min:1','idempotency_key'=>'required|string|min:16|max:128']);return response()->json(['data'=>$s->request($this->claim($id),ClaimDecision::where(['id'=>$decision,'claim_id'=>$id])->firstOrFail(),$d,$r->user())],201);}
public function approvePayment(Request$r,string$id,string$payment,ClaimPaymentService$s){return response()->json(['data'=>$s->approve(ClaimPayment::where(['id'=>$payment,'claim_id'=>$id])->firstOrFail(),$r->user())]);}
public function processPayment(string$id,string$payment,ClaimPaymentService$s){$this->claim($id);return response()->json(['data'=>$s->processing(ClaimPayment::where(['id'=>$payment,'claim_id'=>$id])->firstOrFail())]);}
public function failPayment(Request$r,string$id,string$payment,ClaimPaymentService$s){$d=$r->validate(['reason'=>'required|string|max:2000']);$this->claim($id);return response()->json(['data'=>$s->fail(ClaimPayment::where(['id'=>$payment,'claim_id'=>$id])->firstOrFail(),$d['reason'])]);}
public function paidPayment(Request$r,string$id,string$payment,ClaimPaymentService$s){$d=$r->validate(['external_reference'=>'required|string|max:255']);$this->claim($id);return response()->json(['data'=>$s->paid(ClaimPayment::where(['id'=>$payment,'claim_id'=>$id])->firstOrFail(),$d['external_reference'])]);}
public function reversePayment(Request$r,string$id,string$payment,ClaimPaymentService$s){$d=$r->validate(['reason'=>'required|string|min:20|max:2000']);return response()->json(['data'=>$s->reverse(ClaimPayment::where(['id'=>$payment,'claim_id'=>$id])->firstOrFail(),$d['reason'],$r->user())]);}
private function claim(string$id):Claim{return Claim::where(['id'=>$id,'tenant_id'=>$this->tenant()])->firstOrFail();}private function tenant():string{return app(\App\Domain\Tenancy\TenantContext::class)->id();}}
