<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Claims;
use App\Application\Audit\AuditWriter;use App\Domain\Claims\ClaimStateMachine;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class ClaimController{
// REQ-CLM-002: no raw insert — the one FNOL path (FnolService → ClaimLifecycleService::fnol) creates the claim, pins CLAIMS_INTAKE and writes the immutable FNOL snapshot.
public function store(Request$r,\App\Application\Claims\Fnol\FnolService$fnol){$d=$r->validate(['policy_id'=>'required|uuid|exists:policies,id','claimant_party_id'=>'required|uuid|exists:parties,id','loss_occurred_at'=>'required|date|before_or_equal:now','loss_details'=>'required|array','loss_location'=>'nullable|string|max:255','estimated_loss_minor'=>'nullable|integer|min:0','idempotency_key'=>'sometimes|string|min:16|max:128']);$d['idempotency_key']=$d['idempotency_key']??($r->header('Idempotency-Key')?:(string)Str::uuid());$c=$fnol->submit(app(\App\Domain\Tenancy\TenantContext::class)->id(),$d,$r->user(),['channel'=>'API','role'=>'STAFF']);return response()->json(['data'=>['id'=>$c->id,'claim_number'=>$c->claim_number,'status'=>$c->status]],201);}
public function show(string$claim){$c=$this->claim($claim);return response()->json(['data'=>['claim'=>$c,'events'=>DB::table('claim_events')->where('claim_id',$claim)->orderBy('occurred_at')->get(),'documents'=>app(\App\Application\Documents\SubjectDocuments::class)->forSubject('CLAIM',$claim)]]);}
public function transition(Request$r,string$claim,ClaimStateMachine$machine,AuditWriter$audit){$d=$r->validate(['to_status'=>'required|in:ACKNOWLEDGED,EVIDENCE_PENDING,ASSESSMENT,CARRIER_REVIEW,APPROVED,PARTIALLY_APPROVED,DECLINED,PAID,DISPUTED,CLOSED','reason_code'=>'required|string|max:64','details'=>'sometimes|array']);$c=$this->claim($claim);$machine->assert($c->status,$d['to_status']);DB::transaction(function()use($c,$d,$claim,$r,$audit){$update=['status'=>$d['to_status'],'updated_at'=>now()];if($d['to_status']==='ACKNOWLEDGED')$update['acknowledged_at']=now();if($d['to_status']==='CLOSED')$update['closed_at']=now();DB::table('claims')->where('id',$claim)->update($update);DB::table('claim_events')->insert(['id'=>(string)Str::uuid(),'claim_id'=>$claim,'type'=>'STATUS_CHANGED','from_status'=>$c->status,'to_status'=>$d['to_status'],'reason_code'=>$d['reason_code'],'actor_id'=>$r->user()->id,'details'=>json_encode($d['details']??[]),'occurred_at'=>now()]);$audit->record('claim.transitioned','claim',$claim,['from'=>$c->status,'to'=>$d['to_status']],$d['reason_code']);});return response()->json(['data'=>['id'=>$claim,'status'=>$d['to_status']]]);}
private function claim(string$id):object{$c=DB::table('claims')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$id)->first();abort_unless($c,404);return$c;}}
