import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Smartphone } from 'lucide-react-native';
import { AppHeader, Button, Card, Money, Screen, TextField } from '@/components/ui';
import { useInsurance } from '@/store/insurance';import { useSession } from '@/store/session';import { colors, radius, space, type } from '@/theme/tokens';
const major=(n:number)=>n/100;
export default function Checkout(){const proposal=useInsurance(s=>s.proposal);const request=useInsurance(s=>s.requestPayment);const busy=useInsurance(s=>s.busy);const error=useInsurance(s=>s.error);const defaultPhone=useSession(s=>s.bootstrap?.user.phone_e164??'');const[phone,setPhone]=useState(defaultPhone);const[provider,setProvider]=useState<'mtn_momo'|'orange_money'>('mtn_momo');if(!proposal)return <Screen><AppHeader title="Review and pay" back/><Card><Text style={styles.title}>No payable proposal found.</Text></Card></Screen>;const t=proposal.terms_snapshot;const pay=async()=>{try{await request(provider,phone);router.replace('/payment');}catch{}};return <Screen><AppHeader title="Review and pay" subtitle="Step 5 of 5 · Nothing is charged yet" back/><Card><Text style={styles.title}>Proposal {proposal.proposal_number}</Text><Row label="Gross premium" amount={major(t.premium_minor)}/><Row label="Tax" amount={major(t.tax_minor)}/><Row label="Fees" amount={major(t.fee_minor)}/><View style={styles.rule}/><Text style={styles.title}>Total to authorize</Text><Money amount={major(t.total_minor)} size="large"/></Card><Card><Text style={styles.title}>Mobile Money network</Text><View style={styles.networks}>{(['mtn_momo','orange_money'] as const).map(v=><Pressable accessibilityRole="radio" accessibilityState={{selected:provider===v}} key={v} style={[styles.network,provider===v&&styles.selected]} onPress={()=>setProvider(v)}><Text style={styles.networkText}>{v==='mtn_momo'?'MTN MoMo':'Orange Money'}</Text></Pressable>)}</View><TextField label="Phone authorizing payment" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Text style={styles.meta}>Your PIN is entered only in the operator prompt—never inside OpesInsure.</Text></Card>{error?<Text style={styles.error}>{error}</Text>:null}<Button label={`Request ${major(t.total_minor).toLocaleString()} FCFA payment`} icon={Smartphone} loading={busy} disabled={!/^\+237[26]\d{8}$/.test(phone)} onPress={()=>void pay()}/></Screen>}
function Row({label,amount}:{label:string;amount:number}){return <View style={styles.row}><Text style={styles.meta}>{label}</Text><Money amount={amount}/></View>};const styles=StyleSheet.create({title:{...type.cardTitle,color:colors.navy950},meta:{...type.meta,color:colors.neutral600},error:{...type.meta,color:colors.dangerText},row:{flexDirection:'row',justifyContent:'space-between'},rule:{height:1,backgroundColor:colors.neutral200},networks:{flexDirection:'row',gap:space.x2},network:{flex:1,minHeight:48,borderWidth:1,borderColor:colors.neutral300,borderRadius:radius.control,alignItems:'center',justifyContent:'center'},selected:{borderColor:colors.blue600,backgroundColor:colors.blue50},networkText:{...type.label,color:colors.navy950}});
