import React, { useCallback, useEffect, useState } from 'react';
import { AppState, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Smartphone } from 'lucide-react-native';
import { AppHeader, Button, Card, Money, Screen, StatusChip } from '@/components/ui';
import { useInsurance } from '@/store/insurance';import { colors, type } from '@/theme/tokens';
const terminal=['SUCCEEDED','FAILED','EXPIRED'];
export default function Payment(){const payment=useInsurance(s=>s.payment);const recover=useInsurance(s=>s.recoverPayment);const refresh=useInsurance(s=>s.refreshPayment);const[checking,setChecking]=useState(false);const[error,setError]=useState<string|null>(null);const check=useCallback(async()=>{setChecking(true);setError(null);try{const result=payment?await refresh():await recover();if(result?.status==='SUCCEEDED')router.replace('/confirmation');}catch(e){setError(e instanceof Error?e.message:'Status could not be verified.');}finally{setChecking(false)}},[payment,recover,refresh]);useEffect(()=>{void check();const timer=setInterval(()=>void check(),5000);const sub=AppState.addEventListener('change',s=>{if(s==='active')void check()});return()=>{clearInterval(timer);sub.remove()}},[check]);return <Screen><AppHeader title="Authorize payment" subtitle="Status is verified with the server"/><Card feature style={styles.center}><View style={styles.icon}><Smartphone size={36} color={colors.blue600}/></View><StatusChip label={(payment?.status??'RECOVERING').replaceAll('_',' ')} tone={payment?.status==='FAILED'?'danger':payment?.status==='SUCCEEDED'?'success':'warning'}/><Text style={styles.title}>{payment?'Check your phone':'Recovering secure payment'}</Text>{payment?<><Text style={styles.body}>Approve the {payment.provider.replaceAll('_',' ')} prompt on {payment.payer_phone_e164}. Never share your PIN.</Text><Money amount={payment.amount_minor/100}/></>:null}</Card>{error?<Text style={styles.error}>{error}</Text>:null}<Button label="Refresh verified status" loading={checking} onPress={()=>void check()}/>{payment&&terminal.includes(payment.status)&&payment.status!=='SUCCEEDED'?<Button label="Return to policies" variant="secondary" onPress={()=>router.replace('/(customer)/(tabs)/policies')}/>:null}</Screen>}
const styles=StyleSheet.create({center:{alignItems:'center'},icon:{width:72,height:72,borderRadius:36,backgroundColor:colors.blue50,alignItems:'center',justifyContent:'center'},title:{...type.sectionTitle,color:colors.navy950},body:{...type.body,color:colors.neutral600,textAlign:'center'},error:{...type.meta,color:colors.dangerText}});
