<?php
declare(strict_types=1); namespace App\Interfaces\Http\Controllers\Api\V1\FinancialDistribution;
use App\Application\FinancialDistribution\{BordereauService,CarrierSettlementService,CommissionService,PartnerStatementService,PayoutService}; use App\Domain\Tenancy\TenantContext; use App\Models\{Bordereau,CommissionAccrual,CommissionRuleVersion,PartnerPayoutRequest,PartnerStatement,Policy,SettlementBatch}; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Routing\Controller; use Illuminate\Validation\Rule;
final class FinancialDistributionController extends Controller {
 public function __construct(private CommissionService$commissions,private PartnerStatementService$statements,private PayoutService$payouts,private CarrierSettlementService$settlements,private BordereauService$bordereaux){}
 private function tenant():string{return app(TenantContext::class)->id();} private function owns(object$m):void{abort_unless(($m->tenant_id??null)===$this->tenant(),404);}
 public function createRule(Request$r):JsonResponse{$d=$r->validate(['carrier_id'=>'required|uuid|exists:carriers,id','product_id'=>'nullable|uuid|exists:insurance_products,id','partner_id'=>'nullable|uuid|exists:partners,id','basis_points'=>'required|integer|min:0|max:10000','holdback_basis_points'=>'required|integer|min:0|max:10000','vesting_days'=>'required|integer|min:0|max:3650','effective_from'=>'required|date','effective_until'=>'nullable|date|after_or_equal:effective_from','conditions'=>'array']);return response()->json($this->commissions->createRule([...$d,'tenant_id'=>$this->tenant()],$r->user()),201);}
 public function approveRule(Request$r,CommissionRuleVersion$rule):JsonResponse{$this->owns($rule);return response()->json($this->commissions->approveRule($rule,$r->user()));}
 public function accrue(Request$r):JsonResponse{$d=$r->validate(['policy_id'=>'required|uuid|exists:policies,id','rule_id'=>'required|uuid|exists:commission_rule_versions,id','partner_id'=>'required|uuid|exists:partners,id','idempotency_key'=>'required|string|max:100']);$p=Policy::findOrFail($d['policy_id']);$rule=CommissionRuleVersion::findOrFail($d['rule_id']);$this->owns($p);$this->owns($rule);return response()->json($this->commissions->accrue($p,$rule,$d['partner_id'],$d['idempotency_key']),201);}
 public function vest(Request$r,CommissionAccrual$accrual):JsonResponse{$this->owns($accrual);return response()->json($this->commissions->vest($accrual));} public function clawback(Request$r,CommissionAccrual$accrual):JsonResponse{$this->owns($accrual);$d=$r->validate(['amount_minor'=>'required|integer|min:1','reason_code'=>'required|string|max:80']);return response()->json($this->commissions->clawback($accrual,$d['amount_minor'],$d['reason_code'],$r->user()));}
 public function prepareStatement(Request$r):JsonResponse{$d=$r->validate(['partner_id'=>'required|uuid|exists:partners,id','period_start'=>'required|date','period_end'=>'required|date|after_or_equal:period_start','currency'=>'required|string|size:3','opening_balance_minor'=>'integer','idempotency_key'=>'required|string|max:100']);return response()->json($this->statements->prepare([...$d,'tenant_id'=>$this->tenant()],$r->user()),201);}
 public function approveStatement(Request$r,PartnerStatement$statement):JsonResponse{$this->owns($statement);return response()->json($this->statements->approve($statement,$r->user()));} public function publishStatement(Request$r,PartnerStatement$statement):JsonResponse{$this->owns($statement);return response()->json($this->statements->publish($statement,$r->user()));}
 public function requestPayout(Request$r,PartnerStatement$statement):JsonResponse{$this->owns($statement);$d=$r->validate(['amount_minor'=>'required|integer|min:1','destination_type'=>['required',Rule::in(['MOBILE_MONEY','BANK'])],'destination'=>'required|string|max:500','idempotency_key'=>'required|string|max:100']);return response()->json($this->payouts->request($statement,$d,$r->user()),201);}
 public function approvePayout(Request$r,PartnerPayoutRequest$payout):JsonResponse{$this->owns($payout);return response()->json($this->payouts->approve($payout,$r->user()));} public function processPayout(Request$r,PartnerPayoutRequest$payout):JsonResponse{$this->owns($payout);return response()->json($this->payouts->markProcessing($payout,$r->validate(['provider'=>'required|string|max:48']),$r->user()));} public function completePayout(Request$r,PartnerPayoutRequest$payout):JsonResponse{$this->owns($payout);return response()->json($this->payouts->complete($payout,$r->validate(['provider_reference'=>'required|string|max:120']),$r->user()));} public function failPayout(Request$r,PartnerPayoutRequest$payout):JsonResponse{$this->owns($payout);return response()->json($this->payouts->fail($payout,$r->validate(['failure_code'=>'required|string|max:80','failure_message'=>'nullable|string|max:1000']),$r->user()));} public function reversePayout(Request$r,PartnerPayoutRequest$payout):JsonResponse{$this->owns($payout);$d=$r->validate(['reason_code'=>'required|string|max:80']);return response()->json($this->payouts->reverse($payout,$d['reason_code'],$r->user()));}
 public function prepareSettlement(Request$r):JsonResponse{$d=$r->validate(['carrier_id'=>'required|uuid|exists:carriers,id','period_start'=>'required|date','period_end'=>'required|date|after_or_equal:period_start','currency'=>'required|string|size:3','idempotency_key'=>'required|string|max:100']);return response()->json($this->settlements->prepare([...$d,'tenant_id'=>$this->tenant()],$r->user()),201);} public function approveSettlement(Request$r,SettlementBatch$settlement):JsonResponse{$this->owns($settlement);$d=$r->validate(['notes'=>'sometimes|string|min:20|max:2000']);return response()->json($this->settlements->approve($settlement,$r->user(),$d['notes']??null));} public function submitSettlement(Request$r,SettlementBatch$settlement):JsonResponse{$this->owns($settlement);return response()->json($this->settlements->submit($settlement,$r->user()));} public function paidSettlement(Request$r,SettlementBatch$settlement):JsonResponse{$this->owns($settlement);$d=$r->validate(['bank_reference'=>'required|string|max:120']);return response()->json($this->settlements->markPaid($settlement,$d['bank_reference'],$r->user()));} public function failSettlement(Request$r,SettlementBatch$settlement):JsonResponse{$this->owns($settlement);$d=$r->validate(['reason'=>'required|string|max:1000']);return response()->json($this->settlements->fail($settlement,$d['reason'],$r->user()));} public function reverseSettlement(Request$r,SettlementBatch$settlement):JsonResponse{$this->owns($settlement);$d=$r->validate(['reason_code'=>'required|string|max:80']);return response()->json($this->settlements->reverse($settlement,$d['reason_code'],$r->user()));}
 public function prepareBordereau(Request$r):JsonResponse{$d=$r->validate(['carrier_id'=>'required|uuid|exists:carriers,id','type'=>['required',Rule::in(['PREMIUM','COMMISSION'])],'period_start'=>'required|date','period_end'=>'required|date|after_or_equal:period_start','currency'=>'required|string|size:3','idempotency_key'=>'required|string|max:100']);return response()->json($this->bordereaux->prepare([...$d,'tenant_id'=>$this->tenant()],$r->user()),201);} public function approveBordereau(Request$r,Bordereau$bordereau):JsonResponse{$this->owns($bordereau);return response()->json($this->bordereaux->approve($bordereau,$r->user()));} public function submitBordereau(Request$r,Bordereau$bordereau):JsonResponse{$this->owns($bordereau);return response()->json($this->bordereaux->submit($bordereau,$r->user()));} public function acknowledgeBordereau(Request$r,Bordereau$bordereau):JsonResponse{$this->owns($bordereau);$d=$r->validate(['carrier_reference'=>'required|string|max:120']);return response()->json($this->bordereaux->acknowledge($bordereau,$d['carrier_reference'],$r->user()));} public function rejectBordereau(Request$r,Bordereau$bordereau):JsonResponse{$this->owns($bordereau);$d=$r->validate(['reason'=>'required|string|max:1000']);return response()->json($this->bordereaux->reject($bordereau,$d['reason'],$r->user()));}
}
