<?php
namespace App\Filament\Admin\Resources\Partners;
use App\Application\Audit\AuditWriter;use App\Filament\Admin\Resources\Partners\Pages;use App\Models\Partner;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Infolists;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Tables;use Filament\Tables\Table;
final class PartnerResource extends \App\Filament\Shared\LocalizedResource
{
protected static?string$model=Partner::class;protected static string|BackedEnum|null$navigationIcon='lucide-store';protected static string|\UnitEnum|null$navigationGroup='Customers & partners';protected static?int$navigationSort=23;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Partner profile')->columnSpanFull()->columns(2)->schema([Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload(),Forms\Components\Select::make('party_id')->relationship('party','display_name')->searchable()->preload()->required(),Forms\Components\Select::make('type')->options(['AGENT'=>'Freelance agent','BROKER'=>'Corporate broker','CARRIER'=>'Insurance carrier'])->required()->native(false),Forms\Components\Select::make('status')->options(['PENDING'=>'Pending licence review','ACTIVE'=>'Active','SUSPENDED'=>'Suspended','REJECTED'=>'Rejected'])->default('PENDING')->required()->disabled(fn(?Partner$p)=>$p!==null)->native(false)])]);}
public static function infolist(Schema$s):Schema{return$s->components(\App\Filament\Shared\Components\RecordShell::detailTabs('partner',self::overview(),null,true,['financial']));}
/** Overview tab (RecordShell core-record pattern). */
public static function overview():array{return[\Filament\Schemas\Components\Section::make('Partner profile')->columnSpanFull()->columns(2)->schema([Infolists\Components\TextEntry::make('party.display_name')->label('Partner'),Infolists\Components\TextEntry::make('type')->badge(),Infolists\Components\TextEntry::make('tenant.legal_name')->label('Organization')->placeholder('Platform-wide'),Infolists\Components\TextEntry::make('status')->badge()->color(fn(string$state)=>match($state){'ACTIVE'=>'success','PENDING'=>'warning','SUSPENDED','REJECTED'=>'danger',default=>'gray'}),Infolists\Components\TextEntry::make('licence_number')->label('Verified licence')->placeholder('Pending'),Infolists\Components\TextEntry::make('licence_expires_on')->label('Licence expires')->date()->placeholder('—')])];}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('party.display_name')->label('Partner')->searchable()->sortable(),Tables\Columns\TextColumn::make('type')->badge(),Tables\Columns\TextColumn::make('tenant.legal_name')->label('Organization')->placeholder('Platform-wide'),Tables\Columns\TextColumn::make('licence_number')->label('Verified licence')->placeholder('Pending'),\App\Filament\Shared\Columns::date('licence_expires_on', false),\App\Filament\Shared\Columns::status('status')])->recordActions([Actions\ViewAction::make()])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No distribution partners')->emptyStateDescription('Register an agent, broker or carrier, then complete licence verification before activation.')->emptyStateIcon('lucide-store');}
public static function getPages():array{return['index'=>Pages\ListPartners::route('/'),'create'=>Pages\CreatePartner::route('/create'),'view'=>Pages\ViewPartner::route('/{record}')];}}
