<?php

declare(strict_types=1);

namespace App\Application\Integrations\Developer;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Routing\{Route,Router};
use ReflectionFunctionAbstract;
use ReflectionMethod;
use ReflectionNamedType;
use Throwable;

/**
 * REQ-API-006 — builds an OpenAPI 3.1 document from the live route table: one operation per
 * /api/v1 route + method, with its path parameters, the permission (`permission:x`) or partner
 * scope (`integration.client:x`) guarding it, and request-body fields from the validation rules —
 * a FormRequest's rules(), or the literal `'field' => 'rules'` pairs of an inline ->validate([...])
 * call in the controller action (best effort, static; never executes the action).
 */
final class OpenApiGenerator
{
    public const PREFIX = 'api/v1';

    public function __construct(private readonly Router $router) {}

    public function generate(): array
    {
        $paths = [];
        foreach ($this->routes() as $route) {
            $path = '/'.ltrim($route->uri(), '/');
            foreach (array_diff($route->methods(), ['HEAD']) as $method) {
                $paths[$path][strtolower($method)] = $this->operation($route, $method);
            }
        }
        ksort($paths);

        $issuer = rtrim((string) config('app.url'), '/');

        return [
            'openapi' => '3.1.0',
            'info' => ['title' => 'OpesInsure API', 'version' => 'v1', 'description' => 'Generated by `php artisan api:openapi` from the route table, validation rules and permission scopes.'],
            'servers' => [['url' => $issuer]],
            'paths' => $paths,
            'components' => ['securitySchemes' => [
                'userToken' => ['type' => 'http', 'scheme' => 'bearer', 'bearerFormat' => 'JWT', 'description' => 'User access token; tenant routes also need X-Tenant-Id.'],
                'partnerClient' => ['type' => 'oauth2', 'flows' => ['clientCredentials' => ['tokenUrl' => $issuer.'/oauth/token', 'scopes' => OAuthScopeCatalogue::descriptions()]]],
            ]],
        ];
    }

    /** @return list<Route> */
    public function routes(): array
    {
        return array_values(array_filter($this->router->getRoutes()->getRoutes(), fn (Route $r) => str_starts_with($r->uri(), self::PREFIX)));
    }

    private function operation(Route $route, string $method): array
    {
        $middleware = $route->gatherMiddleware();
        $permissions = $scopes = [];
        $tenant = false;
        foreach ($middleware as $m) {
            if (! is_string($m)) {
                continue;
            }
            if (str_starts_with($m, 'permission:')) {
                array_push($permissions, ...explode('|', substr($m, 11)));
            } elseif (str_starts_with($m, 'integration.client:')) {
                $scopes[] = substr($m, 19);
            } elseif ($m === 'tenant') {
                $tenant = true;
            }
        }

        $op = [
            'operationId' => strtolower($method).'_'.trim(preg_replace('/[^a-z0-9]+/i', '_', $route->uri()), '_'),
            'tags' => [explode('/', substr($route->uri(), strlen(self::PREFIX) + 1))[0] ?: 'root'],
            'summary' => $route->getActionName(),
            'responses' => ['200' => ['description' => 'OK'], '401' => ['description' => 'Unauthenticated'], '403' => ['description' => 'Forbidden'], '422' => ['description' => 'Validation failed']],
        ];
        if ($route->getName()) {
            $op['x-route-name'] = $route->getName();
        }
        $params = [];
        foreach ($route->parameterNames() as $name) {
            $params[] = ['name' => $name, 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']];
        }
        if ($tenant) {
            $params[] = ['name' => 'X-Tenant-Id', 'in' => 'header', 'required' => true, 'schema' => ['type' => 'string', 'format' => 'uuid']];
        }
        if ($params !== []) {
            $op['parameters'] = $params;
        }
        if ($permissions !== []) {
            $op['x-permissions'] = array_values(array_unique($permissions));
        }
        if ($scopes !== []) {
            $op['x-partner-scopes'] = $scopes;
            $op['security'] = [['partnerClient' => array_values(array_filter($scopes, fn ($s) => $s !== '*'))]];
        } elseif (in_array('auth:api', $middleware, true)) {
            $op['security'] = [['userToken' => []]];
        } else {
            $op['security'] = [];
        }

        $rules = $this->rules($route);
        if ($rules !== []) {
            $properties = $required = [];
            foreach ($rules as $field => $rule) {
                $rule = is_array($rule) ? implode('|', array_filter($rule, 'is_string')) : (string) $rule;
                $properties[$field] = ['type' => $this->typeOf($rule), 'x-rules' => $rule];
                if (str_contains($rule, 'required') && ! str_contains($field, '.')) {
                    $required[] = $field;
                }
            }
            $schema = ['type' => 'object', 'properties' => $properties] + ($required ? ['required' => $required] : []);
            if (in_array($method, ['GET', 'DELETE'], true)) {
                $op['x-query-rules'] = $schema;
            } else {
                $op['requestBody'] = ['content' => ['application/json' => ['schema' => $schema]]];
            }
        }

        return $op;
    }

    /** @return array<string,mixed> */
    private function rules(Route $route): array
    {
        try {
            $action = $route->getAction('uses');
            if (! is_string($action) || ! str_contains($action, '@')) {
                return [];
            }
            [$class, $fn] = explode('@', $action, 2);
            if (! method_exists($class, $fn)) {
                return [];
            }
            $ref = new ReflectionMethod($class, $fn);
            foreach ($ref->getParameters() as $p) {
                $t = $p->getType();
                if ($t instanceof ReflectionNamedType && ! $t->isBuiltin() && is_subclass_of($t->getName(), FormRequest::class)) {
                    $req = new ($t->getName());
                    if (method_exists($req, 'rules')) {
                        try {
                            return (array) app()->call([$req, 'rules']);
                        } catch (Throwable) {
                            return [];
                        }
                    }
                }
            }

            return $this->inlineRules($ref);
        } catch (Throwable) {
            return [];
        }
    }

    /** @return array<string,string> */
    private function inlineRules(ReflectionFunctionAbstract $ref): array
    {
        $file = $ref->getFileName();
        if (! $file || ! is_file($file)) {
            return [];
        }
        $lines = file($file);
        $body = implode('', array_slice($lines, $ref->getStartLine() - 1, $ref->getEndLine() - $ref->getStartLine() + 1));
        if (! preg_match('/validate\(\s*\[(.*?)\]\s*\)/s', $body, $m)) {
            return [];
        }
        preg_match_all("/'([A-Za-z0-9_.*]+)'\s*=>\s*(?:'([^']*)'|\[)/", $m[1], $pairs, PREG_SET_ORDER);
        $out = [];
        foreach ($pairs as $p) {
            $out[$p[1]] = $p[2] ?? '';
        }

        return $out;
    }

    private function typeOf(string $rule): string
    {
        return match (true) {
            str_contains($rule, 'integer') => 'integer',
            str_contains($rule, 'numeric') => 'number',
            str_contains($rule, 'boolean') => 'boolean',
            str_contains($rule, 'array') => 'array',
            default => 'string',
        };
    }
}
