<?php
declare(strict_types=1);
namespace App\Application\Customers;
use App\Application\Audit\AuditWriter;use App\Application\Events\OutboxWriter;use App\Models\AttributionDispute;use App\Models\CustomerAttribution;use App\Models\Partner;use App\Models\Party;use App\Models\User;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class AttributionService
{
public function __construct(private readonly AuditWriter$audit,private readonly OutboxWriter$outbox){}
public function lockOrPreserve(Party$party,?Partner$partner,string$origin,string$terms,string$evidence,User$actor):CustomerAttribution{return CustomerAttribution::where(['party_id'=>$party->id,'status'=>'ACTIVE'])->first()??$this->lock($party,$partner,$origin,$terms,$evidence,$actor);}
public function lock(Party$party,?Partner$partner,string$origin,string$terms,string$evidence,User$actor):CustomerAttribution{return DB::transaction(function()use($party,$partner,$origin,$terms,$evidence,$actor){$existing=CustomerAttribution::where(['party_id'=>$party->id,'status'=>'ACTIVE'])->lockForUpdate()->first();if($existing){if($existing->partner_id===$partner?->id&&$existing->origin_type===$origin)return$existing;throw ValidationException::withMessages(['party_id'=>__('wave1.attribution_already_locked')]);}if($origin!=='SYSTEM'&&!$partner)throw ValidationException::withMessages(['partner_id'=>__('wave1.partner_required')]);if($partner&&$partner->status!=='ACTIVE')throw ValidationException::withMessages(['partner_id'=>__('wave1.partner_not_active')]);if($partner&&$origin!==$partner->type)throw ValidationException::withMessages(['partner_id'=>__('wave1.partner_type_mismatch')]);$a=CustomerAttribution::create(['party_id'=>$party->id,'partner_id'=>$partner?->id,'origin_type'=>$origin,'terms_version'=>$terms,'effective_from'=>now(),'status'=>'ACTIVE','evidence_reference'=>$evidence,'recorded_by'=>$actor->id]);$this->event($a,'LOCKED',null,$partner?->id,null,'ORIGIN_REGISTRATION','Initial permanent origin lock',$actor);$this->audit->record('attribution.locked','customer_attribution',$a->id,['party_id'=>$party->id,'partner_id'=>$partner?->id,'origin_type'=>$origin]);$this->outbox->record('customer.attribution.locked','customer_attribution',$a->id,['attribution_id'=>$a->id,'party_id'=>$party->id,'partner_id'=>$partner?->id]);return$a;});}
public function openDispute(CustomerAttribution$a,?Partner$raisedBy,string$reason,string$description,array$evidence,User$actor):AttributionDispute{if($a->disputes()->whereIn('status',['OPEN','UNDER_REVIEW'])->exists())throw ValidationException::withMessages(['attribution_id'=>__('wave1.dispute_exists')]);$d=$a->disputes()->create(['raised_by_partner_id'=>$raisedBy?->id,'reason_code'=>$reason,'description'=>$description,'status'=>'OPEN','evidence'=>$evidence]);$this->event($a,'DISPUTED',$a->partner_id,$a->partner_id,$d->id,$reason,$description,$actor);$this->audit->record('attribution.dispute.opened','attribution_dispute',$d->id,['attribution_id'=>$a->id],$reason);return$d;}
public function resolve(AttributionDispute$d,string$resolution,string$notes,User$actor,?Partner$reassignTo=null):AttributionDispute{return DB::transaction(function()use($d,$resolution,$notes,$actor,$reassignTo){$d=AttributionDispute::whereKey($d->id)->lockForUpdate()->firstOrFail();if(!in_array($d->status,['OPEN','UNDER_REVIEW'],true))throw ValidationException::withMessages(['status'=>__('wave1.dispute_resolved')]);$a=$d->attribution;$from=$a->partner_id;if($resolution==='REASSIGNED'){if(!$reassignTo||$reassignTo->status!=='ACTIVE')throw ValidationException::withMessages(['reassign_partner_id'=>__('wave1.active_partner_required')]);$a->update(['partner_id'=>$reassignTo->id,'origin_type'=>$reassignTo->type==='AGENT'?'AGENT':'BROKER','terms_version'=>$a->terms_version,'evidence_reference'=>'DISPUTE:'.$d->id]);}$d->update(['status'=>'RESOLVED','resolution_code'=>$resolution,'resolution_notes'=>$notes,'resolved_by'=>$actor->id,'resolved_at'=>now()]);$this->event($a,$resolution==='REASSIGNED'?'REASSIGNED':'DISPUTE_RESOLVED',$from,$a->partner_id,$d->id,$resolution,$notes,$actor);$this->audit->record('attribution.dispute.resolved','attribution_dispute',$d->id,['resolution'=>$resolution,'from_partner_id'=>$from,'to_partner_id'=>$a->partner_id]);$this->outbox->record('customer.attribution.changed','customer_attribution',$a->id,['attribution_id'=>$a->id,'resolution'=>$resolution,'partner_id'=>$a->partner_id]);return$d->refresh();});}
private function event(CustomerAttribution$a,string$type,?string$from,?string$to,?string$dispute,string$reason,string$notes,User$actor):void{DB::table('attribution_events')->insert(['id'=>(string)Str::uuid(),'attribution_id'=>$a->id,'type'=>$type,'from_partner_id'=>$from,'to_partner_id'=>$to,'dispute_id'=>$dispute,'reason_code'=>$reason,'notes'=>$notes,'actor_id'=>$actor->id,'occurred_at'=>now()]);}
}
