<?php
declare(strict_types=1);
namespace App\Application\Customers;
use App\Application\Audit\AuditWriter;use App\Application\Events\OutboxWriter;use App\Models\Party;use App\Models\PartyIdentifier;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
final class PartyService
{
public function __construct(private readonly AuditWriter$audit,private readonly OutboxWriter$outbox){}
public function create(array$data):Party{return DB::transaction(function()use($data){$phone=$data['phone_e164']??null;if($phone&&DB::table('party_contacts')->where(['type'=>'PHONE','normalized_value'=>$phone])->exists())throw ValidationException::withMessages(['phone_e164'=>__('wave1.phone_exists')]);$party=Party::create(['type'=>$data['type'],'display_name'=>$data['display_name'],'legal_identity'=>array_filter(['date_of_birth'=>$data['date_of_birth']??null,'registration_number'=>$data['registration_number']??null]),'status'=>'ACTIVE']);if($phone)$party->contacts()->create(['type'=>'PHONE','normalized_value'=>$phone,'is_primary'=>true]);if($email=$data['email']??null){$email=mb_strtolower($email);if(DB::table('party_contacts')->where(['type'=>'EMAIL','normalized_value'=>$email])->exists())throw ValidationException::withMessages(['email'=>__('wave1.email_exists')]);$party->contacts()->create(['type'=>'EMAIL','normalized_value'=>$email,'is_primary'=>true]);}if($value=$data['identifier_value']??null)$this->addIdentifier($party,$data['identifier_type'],$value,$data['identifier_country']??'CM');$this->audit->record('party.created','party',$party->id,['type'=>$party->type]);$this->outbox->record('party.created','party',$party->id,['party_id'=>$party->id,'type'=>$party->type]);return$party;});}
public function addIdentifier(Party$party,string$type,string$value,string$country='CM'):PartyIdentifier{$normalized=mb_strtoupper(preg_replace('/[\s\-]+/','',$value));$hash=hash_hmac('sha256',$country.'|'.$type.'|'.$normalized,(string)config('app.key'));if(PartyIdentifier::where(['type'=>$type,'country_code'=>$country,'value_hash'=>$hash])->exists())throw ValidationException::withMessages(['identifier_value'=>__('wave1.identifier_exists')]);$masked=str_repeat('•',max(0,mb_strlen($normalized)-4)).mb_substr($normalized,-4);return$party->identifiers()->create(['type'=>$type,'country_code'=>$country,'value_hash'=>$hash,'value_encrypted'=>Crypt::encryptString($normalized),'masked_value'=>$masked]);}
}
