<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::table('fraud_rule_versions',function(Blueprint$t){$t->foreignUuid('created_by')->nullable()->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->text('retirement_reason')->nullable();});
Schema::table('risk_alerts',function(Blueprint$t){$t->foreignUuid('fraud_rule_version_id')->nullable()->constrained();$t->string('idempotency_key',100)->nullable();$t->string('payload_hash',64)->nullable();$t->timestampTz('review_due_at')->nullable();$t->unsignedInteger('version')->default(1);$t->unique(['tenant_id','idempotency_key']);});
Schema::table('compliance_cases',function(Blueprint$t){$t->string('idempotency_key',100)->nullable();$t->string('payload_hash',64)->nullable();$t->foreignUuid('opened_by')->nullable()->constrained('users');$t->foreignUuid('closed_by')->nullable()->constrained('users');$t->string('closure_code',64)->nullable();$t->text('closure_notes')->nullable();$t->unsignedInteger('version')->default(1);$t->unique(['tenant_id','idempotency_key']);});
Schema::create('compliance_case_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('compliance_case_id')->constrained()->cascadeOnDelete();$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::table('data_subject_requests',function(Blueprint$t){$t->foreignUuid('tenant_id')->nullable()->constrained();$t->string('idempotency_key',100)->nullable();$t->string('payload_hash',64)->nullable();$t->string('identity_evidence_hash',64)->nullable();$t->foreignUuid('verified_by')->nullable()->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->string('rejection_code',64)->nullable();$t->text('resolution_notes')->nullable();$t->timestampTz('fulfilled_at')->nullable();$t->unique(['tenant_id','idempotency_key']);});
Schema::create('data_subject_request_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('data_subject_request_id')->constrained()->cascadeOnDelete();$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::table('privileged_access_grants',function(Blueprint$t){$t->string('status',24)->default('APPROVED');$t->foreignUuid('requested_by')->nullable()->constrained('users');$t->foreignUuid('revoked_by')->nullable()->constrained('users');$t->text('revocation_reason')->nullable();$t->string('scope_hash',64)->nullable();$t->jsonb('scope')->default('[]');});
Schema::create('privileged_access_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('privileged_access_grant_id')->constrained()->cascadeOnDelete();$t->string('event_type',32);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->string('purpose',64);$t->string('resource_type',64)->nullable();$t->uuid('resource_id')->nullable();$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::create('regulatory_report_definitions',function(Blueprint$t){$t->uuid('id')->primary();$t->string('code',80);$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->string('jurisdiction',40);$t->string('report_type',64);$t->jsonb('schema');$t->string('schema_hash',64);$t->date('effective_from');$t->date('effective_until')->nullable();$t->foreignUuid('created_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();$t->unique(['code','version']);});
Schema::create('regulatory_report_runs',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->foreignUuid('definition_id')->constrained('regulatory_report_definitions');$t->string('period_key',40);$t->string('status',32)->default('DRAFT');$t->string('idempotency_key',100);$t->string('payload_hash',64);$t->jsonb('payload')->default('{}');$t->foreignUuid('prepared_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->unsignedSmallInteger('attempt_count')->default(0);$t->timestampTz('next_attempt_at')->nullable();$t->text('failure_reason')->nullable();$t->string('external_reference')->nullable();$t->timestampTz('submitted_at')->nullable();$t->timestampTz('acknowledged_at')->nullable();$t->timestampTz('reversed_at')->nullable();$t->timestampsTz();$t->unique(['tenant_id','idempotency_key']);$t->unique(['tenant_id','definition_id','period_key']);});
DB::statement("ALTER TABLE regulatory_report_definitions ADD CONSTRAINT regulatory_definition_checker CHECK (approved_by IS NULL OR approved_by <> created_by)");DB::statement("ALTER TABLE regulatory_report_runs ADD CONSTRAINT regulatory_run_checker CHECK (approved_by IS NULL OR approved_by <> prepared_by)");
}public function down():void{foreach(['regulatory_report_runs','regulatory_report_definitions','privileged_access_events','data_subject_request_events','compliance_case_events']as$x)Schema::dropIfExists($x);Schema::table('privileged_access_grants',fn(Blueprint$t)=>$t->dropColumn(['status','requested_by','revoked_by','revocation_reason','scope_hash','scope']));Schema::table('data_subject_requests',function(Blueprint$t){$t->dropUnique(['tenant_id','idempotency_key']);foreach(['tenant_id','verified_by','approved_by']as$x)$t->dropConstrainedForeignId($x);$t->dropColumn(['idempotency_key','payload_hash','identity_evidence_hash','rejection_code','resolution_notes','fulfilled_at']);});Schema::table('compliance_cases',function(Blueprint$t){$t->dropUnique(['tenant_id','idempotency_key']);foreach(['opened_by','closed_by']as$x)$t->dropConstrainedForeignId($x);$t->dropColumn(['idempotency_key','payload_hash','closure_code','closure_notes','version']);});Schema::table('risk_alerts',function(Blueprint$t){$t->dropUnique(['tenant_id','idempotency_key']);$t->dropConstrainedForeignId('fraud_rule_version_id');$t->dropColumn(['idempotency_key','payload_hash','review_due_at','version']);});Schema::table('fraud_rule_versions',function(Blueprint$t){foreach(['created_by','approved_by']as$x)$t->dropConstrainedForeignId($x);$t->dropColumn(['approved_at','retirement_reason']);});}};
