<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('policy_issuance_requests',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained();$t->foreignUuid('proposal_id')->constrained();$t->foreignUuid('payment_intent_id')->constrained();$t->foreignUuid('carrier_id')->constrained();$t->foreignUuid('delegated_authority_agreement_id')->nullable()->constrained();$t->string('status',32)->default('REQUESTED');$t->jsonb('authority_snapshot')->default('{}');$t->string('terms_hash',64);$t->dateTimeTz('coverage_starts_at');$t->dateTimeTz('coverage_ends_at');$t->foreignUuid('requested_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->string('carrier_reference')->nullable();$t->text('rejection_reason')->nullable();$t->timestampsTz();$t->unique('proposal_id');});
Schema::create('policy_issuance_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('policy_issuance_request_id')->constrained()->cascadeOnDelete();$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::create('sticker_batches',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('carrier_id')->constrained();$t->string('batch_number',100)->unique();$t->unsignedInteger('quantity');$t->string('status',24)->default('RECEIVED');$t->foreignUuid('received_by')->constrained('users');$t->timestampTz('received_at');$t->jsonb('evidence')->default('{}');$t->timestampsTz();});
Schema::create('certificate_verification_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('policy_certificate_id')->constrained()->cascadeOnDelete();$t->string('result',24);$t->string('request_fingerprint_hash',64);$t->timestampTz('occurred_at');});
Schema::create('renewal_cases',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained();$t->foreignUuid('policy_id')->constrained();$t->foreignUuid('renewal_quote_id')->nullable()->constrained('quotes');$t->foreignUuid('successor_policy_id')->nullable()->constrained('policies');$t->string('status',32)->default('DUE');$t->date('due_on');$t->jsonb('attribution_snapshot')->default('{}');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->unsignedSmallInteger('contact_attempts')->default(0);$t->timestampTz('last_contacted_at')->nullable();$t->timestampsTz();$t->unique(['policy_id','due_on']);});
Schema::create('cancellation_rule_versions',function(Blueprint$t){$t->uuid('id')->primary();$t->string('line_code',32);$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->string('basis',24);$t->unsignedInteger('short_rate_basis_points')->default(10000);$t->bigInteger('admin_fee_minor')->default(0);$t->date('effective_from');$t->date('effective_until')->nullable();$t->foreignUuid('created_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();$t->unique(['line_code','version']);});
Schema::create('policy_transaction_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('policy_transaction_id')->constrained()->cascadeOnDelete();$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::table('certificate_templates',function(Blueprint$t){$t->foreignUuid('created_by')->nullable()->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();});
Schema::table('sticker_stock',function(Blueprint$t){$t->foreignUuid('sticker_batch_id')->nullable()->constrained('sticker_batches');$t->string('security_code_hash',64)->nullable()->unique();});
Schema::table('policies',function(Blueprint$t){$t->foreignUuid('issuance_request_id')->nullable()->constrained('policy_issuance_requests');$t->foreignUuid('previous_policy_id')->nullable()->constrained('policies');$t->string('terms_hash',64)->nullable();});
Schema::table('policy_transactions',function(Blueprint$t){$t->foreignUuid('cancellation_rule_version_id')->nullable()->constrained();$t->foreignUuid('payment_intent_id')->nullable()->constrained();$t->bigInteger('refund_minor')->default(0);$t->string('terms_hash',64)->nullable();});
DB::statement("ALTER TABLE policy_issuance_requests ADD CONSTRAINT issuance_approver_separation CHECK (approved_by IS NULL OR approved_by <> requested_by)");
DB::statement("ALTER TABLE cancellation_rule_versions ADD CONSTRAINT cancellation_approver_separation CHECK (approved_by IS NULL OR approved_by <> created_by)");
DB::statement("ALTER TABLE cancellation_rule_versions ADD CONSTRAINT short_rate_valid CHECK (short_rate_basis_points <= 10000)");
}
public function down():void{DB::statement('ALTER TABLE cancellation_rule_versions DROP CONSTRAINT IF EXISTS short_rate_valid');DB::statement('ALTER TABLE cancellation_rule_versions DROP CONSTRAINT IF EXISTS cancellation_approver_separation');DB::statement('ALTER TABLE policy_issuance_requests DROP CONSTRAINT IF EXISTS issuance_approver_separation');Schema::table('policy_transactions',function(Blueprint$t){$t->dropConstrainedForeignId('cancellation_rule_version_id');$t->dropConstrainedForeignId('payment_intent_id');$t->dropColumn(['refund_minor','terms_hash']);});Schema::table('policies',function(Blueprint$t){$t->dropConstrainedForeignId('issuance_request_id');$t->dropConstrainedForeignId('previous_policy_id');$t->dropColumn('terms_hash');});Schema::table('sticker_stock',function(Blueprint$t){$t->dropConstrainedForeignId('sticker_batch_id');$t->dropColumn('security_code_hash');});Schema::table('certificate_templates',function(Blueprint$t){$t->dropConstrainedForeignId('created_by');$t->dropConstrainedForeignId('approved_by');$t->dropColumn('approved_at');});Schema::dropIfExists('policy_transaction_events');Schema::dropIfExists('cancellation_rule_versions');Schema::dropIfExists('renewal_cases');Schema::dropIfExists('certificate_verification_events');Schema::dropIfExists('sticker_batches');Schema::dropIfExists('policy_issuance_events');Schema::dropIfExists('policy_issuance_requests');}
};
