<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('exclusion_definitions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('insurance_line_id')->constrained();$t->string('code',64);$t->jsonb('name');$t->jsonb('description')->default('{}');$t->string('status',24)->default('ACTIVE');$t->timestampsTz();$t->unique(['insurance_line_id','code']);});
Schema::create('product_exclusions',function(Blueprint$t){$t->foreignUuid('insurance_product_id')->constrained()->cascadeOnDelete();$t->foreignUuid('exclusion_definition_id')->constrained()->cascadeOnDelete();$t->jsonb('configuration')->default('{}');$t->primary(['insurance_product_id','exclusion_definition_id']);});
Schema::table('coverage_definitions',function(Blueprint$t){$t->string('status',24)->default('ACTIVE');});
Schema::table('product_coverages',function(Blueprint$t){$t->boolean('is_optional')->default(false);$t->unsignedSmallInteger('display_order')->default(0);});
Schema::table('insurance_products',function(Blueprint$t){$t->foreignUuid('created_by')->nullable()->constrained('users');$t->foreignUuid('published_by')->nullable()->constrained('users');$t->timestampTz('published_at')->nullable();$t->string('regulatory_reference',120)->nullable();});
Schema::create('product_status_history',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('insurance_product_id')->constrained()->cascadeOnDelete();$t->string('from_status',24)->nullable();$t->string('to_status',24);$t->string('reason_code',64);$t->text('notes');$t->foreignUuid('actor_id')->constrained('users');$t->timestampTz('occurred_at');});
Schema::table('tariff_versions',function(Blueprint$t){$t->foreignUuid('created_by')->nullable()->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->text('approval_reason')->nullable();$t->string('regulatory_reference',120)->nullable();});
Schema::create('tariff_status_history',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tariff_version_id')->constrained()->cascadeOnDelete();$t->string('from_status',24)->nullable();$t->string('to_status',24);$t->string('reason_code',64);$t->text('notes');$t->foreignUuid('actor_id')->constrained('users');$t->timestampTz('occurred_at');});
Schema::create('risk_asset_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('risk_asset_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('from_version')->nullable();$t->unsignedInteger('to_version');$t->string('type',32);$t->jsonb('changed_fields')->default('[]');$t->string('facts_hash',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->timestampTz('occurred_at');});
Schema::table('quotes',function(Blueprint$t){$t->timestampTz('rated_at')->nullable();$t->jsonb('comparison_context')->default('{}');});
Schema::table('quote_offers',function(Blueprint$t){$t->unsignedSmallInteger('comparison_rank')->nullable();$t->jsonb('ranking_reasons')->default('[]');});
DB::statement('CREATE UNIQUE INDEX quote_offers_one_per_tariff ON quote_offers (quote_id, tariff_version_id)');
DB::statement("CREATE UNIQUE INDEX insurance_products_one_active_version ON insurance_products (carrier_id, code) WHERE status = 'ACTIVE'");
DB::statement("ALTER TABLE insurance_products ADD CONSTRAINT insurance_product_status_allowed CHECK (status IN ('DRAFT','IN_REVIEW','ACTIVE','RETIRED','REJECTED'))");
DB::statement("ALTER TABLE tariff_versions ADD CONSTRAINT tariff_status_allowed CHECK (status IN ('DRAFT','IN_REVIEW','APPROVED','RETIRED','REJECTED'))");
}
public function down():void{DB::statement('DROP INDEX IF EXISTS insurance_products_one_active_version');DB::statement('ALTER TABLE tariff_versions DROP CONSTRAINT IF EXISTS tariff_status_allowed');DB::statement('ALTER TABLE insurance_products DROP CONSTRAINT IF EXISTS insurance_product_status_allowed');Schema::table('quote_offers',fn(Blueprint$t)=>$t->dropColumn(['comparison_rank','ranking_reasons']));Schema::table('quotes',fn(Blueprint$t)=>$t->dropColumn(['rated_at','comparison_context']));Schema::dropIfExists('risk_asset_events');Schema::dropIfExists('tariff_status_history');Schema::table('tariff_versions',function(Blueprint$t){$t->dropConstrainedForeignId('created_by');$t->dropConstrainedForeignId('approved_by');$t->dropColumn(['approved_at','approval_reason','regulatory_reference']);});Schema::dropIfExists('product_status_history');Schema::table('insurance_products',function(Blueprint$t){$t->dropConstrainedForeignId('created_by');$t->dropConstrainedForeignId('published_by');$t->dropColumn(['published_at','regulatory_reference']);});Schema::table('product_coverages',fn(Blueprint$t)=>$t->dropColumn(['is_optional','display_order']));Schema::table('coverage_definitions',fn(Blueprint$t)=>$t->dropColumn('status'));Schema::dropIfExists('product_exclusions');Schema::dropIfExists('exclusion_definitions');}}
;
