<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('couriers',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->string('name');$t->string('type',24);$t->string('phone_e164',20)->nullable();$t->string('status',24)->default('ACTIVE');$t->jsonb('service_areas')->default('[]');$t->timestampsTz();});
Schema::create('fulfilment_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('fulfilment_order_id')->constrained()->cascadeOnDelete();$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('event_type',40);$t->foreignUuid('courier_id')->nullable()->constrained();$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->jsonb('evidence')->default('{}');$t->timestampTz('occurred_at');});
Schema::table('fulfilment_orders',function(Blueprint$t){$t->foreignUuid('courier_id')->nullable()->constrained();$t->string('tracking_number',80)->nullable()->unique();$t->unsignedSmallInteger('delivery_attempts')->default(0);$t->timestampTz('delivered_at')->nullable();});
Schema::create('notification_templates',function(Blueprint$t){$t->uuid('id')->primary();$t->string('code',80);$t->string('purpose',64);$t->string('channel',24);$t->string('locale',5);$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->string('subject')->nullable();$t->text('body');$t->jsonb('required_variables')->default('[]');$t->timestampsTz();$t->unique(['code','channel','locale','version']);});
Schema::create('communication_preferences',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('party_id')->constrained();$t->string('purpose',64);$t->string('channel',24);$t->boolean('enabled')->default(true);$t->string('source',24);$t->timestampTz('changed_at');$t->timestampsTz();$t->unique(['party_id','purpose','channel']);});
Schema::create('notification_deliveries',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->foreignUuid('party_id')->nullable()->constrained();$t->foreignUuid('template_id')->constrained('notification_templates');$t->string('channel',24);$t->string('destination_hash',64);$t->string('status',24)->default('QUEUED');$t->string('provider')->nullable();$t->string('provider_reference')->nullable();$t->unsignedSmallInteger('attempts')->default(0);$t->timestampTz('next_attempt_at')->nullable();$t->timestampTz('sent_at')->nullable();$t->timestampTz('delivered_at')->nullable();$t->text('failure_reason')->nullable();$t->jsonb('payload')->default('{}');$t->timestampsTz();});
Schema::create('support_tickets',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->foreignUuid('party_id')->nullable()->constrained();$t->string('ticket_number',64)->unique();$t->string('type',24);$t->string('category',64);$t->string('priority',16)->default('NORMAL');$t->string('status',32)->default('OPEN');$t->string('subject');$t->text('description');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->timestampTz('sla_due_at');$t->timestampTz('resolved_at')->nullable();$t->timestampTz('closed_at')->nullable();$t->timestampsTz();});
Schema::create('support_ticket_events',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('support_ticket_id')->constrained()->cascadeOnDelete();$t->string('type',32);$t->string('from_status',32)->nullable();$t->string('to_status',32)->nullable();$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->text('message')->nullable();$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::create('fraud_rule_versions',function(Blueprint$t){$t->uuid('id')->primary();$t->string('code',80);$t->unsignedInteger('version');$t->string('scope',32);$t->string('status',24)->default('DRAFT');$t->unsignedSmallInteger('risk_points');$t->jsonb('conditions');$t->string('rule_hash',64);$t->date('effective_from');$t->date('effective_until')->nullable();$t->timestampsTz();$t->unique(['code','version']);});
Schema::create('risk_alerts',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->string('subject_type',64);$t->uuid('subject_id');$t->string('alert_type',64);$t->unsignedSmallInteger('risk_score');$t->string('severity',16);$t->string('status',24)->default('OPEN');$t->jsonb('signals');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->foreignUuid('decided_by')->nullable()->constrained('users');$t->string('decision',32)->nullable();$t->text('decision_notes')->nullable();$t->timestampTz('decided_at')->nullable();$t->timestampsTz();});
Schema::create('compliance_cases',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->string('case_number',64)->unique();$t->string('type',48);$t->string('subject_type',64);$t->uuid('subject_id');$t->string('status',32)->default('OPEN');$t->string('severity',16);$t->foreignUuid('owner_id')->nullable()->constrained('users');$t->date('review_due_on')->nullable();$t->jsonb('findings')->default('[]');$t->timestampTz('closed_at')->nullable();$t->timestampsTz();});
Schema::create('privileged_access_grants',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('user_id')->constrained();$t->foreignUuid('tenant_id')->constrained();$t->string('purpose',64);$t->text('justification');$t->foreignUuid('approved_by')->constrained('users');$t->timestampTz('starts_at');$t->timestampTz('expires_at');$t->timestampTz('revoked_at')->nullable();$t->timestampsTz();});
Schema::create('data_subject_requests',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('party_id')->constrained();$t->string('request_number',64)->unique();$t->string('type',32);$t->string('status',32)->default('RECEIVED');$t->timestampTz('identity_verified_at')->nullable();$t->date('due_on');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->timestampTz('completed_at')->nullable();$t->timestampsTz();});
DB::statement("ALTER TABLE privileged_access_grants ADD CONSTRAINT privileged_approver_separation CHECK (approved_by <> user_id)");}
public function down():void{Schema::table('fulfilment_orders',function(Blueprint$t){$t->dropConstrainedForeignId('courier_id');$t->dropColumn(['tracking_number','delivery_attempts','delivered_at']);});foreach(['data_subject_requests','privileged_access_grants','compliance_cases','risk_alerts','fraud_rule_versions','support_ticket_events','support_tickets','notification_deliveries','communication_preferences','notification_templates','fulfilment_events','couriers']as$table)Schema::dropIfExists($table);}}
;
