<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('payment_provider_connections',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->string('provider',32);$t->string('environment',16)->default('SANDBOX');$t->string('status',24)->default('DISABLED');$t->string('credential_reference');$t->jsonb('capabilities')->default('[]');$t->foreignUuid('created_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();$t->unique(['tenant_id','provider','environment']);});
Schema::create('payment_attempts',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('payment_intent_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('attempt_number');$t->string('provider_request_id',128)->unique();$t->string('status',32);$t->jsonb('request_snapshot')->default('{}');$t->jsonb('response_snapshot')->default('{}');$t->string('failure_code',64)->nullable();$t->timestampTz('started_at');$t->timestampTz('completed_at')->nullable();$t->timestampsTz();$t->unique(['payment_intent_id','attempt_number']);});
Schema::create('financial_posting_profiles',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->string('event_type',64);$t->string('currency',3)->default('XAF');$t->foreignUuid('debit_account_id')->constrained('ledger_accounts');$t->foreignUuid('credit_account_id')->constrained('ledger_accounts');$t->string('status',24)->default('DRAFT');$t->foreignUuid('created_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();$t->unique(['tenant_id','event_type','currency']);});
Schema::create('financial_case_events',function(Blueprint$t){$t->uuid('id')->primary();$t->string('case_type',24);$t->uuid('case_id');$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::table('reconciliation_imports',function(Blueprint$t){$t->foreignUuid('tenant_id')->nullable()->constrained();$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();});
Schema::table('webhook_inbox',function(Blueprint$t){$t->unsignedInteger('processing_attempts')->default(0);$t->timestampTz('next_attempt_at')->nullable();});
Schema::table('payment_intents',function(Blueprint$t){$t->foreignUuid('journal_id')->nullable()->constrained('journals');$t->timestampTz('reconciled_at')->nullable();});
Schema::table('refunds',function(Blueprint$t){$t->foreignUuid('journal_id')->nullable()->constrained('journals');$t->string('idempotency_key',128)->nullable();$t->unique(['tenant_id','idempotency_key']);});
Schema::table('chargebacks',function(Blueprint$t){$t->foreignUuid('journal_id')->nullable()->constrained('journals');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->text('resolution_notes')->nullable();});
DB::statement("CREATE UNIQUE INDEX journals_reference_once ON journals (reference_type, reference_id) WHERE status = 'POSTED'");
DB::statement("ALTER TABLE payment_provider_connections ADD CONSTRAINT provider_connection_approver_separation CHECK (approved_by IS NULL OR approved_by <> created_by)");
DB::statement("ALTER TABLE financial_posting_profiles ADD CONSTRAINT posting_profile_approver_separation CHECK (approved_by IS NULL OR approved_by <> created_by)");
}
public function down():void{DB::statement('DROP INDEX IF EXISTS journals_reference_once');DB::statement('ALTER TABLE financial_posting_profiles DROP CONSTRAINT IF EXISTS posting_profile_approver_separation');DB::statement('ALTER TABLE payment_provider_connections DROP CONSTRAINT IF EXISTS provider_connection_approver_separation');Schema::table('chargebacks',function(Blueprint$t){$t->dropConstrainedForeignId('journal_id');$t->dropConstrainedForeignId('assigned_to');$t->dropColumn('resolution_notes');});Schema::table('refunds',function(Blueprint$t){$t->dropUnique(['tenant_id','idempotency_key']);$t->dropConstrainedForeignId('journal_id');$t->dropColumn('idempotency_key');});Schema::table('payment_intents',function(Blueprint$t){$t->dropConstrainedForeignId('journal_id');$t->dropColumn('reconciled_at');});Schema::table('webhook_inbox',fn(Blueprint$t)=>$t->dropColumn(['processing_attempts','next_attempt_at']));Schema::table('reconciliation_imports',function(Blueprint$t){$t->dropConstrainedForeignId('tenant_id');$t->dropConstrainedForeignId('approved_by');$t->dropColumn('approved_at');});Schema::dropIfExists('financial_case_events');Schema::dropIfExists('financial_posting_profiles');Schema::dropIfExists('payment_attempts');Schema::dropIfExists('payment_provider_connections');}
};
