<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('report_definitions',function(Blueprint$t){$t->uuid('id')->primary();$t->string('code',80);$t->string('name');$t->string('category',40);$t->jsonb('dimensions');$t->jsonb('measures');$t->jsonb('allowed_roles')->default('[]');$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->timestampsTz();$t->unique(['code','version']);});
Schema::create('report_exports',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained();$t->foreignUuid('report_definition_id')->constrained();$t->foreignUuid('requested_by')->constrained('users');$t->string('format',16);$t->jsonb('filters');$t->string('status',24)->default('QUEUED');$t->string('storage_key')->nullable();$t->string('sha256',64)->nullable();$t->timestampTz('expires_at')->nullable();$t->timestampsTz();});
Schema::create('regulatory_reference_sets',function(Blueprint$t){$t->uuid('id')->primary();$t->string('jurisdiction',8)->default('CM');$t->string('code',80);$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->date('effective_from');$t->date('effective_until')->nullable();$t->jsonb('entries');$t->string('content_hash',64);$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();$t->unique(['jurisdiction','code','version']);});
Schema::create('business_calendars',function(Blueprint$t){$t->uuid('id')->primary();$t->string('jurisdiction',8);$t->unsignedSmallInteger('year');$t->jsonb('holidays')->default('[]');$t->string('timezone',64)->default('Africa/Douala');$t->timestampsTz();$t->unique(['jurisdiction','year']);});
Schema::create('integration_clients',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('partner_id')->nullable()->constrained();$t->string('name');$t->string('client_id',100)->unique();$t->string('client_secret_hash');$t->jsonb('scopes');$t->jsonb('allowed_ips')->default('[]');$t->string('status',24)->default('ACTIVE');$t->unsignedInteger('rate_limit_per_minute')->default(60);$t->timestampTz('last_used_at')->nullable();$t->timestampsTz();});
Schema::create('integration_webhook_subscriptions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('integration_client_id')->constrained()->cascadeOnDelete();$t->string('event_name',120);$t->text('endpoint_encrypted');$t->string('signing_secret_hash');$t->string('status',24)->default('ACTIVE');$t->timestampsTz();$t->unique(['integration_client_id','event_name']);});
Schema::create('integration_delivery_attempts',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('integration_webhook_subscription_id')->constrained()->cascadeOnDelete();$t->uuid('event_id');$t->unsignedSmallInteger('attempt');$t->string('status',24);$t->unsignedSmallInteger('response_status')->nullable();$t->text('failure_reason')->nullable();$t->timestampTz('next_attempt_at')->nullable();$t->timestampTz('delivered_at')->nullable();$t->timestampsTz();$t->unique(['integration_webhook_subscription_id','event_id','attempt'],'ida_subscription_event_attempt_unique');});
Schema::create('bordereaux',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained();$t->foreignUuid('carrier_id')->constrained();$t->string('type',24);$t->string('bordereau_number',64)->unique();$t->date('period_start');$t->date('period_end');$t->string('status',32)->default('DRAFT');$t->unsignedInteger('item_count')->default(0);$t->bigInteger('gross_premium_minor')->default(0);$t->bigInteger('commission_minor')->default(0);$t->string('currency',3)->default('XAF');$t->foreignUuid('prepared_by')->constrained('users');$t->foreignUuid('submitted_by')->nullable()->constrained('users');$t->timestampTz('submitted_at')->nullable();$t->string('carrier_reference')->nullable();$t->timestampsTz();});
Schema::create('bordereau_items',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('bordereau_id')->constrained('bordereaux')->cascadeOnDelete();$t->foreignUuid('policy_id')->constrained();$t->string('transaction_type',32);$t->bigInteger('premium_minor');$t->bigInteger('commission_minor');$t->string('currency',3);$t->dateTimeTz('effective_at');$t->timestampsTz();$t->unique(['bordereau_id','policy_id','transaction_type']);});
Schema::create('renewal_work_items',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained();$t->foreignUuid('policy_id')->constrained();$t->date('renewal_due_on');$t->string('status',32)->default('DUE');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->unsignedSmallInteger('contact_attempts')->default(0);$t->timestampTz('last_contacted_at')->nullable();$t->string('outcome',32)->nullable();$t->timestampsTz();$t->unique(['policy_id','renewal_due_on']);});
Schema::create('delegated_authority_agreements',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('carrier_id')->constrained();$t->foreignUuid('partner_id')->constrained();$t->string('agreement_number',80)->unique();$t->date('effective_from');$t->date('effective_until');$t->string('status',24)->default('DRAFT');$t->jsonb('permitted_lines');$t->bigInteger('max_policy_premium_minor');$t->bigInteger('max_claim_authority_minor')->default(0);$t->jsonb('territories')->default('[]');$t->foreignUuid('approved_by_carrier')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();});
Schema::create('carrier_exchange_messages',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('carrier_id')->constrained();$t->string('direction',16);$t->string('message_type',48);$t->string('correlation_id',80);$t->string('external_reference')->nullable();$t->string('status',24);$t->jsonb('payload');$t->string('payload_hash',64);$t->timestampTz('sent_at')->nullable();$t->timestampTz('acknowledged_at')->nullable();$t->text('failure_reason')->nullable();$t->timestampsTz();$t->unique(['carrier_id','correlation_id','direction']);});
DB::statement("ALTER TABLE bordereaux ADD CONSTRAINT bordereaux_period_valid CHECK (period_end >= period_start)");}
public function down():void{foreach(['carrier_exchange_messages','delegated_authority_agreements','renewal_work_items','bordereau_items','bordereaux','integration_delivery_attempts','integration_webhook_subscriptions','integration_clients','business_calendars','regulatory_reference_sets','report_exports','report_definitions']as$table)Schema::dropIfExists($table);}}
;
