<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('reconciliation_imports',function(Blueprint $t){$t->uuid('id')->primary();$t->string('source_type',32);$t->string('provider',40);$t->string('statement_reference',120);$t->date('period_start');$t->date('period_end');$t->string('currency',3);$t->string('file_hash',64)->unique();$t->string('status',32)->default('UPLOADED');$t->unsignedInteger('total_rows')->default(0);$t->unsignedInteger('matched_rows')->default(0);$t->unsignedInteger('exception_rows')->default(0);$t->foreignUuid('uploaded_by')->constrained('users');$t->timestampTz('completed_at')->nullable();$t->timestampsTz();$t->unique(['provider','statement_reference']);});
Schema::create('reconciliation_items',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('reconciliation_import_id')->constrained()->cascadeOnDelete();$t->string('external_reference',160);$t->dateTimeTz('transaction_at');$t->bigInteger('gross_minor');$t->bigInteger('fee_minor')->default(0);$t->bigInteger('net_minor');$t->string('currency',3);$t->string('status',32)->default('UNMATCHED');$t->string('matched_type',64)->nullable();$t->uuid('matched_id')->nullable();$t->string('exception_code',64)->nullable();$t->text('resolution_notes')->nullable();$t->foreignUuid('resolved_by')->nullable()->constrained('users');$t->timestampTz('resolved_at')->nullable();$t->jsonb('raw_data')->default('{}');$t->timestampsTz();$t->unique(['reconciliation_import_id','external_reference']);});
Schema::create('settlement_items',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('settlement_batch_id')->constrained()->cascadeOnDelete();$t->foreignUuid('policy_id')->constrained();$t->foreignUuid('payment_intent_id')->constrained();$t->bigInteger('gross_premium_minor');$t->bigInteger('commission_minor')->default(0);$t->bigInteger('tax_minor')->default(0);$t->bigInteger('adjustment_minor')->default(0);$t->bigInteger('net_due_minor');$t->string('currency',3);$t->string('status',24)->default('INCLUDED');$t->timestampsTz();$t->unique(['settlement_batch_id','policy_id']);});
Schema::create('settlement_approvals',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('settlement_batch_id')->constrained()->cascadeOnDelete();$t->string('stage',32);$t->string('decision',24);$t->foreignUuid('actor_id')->constrained('users');$t->text('notes');$t->timestampTz('decided_at');$t->unique(['settlement_batch_id','stage']);});
Schema::create('claim_events',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('claim_id')->constrained()->cascadeOnDelete();$t->string('type',40);$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('details')->default('{}');$t->timestampTz('occurred_at');});
Schema::create('claim_documents',function(Blueprint $t){$t->foreignUuid('claim_id')->constrained()->cascadeOnDelete();$t->foreignUuid('document_id')->constrained()->cascadeOnDelete();$t->string('evidence_type',64);$t->string('status',24)->default('SUBMITTED');$t->primary(['claim_id','document_id']);});
Schema::create('document_versions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('document_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('version');$t->string('storage_key');$t->string('sha256',64);$t->bigInteger('size_bytes');$t->string('mime_type',128);$t->foreignUuid('uploaded_by')->nullable()->constrained('users');$t->timestampTz('created_at');$t->unique(['document_id','version']);});
Schema::create('document_access_log',function(Blueprint $t){$t->bigIncrements('id');$t->foreignUuid('document_id')->constrained()->cascadeOnDelete();$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->string('action',24);$t->string('purpose',64);$t->string('request_id',64);$t->timestampTz('occurred_at');});
Schema::create('document_retention_holds',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('document_id')->constrained()->cascadeOnDelete();$t->string('reason_code',64);$t->text('notes');$t->date('hold_until')->nullable();$t->foreignUuid('placed_by')->constrained('users');$t->timestampTz('released_at')->nullable();$t->foreignUuid('released_by')->nullable()->constrained('users');$t->timestampsTz();});
Schema::create('certificate_templates',function(Blueprint $t){$t->uuid('id')->primary();$t->string('type',32);$t->string('code',64);$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->string('template_hash',64);$t->jsonb('layout_schema');$t->date('effective_from');$t->date('effective_until')->nullable();$t->timestampsTz();$t->unique(['code','version']);});
Schema::create('policy_certificates',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('policy_id')->constrained()->cascadeOnDelete();$t->foreignUuid('certificate_template_id')->constrained();$t->string('serial_number',100)->unique();$t->string('verification_token_hash',64)->unique();$t->string('document_hash',64);$t->string('status',24)->default('VALID');$t->timestampTz('issued_at');$t->foreignUuid('issued_by')->constrained('users');$t->timestampTz('voided_at')->nullable();$t->foreignUuid('voided_by')->nullable()->constrained('users');$t->string('void_reason')->nullable();$t->timestampsTz();});
Schema::create('sticker_stock',function(Blueprint $t){$t->uuid('id')->primary();$t->string('serial_number',100)->unique();$t->foreignUuid('carrier_id')->constrained();$t->string('batch_number',100);$t->string('status',24)->default('IN_STOCK');$t->foreignUuid('custodian_tenant_id')->nullable()->constrained('tenants');$t->foreignUuid('assigned_policy_id')->nullable()->constrained('policies');$t->timestampTz('assigned_at')->nullable();$t->timestampsTz();});
Schema::create('sticker_custody_events',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('sticker_stock_id')->constrained('sticker_stock')->cascadeOnDelete();$t->string('event_type',32);$t->foreignUuid('from_tenant_id')->nullable()->constrained('tenants');$t->foreignUuid('to_tenant_id')->nullable()->constrained('tenants');$t->foreignUuid('actor_id')->constrained('users');$t->string('reason_code',64);$t->timestampTz('occurred_at');});
Schema::table('claims',function(Blueprint $t){$t->foreignUuid('claimant_party_id')->nullable()->constrained('parties');$t->string('carrier_reference')->nullable();$t->bigInteger('estimated_loss_minor')->nullable();$t->string('currency',3)->default('XAF');$t->timestampTz('acknowledged_at')->nullable();$t->timestampTz('closed_at')->nullable();});
DB::statement("ALTER TABLE settlement_batches ADD CONSTRAINT settlement_approver_separation CHECK (approved_by IS NULL OR approved_by <> prepared_by)");}
public function down():void{Schema::table('claims',function(Blueprint $t){$t->dropConstrainedForeignId('claimant_party_id');$t->dropColumn(['carrier_reference','estimated_loss_minor','currency','acknowledged_at','closed_at']);});foreach(['sticker_custody_events','sticker_stock','policy_certificates','certificate_templates','document_retention_holds','document_access_log','document_versions','claim_documents','claim_events','settlement_approvals','settlement_items','reconciliation_items','reconciliation_imports']as$table)Schema::dropIfExists($table);}}
;
