<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('disclosure_schema_versions',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('insurance_line_id')->constrained();$t->unsignedInteger('version');$t->string('status',24)->default('DRAFT');$t->jsonb('questions');$t->string('schema_hash',64);$t->date('effective_from');$t->date('effective_until')->nullable();$t->foreignUuid('created_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampTz('approved_at')->nullable();$t->timestampsTz();$t->unique(['insurance_line_id','version']);});
Schema::create('proposal_disclosure_responses',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('proposal_id')->constrained()->cascadeOnDelete();$t->foreignUuid('disclosure_schema_version_id')->constrained();$t->jsonb('answers');$t->jsonb('referral_flags')->default('[]');$t->string('answers_hash',64);$t->timestampTz('attested_at')->nullable();$t->foreignUuid('attested_by')->nullable()->constrained('users');$t->timestampsTz();$t->unique(['proposal_id','disclosure_schema_version_id']);});
Schema::create('document_requirement_versions',function(Blueprint$t){$t->uuid('id')->primary();$t->string('line_code',32);$t->string('code',64);$t->unsignedInteger('version');$t->jsonb('name');$t->jsonb('rules')->default('{}');$t->boolean('mandatory')->default(true);$t->string('status',24)->default('DRAFT');$t->date('effective_from');$t->date('effective_until')->nullable();$t->foreignUuid('created_by')->constrained('users');$t->foreignUuid('approved_by')->nullable()->constrained('users');$t->timestampsTz();$t->unique(['line_code','code','version']);});
Schema::table('proposal_documents',function(Blueprint$t){$t->foreignUuid('document_requirement_version_id')->nullable()->constrained();$t->foreignUuid('verified_by')->nullable()->constrained('users');$t->timestampTz('verified_at')->nullable();$t->text('review_notes')->nullable();});
Schema::create('underwriting_referral_tasks',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('underwriting_case_id')->constrained()->cascadeOnDelete();$t->string('reason_code',64);$t->string('status',24)->default('OPEN');$t->string('severity',16)->default('MEDIUM');$t->foreignUuid('assigned_to')->nullable()->constrained('users');$t->timestampTz('due_at')->nullable();$t->text('resolution_notes')->nullable();$t->foreignUuid('resolved_by')->nullable()->constrained('users');$t->timestampTz('resolved_at')->nullable();$t->timestampsTz();});
Schema::create('proposal_status_history',function(Blueprint$t){$t->uuid('id')->primary();$t->foreignUuid('proposal_id')->constrained()->cascadeOnDelete();$t->string('from_status',32)->nullable();$t->string('to_status',32);$t->string('reason_code',64);$t->foreignUuid('actor_id')->nullable()->constrained('users');$t->jsonb('metadata')->default('{}');$t->timestampTz('occurred_at');});
Schema::table('proposals',function(Blueprint$t){$t->foreignUuid('disclosure_schema_version_id')->nullable()->constrained();$t->foreignUuid('created_by')->nullable()->constrained('users');$t->timestampTz('attested_at')->nullable();});
Schema::table('payment_intents',function(Blueprint$t){$t->foreignUuid('requested_by')->nullable()->constrained('users');$t->timestampTz('expires_at')->nullable();$t->timestampTz('customer_prompted_at')->nullable();$t->string('request_channel',24)->default('WEB');});
DB::statement("ALTER TABLE proposals ADD CONSTRAINT proposal_status_allowed CHECK (status IN ('DRAFT','DISCLOSURES_PENDING','DOCUMENTS_PENDING','SUBMITTED','UNDER_REVIEW','APPROVED','COUNTEROFFERED','DECLINED','PAYMENT_PENDING','WITHDRAWN'))");
DB::statement("ALTER TABLE underwriting_cases ADD CONSTRAINT underwriting_case_status_allowed CHECK (status IN ('QUEUED','IN_REVIEW','AWAITING_INFORMATION','DECIDED','CANCELLED'))");
DB::statement("CREATE UNIQUE INDEX proposal_one_per_offer ON proposals (quote_offer_id) WHERE status <> 'WITHDRAWN'");
}
public function down():void{DB::statement('DROP INDEX IF EXISTS proposal_one_per_offer');DB::statement('ALTER TABLE underwriting_cases DROP CONSTRAINT IF EXISTS underwriting_case_status_allowed');DB::statement('ALTER TABLE proposals DROP CONSTRAINT IF EXISTS proposal_status_allowed');Schema::table('payment_intents',function(Blueprint$t){$t->dropConstrainedForeignId('requested_by');$t->dropColumn(['expires_at','customer_prompted_at','request_channel']);});Schema::table('proposals',function(Blueprint$t){$t->dropConstrainedForeignId('disclosure_schema_version_id');$t->dropConstrainedForeignId('created_by');$t->dropColumn('attested_at');});Schema::dropIfExists('proposal_status_history');Schema::dropIfExists('underwriting_referral_tasks');Schema::table('proposal_documents',function(Blueprint$t){$t->dropConstrainedForeignId('document_requirement_version_id');$t->dropConstrainedForeignId('verified_by');$t->dropColumn(['verified_at','review_notes']);});Schema::dropIfExists('document_requirement_versions');Schema::dropIfExists('proposal_disclosure_responses');Schema::dropIfExists('disclosure_schema_versions');}
};
