<?php
declare(strict_types=1);
namespace App\Application\Partners;
use App\Application\Audit\AuditWriter;use App\Application\Events\OutboxWriter;use App\Models\Partner;use App\Models\PartnerLicence;use App\Models\User;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class LicensingService
{
public function __construct(private readonly AuditWriter$audit,private readonly OutboxWriter$outbox){}
public function submit(Partner$p,array$data):PartnerLicence{return DB::transaction(function()use($p,$data){$expected=match($p->type){'AGENT'=>'AGENT_MANDATE','BROKER'=>'BROKER','CARRIER'=>'CARRIER_AUTHORIZATION'};if($data['licence_type']!==$expected)throw ValidationException::withMessages(['licence_type'=>__('wave1.licence_type_mismatch')]);if(PartnerLicence::where(['authority'=>$data['authority'],'licence_number'=>$data['licence_number']])->exists())throw ValidationException::withMessages(['licence_number'=>__('wave1.licence_exists')]);$licence=$p->licences()->create([...$data,'status'=>'PENDING_VERIFICATION']);$this->audit->record('partner.licence.submitted','partner_licence',$licence->id,['partner_id'=>$p->id]);$this->outbox->record('partner.licence.submitted','partner_licence',$licence->id,['licence_id'=>$licence->id,'partner_id'=>$p->id]);return$licence;});}
public function decide(PartnerLicence$l,string$decision,string$notes,User$actor):PartnerLicence{if($l->status!=='PENDING_VERIFICATION')throw ValidationException::withMessages(['status'=>__('wave1.licence_already_decided')]);if($decision==='VERIFIED'&&$l->expires_on?->isPast())throw ValidationException::withMessages(['expires_on'=>__('wave1.licence_expired')]);return DB::transaction(function()use($l,$decision,$notes,$actor){$l->update(['status'=>$decision,'verified_by'=>$actor->id,'verified_at'=>now(),'verification_notes'=>$notes]);$p=$l->partner;$from=$p->status;$verified=$p->licences()->where('status','VERIFIED')->where(fn($q)=>$q->whereNull('expires_on')->orWhereDate('expires_on','>=',today()))->exists();$to=$verified?'ACTIVE':($decision==='REJECTED'?'REJECTED':$from);if($to!==$from){$p->update(['status'=>$to,'licence_number'=>$verified?$l->licence_number:$p->licence_number,'licence_expires_on'=>$verified?$l->expires_on:$p->licence_expires_on]);DB::table('partner_status_history')->insert(['id'=>(string)Str::uuid(),'partner_id'=>$p->id,'from_status'=>$from,'to_status'=>$to,'reason_code'=>'LICENCE_'.$decision,'notes'=>$notes,'actor_id'=>$actor->id,'occurred_at'=>now()]);}$this->audit->record('partner.licence.decided','partner_licence',$l->id,['decision'=>$decision,'partner_status'=>$to]);$this->outbox->record('partner.licence.decided','partner_licence',$l->id,['licence_id'=>$l->id,'partner_id'=>$p->id,'decision'=>$decision]);return$l->refresh();});}
}
