<?php
namespace App\Interfaces\Http\Controllers\Api\V1\CarrierOperations;use App\Application\Audit\AuditWriter;use App\Domain\CarrierOperations\AuthorityChecker;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class CarrierOperationsController{
public function createAuthority(Request$r,\App\Application\CarrierOperations\DelegatedAuthorityService$svc){$d=$r->validate(['carrier_id'=>'required|uuid|exists:carriers,id','partner_id'=>'required|uuid|exists:partners,id','agreement_number'=>'required|string|max:80|unique:delegated_authority_agreements,agreement_number','effective_from'=>'required|date','effective_until'=>'required|date|after:effective_from','permitted_lines'=>'required|array|min:1','permitted_lines.*'=>'in:AUTOMOBILE,HEALTH,TRAVEL,PROPERTY','max_policy_premium_minor'=>'required|integer|min:0','max_claim_authority_minor'=>'required|integer|min:0','territories'=>'required|array|min:1']);return response()->json(['data'=>$svc->create($d,$r->user())],201);}
public function approveAuthority(Request$r,string$agreement,\App\Application\CarrierOperations\DelegatedAuthorityService$svc){$d=$r->validate(['reason'=>'required|string|min:20|max:2000']);return response()->json(['data'=>$svc->approve($agreement,$r->user(),$d['reason'])]);}
public function checkAuthority(Request$r,string$agreement,\App\Application\CarrierOperations\DelegatedAuthorityService$svc){/* S6: the route had no permission gate; any tenant user could probe any insurer's agreement limits. */abort_unless($r->user()->hasPermission('carrier.authority.manage')||$r->user()->hasPermission('carrier.authority.approve'),403);$da=\Illuminate\Support\Facades\DB::table('delegated_authority_agreements')->where('id',$agreement)->first();abort_unless($da,404);app(\App\Application\Identity\CarrierScopeResolver::class)->abortUnlessOwnCarrier($r->user(),$da->carrier_id,app(\App\Domain\Tenancy\TenantContext::class)->id());$d=$r->validate(['line_code'=>'required|string','premium_minor'=>'required|integer|min:0','territory'=>'required|string','effective_at'=>'required|date']);return response()->json(['data'=>$svc->check($agreement,$d['line_code'],(int)$d['premium_minor'],$d['territory'],new \DateTimeImmutable($d['effective_at']))]);}
/** REQ-DUP-008 deprecated alias of POST bordereaux/{bordereau}/acknowledge|reject: one carrier decision body mapped onto the one BordereauService. Tenant-scoped lookup (cross-tenant IDOR fix): not found or not SUBMITTED => 409. */
public function acknowledgeBordereau(Request$r,string$bordereau,\App\Application\FinancialDistribution\BordereauService$bordereaux){$d=$r->validate(['carrier_reference'=>'required|string|max:160','decision'=>'required|in:ACKNOWLEDGED,REJECTED','notes'=>'required|string|min:20|max:2000']);$tenantId=app(\App\Domain\Tenancy\TenantContext::class)->id();/* Launch fix 2026-09-29: a carrier-linked user decides only its own insurer's bordereaux (same scope as GET mobile/carrier/bordereaux/{id}). */$carrierId=app(\App\Application\Identity\CarrierScopeResolver::class)->carrierIdFor($r->user(),$tenantId);$row=\App\Models\Bordereau::where('tenant_id',$tenantId)->when($carrierId,fn($q,$cid)=>$q->where('carrier_id',$cid))->where('id',$bordereau)->where('status','SUBMITTED')->first();abort_unless($row,409);$b=$d['decision']==='ACKNOWLEDGED'?$bordereaux->acknowledge($row,$d['carrier_reference'],$r->user(),$d['notes']):$bordereaux->reject($row,$d['notes'],$r->user(),$d['carrier_reference']);return response()->json(['data'=>['id'=>$b->id,'status'=>$b->status]]);}
}
