<?php
declare(strict_types=1);
namespace App\Application\Rating;
use App\Application\Audit\AuditWriter;use App\Application\Events\OutboxWriter;use App\Application\Shared\CanonicalJson;use App\Models\InsuranceProduct;use App\Models\TariffVersion;use App\Models\User;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class TariffGovernanceService
{
public function __construct(private readonly CanonicalJson$json,private readonly AuditWriter$audit,private readonly OutboxWriter$outbox){}
public function create(InsuranceProduct$p,array$data,User$actor):TariffVersion{return DB::transaction(function()use($p,$data,$actor){$this->validateRules($data['rules']);$version=(TariffVersion::where('insurance_product_id',$p->id)->lockForUpdate()->max('version')??0)+1;$t=TariffVersion::create(['insurance_product_id'=>$p->id,'version'=>$version,'effective_from'=>$data['effective_from'],'effective_until'=>$data['effective_until']??null,'status'=>'DRAFT','input_schema'=>$data['input_schema'],'rules'=>$data['rules'],'rules_hash'=>$this->json->hash($data['rules']),'created_by'=>$actor->id,'regulatory_reference'=>$data['regulatory_reference']]);$this->audit->record('tariff.created','tariff_version',$t->id,['version'=>$version]);return$t;});}
public function submit(TariffVersion$t,User$actor,string$notes):TariffVersion{$t=$this->transition($t,'DRAFT','IN_REVIEW','SUBMITTED_FOR_REVIEW',$notes,$actor);$this->audit->record('tariff.submitted','tariff_version',$t->id,['version'=>$t->version]);$this->outbox->record('tariff.submitted','tariff_version',$t->id,['tariff_id'=>$t->id]);return$t;}
public function approve(TariffVersion$t,User$actor,string$reason):TariffVersion{if($t->status!=='IN_REVIEW')throw ValidationException::withMessages(['status'=>__('wave2.tariff_not_reviewable')]);if($t->created_by===$actor->id)throw ValidationException::withMessages(['actor'=>__('wave2.maker_checker')]);if($this->json->hash($t->rules)!==$t->rules_hash)throw ValidationException::withMessages(['rules'=>__('wave2.tariff_hash_mismatch')]);$this->validateRules($t->rules);$overlap=TariffVersion::where('insurance_product_id',$t->insurance_product_id)->where('status','APPROVED')->where('id','!=',$t->id)->where(fn($q)=>$q->whereNull('effective_until')->orWhereDate('effective_until','>=',$t->effective_from))->where(fn($q)=>$q->whereDate('effective_from','<=',$t->effective_until??'9999-12-31'))->exists();if($overlap)throw ValidationException::withMessages(['effective_from'=>__('wave2.tariff_overlap')]);return DB::transaction(function()use($t,$actor,$reason){$t->update(['status'=>'APPROVED','approved_by'=>$actor->id,'approved_at'=>now(),'approval_reason'=>$reason]);$this->history($t,'IN_REVIEW','APPROVED','APPROVED',$reason,$actor);$this->audit->record('tariff.approved','tariff_version',$t->id,['rules_hash'=>$t->rules_hash],'APPROVED_TARIFF');$this->outbox->record('tariff.approved','tariff_version',$t->id,['tariff_id'=>$t->id,'product_id'=>$t->insurance_product_id,'rules_hash'=>$t->rules_hash]);return$t->refresh();});}
private function validateRules(array$r):void{if((int)($r['base_premium_minor']??0)<=0)throw ValidationException::withMessages(['rules'=>__('wave2.positive_base_required')]);foreach($r['factors']??[]as$i=>$f){if(!isset($f['code'],$f['fact'],$f['operator'],$f['value'],$f['basis_points']))throw ValidationException::withMessages(["rules.factors.$i"=>__('wave2.factor_incomplete')]);if(!in_array($f['operator'],['EQUALS','IN','BETWEEN'],true)||(int)$f['basis_points'] < -10000||(int)$f['basis_points']>100000)throw ValidationException::withMessages(["rules.factors.$i"=>__('wave2.factor_invalid')]);}}
private function transition(TariffVersion$t,string$from,string$to,string$reason,string$notes,User$actor):TariffVersion{if($t->status!==$from)throw ValidationException::withMessages(['status'=>__('wave2.invalid_tariff_transition')]);$t->update(['status'=>$to]);$this->history($t,$from,$to,$reason,$notes,$actor);return$t->refresh();}
private function history(TariffVersion$t,?string$from,string$to,string$reason,string$notes,User$actor):void{DB::table('tariff_status_history')->insert(['id'=>(string)Str::uuid(),'tariff_version_id'=>$t->id,'from_status'=>$from,'to_status'=>$to,'reason_code'=>$reason,'notes'=>$notes,'actor_id'=>$actor->id,'occurred_at'=>now()]);}
}
