<?php
declare(strict_types=1);namespace App\Application\Payments;
use App\Application\{Audit\AuditWriter,Events\OutboxWriter};use App\Application\Underwriting\Proposal\ProposalDeclarations;use App\Interfaces\Http\Errors\{ApiProblemException,ErrorCode};use App\Models\{PaymentIntentRecord,Proposal,Tenant,User};use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
/**
 * POST /payments. Double-charge guard (owner fix 2026-09-29): a proposal stays PAYMENT_PENDING after a successful payment
 * until the carrier issues, so a NEW idempotency key is refused with 409 PAYMENT_ALREADY_MADE (a SUCCEEDED payment exists)
 * or 409 PAYMENT_IN_PROGRESS (one is with the operator: PROCESSING, or CREATED/PENDING_CUSTOMER with a provider reference
 * that has not expired). The same key still returns the same payment. Terms gate (owner fix 2026-09-30): every payment
 * request needs the TERMS_ACCEPTANCE declaration given by the proposal's OWN party (ProposalDeclarations::acceptedByParty —
 * app terms screen, website review/checkout, or the web acceptance link an agent/broker sends); otherwise 422 terms.
 * An agent/broker/staff acceptance never counts. $requireTerms=false is kept only for internal callers and tests.
 */
final class PaymentRequestService{public function __construct(private AuditWriter$audit,private OutboxWriter$outbox){}
 public function create(Tenant$t,Proposal$p,array$d,User$actor,bool$requireTerms=true):PaymentIntentRecord{if($p->tenant_id!==$t->id||$p->status!=='PAYMENT_PENDING')throw ValidationException::withMessages(['proposal_id'=>__('wave3.payment_not_eligible')]);if($existing=PaymentIntentRecord::where(['tenant_id'=>$t->id,'idempotency_key'=>$d['idempotency_key']])->first())return$existing;$this->assertNotPaid($t,$p);if($requireTerms&&app(ProposalDeclarations::class)->acceptedByParty($p,'TERMS_ACCEPTANCE')===null)throw new ApiProblemException(ErrorCode::TERMS_NOT_ACCEPTED,422,__('api_errors.terms_not_accepted'),['terms'=>[__('api_errors.terms_not_accepted')]]);return DB::transaction(function()use($t,$p,$d,$actor){$amount=(int)$p->terms_snapshot['total_minor'];$intent=PaymentIntentRecord::create(['tenant_id'=>$t->id,'proposal_id'=>$p->id,'provider'=>$d['provider'],'payer_phone_e164'=>$d['payer_phone_e164'],'amount_minor'=>$amount,'currency'=>$p->terms_snapshot['currency'],'status'=>'PENDING_CUSTOMER','idempotency_key'=>$d['idempotency_key'],'provider_snapshot'=>[],'requested_by'=>$actor->id,'expires_at'=>now()->addMinutes(15),'customer_prompted_at'=>now(),'request_channel'=>'WEB']);$this->audit->record('payment.requested','payment_intent',$intent->id,['amount_minor'=>$amount,'provider'=>$d['provider']]);$this->outbox->record('payment.requested','payment_intent',$intent->id,['payment_intent_id'=>$intent->id,'proposal_id'=>$p->id,'provider'=>$d['provider']]);return$intent;});}
 /** 409 when the premium was already collected or a collection is still with the operator (never charge twice). */
 public function assertNotPaid(Tenant$t,Proposal$p):void{$q=fn()=>PaymentIntentRecord::where(['tenant_id'=>$t->id,'proposal_id'=>$p->id]);if($paid=$q()->where('status','SUCCEEDED')->latest('updated_at')->first())throw new ApiProblemException(ErrorCode::PAYMENT_ALREADY_MADE,409,__('api_errors.payment_already_made'),[],['payment_id'=>$paid->id]);$live=$q()->where(fn($w)=>$w->where('status','PROCESSING')->orWhere(fn($x)=>$x->whereIn('status',['CREATED','PENDING_CUSTOMER'])->whereNotNull('provider_reference')->where(fn($e)=>$e->whereNull('expires_at')->orWhere('expires_at','>',now()))))->latest('created_at')->first();if($live)throw new ApiProblemException(ErrorCode::PAYMENT_IN_PROGRESS,409,__('api_errors.payment_in_progress'),[],['payment_id'=>$live->id]);}}
