<?php
namespace App\Filament\Admin\Resources\Claims;use App\Domain\Tenancy\TenantContext;use App\Filament\Admin\Resources\Claims\Pages;use App\Models\Claim;use BackedEnum;use Filament\Actions;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
final class ClaimResource extends \App\Filament\Shared\LocalizedResource{protected static?string$model=Claim::class;protected static string|BackedEnum|null$navigationIcon='lucide-shield-alert';protected static string|\UnitEnum|null$navigationGroup='Claims operations';protected static?int$navigationSort=80;public static function getEloquentQuery():Builder{return \App\Application\WebExperiences\PortalScope::narrowTable(parent::getEloquentQuery()->where('tenant_id',app(TenantContext::class)->id()),'claims');}public static function form(Schema$s):Schema{return$s->components([]);}public static function infolist(Schema$s):Schema{return$s->components(\App\Filament\Shared\Components\RecordShell::detailTabs('claim',self::overview(),['claim.payment.approve',fn($r)=>(int)($r->approved_amount_minor?:$r->current_reserve_minor),fn($r)=>$r->currency],true,[],self::workflowTabs()));}
    /** Payments, disputes and recoveries tabs (the actions on them are in ClaimActions). */
    public static function workflowTabs():array{$o=\App\Filament\Shared\Components\CoreRecordOverview::class;$list=fn(string$rel,array$entries)=>\Filament\Infolists\Components\RepeatableEntry::make($rel)->hiddenLabel()->placeholder(__('web_experience.claim_work.empty'))->columns(['default'=>1,'md'=>4])->schema($entries)->columnSpanFull();$tab=fn(string$key,$entry)=>\Filament\Schemas\Components\Tabs\Tab::make(__('web_experience.tabs.'.$key))->badge(fn($record)=>$record?->{$key}()->count()?:null)->schema([$entry]);return[
        $tab('payments',$list('payments',[$o::money('amount_minor','currency','amount'),$o::status(),$o::date('created_at','requested',true),$o::date('approved_at','approved',true),$o::date('paid_at','paid',true),$o::text('external_reference'),$o::date('reversed_at','reversed',true),$o::text('failure_reason','reason')])),
        $tab('disputes',$list('disputes',[$o::text('reference','number'),$o::status(),$o::text('reason_code'),$o::date('created_at','created',true),$o::text('statement')->columnSpan(2),$o::text('resolution')->columnSpan(2),$o::date('resolved_at','resolved',true)])),
        $tab('recoveries',$list('recoveries',[$o::text('reference','number'),$o::text('type')->badge(),$o::status(),$o::text('counterparty_name','counterparty'),$o::money('target_amount_minor','currency','target_amount'),$o::money('recovered_amount_minor','currency','recovered_amount'),$o::date('due_at','due'),$o::text('dispute_reason','reason')])),
        ...ClaimCaseTabs::tabs(),
    ];}
    /** Overview tab (CoreRecordOverview pattern). */
    public static function overview():array{$o=\App\Filament\Shared\Components\CoreRecordOverview::class;return[$o::section('claim',[$o::text('claim_number','number')->copyable(),$o::status(),$o::text('priority')->badge(),$o::text('policy.policy_number','policy'),$o::text('claimant.display_name','claimant'),$o::text('assignee.full_name','assignee'),$o::text('carrier_reference')]),$o::section('loss',[$o::date('loss_occurred_at','loss_date',true),$o::text('loss_location'),$o::date('submitted_at','submitted',true),$o::date('acknowledged_at','acknowledged',true),$o::date('closed_at','closed',true),$o::text('closure_summary')->columnSpanFull()]),$o::section('amounts',[$o::money('estimated_loss_minor','currency','estimated_loss'),$o::money('current_reserve_minor','currency','reserve'),$o::money('approved_amount_minor','currency','approved_amount')])];}
    public static function table(Table$t):Table{return \App\Filament\Shared\Concerns\ListScreen::apply($t->columns([Tables\Columns\TextColumn::make('claim_number')->searchable()->copyable(),Tables\Columns\TextColumn::make('policy.policy_number')->label('Policy'),Tables\Columns\TextColumn::make('claimant.display_name')->label('Claimant'),\App\Filament\Shared\Columns::status('status'),Tables\Columns\TextColumn::make('priority')->badge(),\App\Filament\Shared\Columns::money('current_reserve_minor'),Tables\Columns\TextColumn::make('assignee.full_name')->label('Assignee'),\App\Filament\Shared\Columns::date('loss_occurred_at')])->recordActions([Actions\ViewAction::make()]),'claims');}public static function getPages():array{return['index'=>Pages\ListClaims::route('/'),'view'=>Pages\ViewClaim::route('/{record}')];}}
