import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { BriefcaseBusiness, Building2, ChevronRight, Shield, Store, UserRound } from 'lucide-react-native';
import { AppHeader, Card, Screen } from '@/components/ui';
import { roleToPortal, useSession } from '@/store/session';
import { colors, radius, space, type } from '@/theme/tokens';

const icons:Record<string,any>={customer:UserRound,agent:BriefcaseBusiness,broker_admin:Store,broker_staff:Store,carrier:Shield,platform_admin:Building2};
const labels:Record<string,[string,string]>={customer:['Customer','Buy and manage my insurance'],agent:['Insurance agent','Serve clients and track commissions'],broker_admin:['Broker administrator','Manage brokerage operations'],broker_staff:['Broker staff','Work with authorised clients'],carrier:['Insurance company','Manage products and referrals'],platform_admin:['Platform operations','Secure administration']};
export default function RoleSelect(){const bootstrap=useSession(s=>s.bootstrap);const selectWorkspace=useSession(s=>s.selectWorkspace);const workspaces=bootstrap?.workspaces??[];const select=async(workspace:typeof workspaces[number])=>{await selectWorkspace(workspace);const portal=roleToPortal(workspace.role_code);if(portal==='customer')router.replace('/(customer)/(tabs)');else if(portal)router.replace({pathname:'/workspace/[role]',params:{role:portal}});};return <Screen><AppHeader title="Choose your workspace" subtitle="Workspaces assigned securely by OpesInsure" back/>{workspaces.length===0?<Card><Text style={styles.title}>No active workspace</Text><Text style={styles.subtitle}>Your account is verified, but no active customer or partner membership has been assigned. Contact support.</Text></Card>:workspaces.map(workspace=>{const portal=roleToPortal(workspace.role_code);const Icon=icons[portal??'']??Building2;const[label,subtitle]=labels[portal??'']??[workspace.role_code,'Authorised workspace'];return <Pressable accessibilityRole="button" accessibilityLabel={`${label}, ${workspace.tenant_name}`} key={workspace.membership_id} onPress={()=>void select(workspace)}><Card><View style={styles.row}><View style={styles.icon}><Icon size={22} color={colors.blue600}/></View><View style={styles.copy}><Text style={styles.title}>{label}</Text><Text style={styles.subtitle}>{workspace.tenant_name} · {subtitle}</Text></View><ChevronRight size={20} color={colors.neutral500}/></View></Card></Pressable>})}</Screen>}
const styles=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',gap:space.x3},icon:{width:44,height:44,borderRadius:radius.control,backgroundColor:colors.blue50,alignItems:'center',justifyContent:'center'},copy:{flex:1},title:{...type.label,color:colors.navy950},subtitle:{...type.meta,color:colors.neutral600}});
