<?php
use App\Models\Tenant;use App\Models\TenantMembership;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;
uses(RefreshDatabase::class);
test('guest is redirected from platform administration',function(){$this->get('/admin')->assertRedirect();});
test('ordinary active tenant member cannot access platform administration',function(){$u=User::factory()->create();$t=Tenant::create(['type'=>'BROKER','legal_name'=>'Test Broker','slug'=>'test-broker','status'=>'ACTIVE','country_code'=>'CM','currency'=>'XAF','primary_locale'=>'en','settings'=>[]]);TenantMembership::create(['tenant_id'=>$t->id,'user_id'=>$u->id,'role_code'=>'CUSTOMER','status'=>'ACTIVE']);expect($u->canAccessPanel(app(\Filament\PanelRegistry::class)->get('admin')))->toBeFalse();});
test('broker staff and commercial agent cannot access platform administration',function(){$u1=User::factory()->create();$u2=User::factory()->create();$t=Tenant::create(['type'=>'BROKER','legal_name'=>'Test Broker 2','slug'=>'test-broker-2','status'=>'ACTIVE','country_code'=>'CM','currency'=>'XAF','primary_locale'=>'en','settings'=>[]]);TenantMembership::create(['tenant_id'=>$t->id,'user_id'=>$u1->id,'role_code'=>'BROKER_STAFF','status'=>'ACTIVE']);TenantMembership::create(['tenant_id'=>$t->id,'user_id'=>$u2->id,'role_code'=>'AGENT','status'=>'ACTIVE']);$panel=app(\Filament\PanelRegistry::class)->get('admin');expect($u1->canAccessPanel($panel))->toBeFalse();expect($u2->canAccessPanel($panel))->toBeFalse();});
test('claims manager inside an insurer tenant sees only that insurer\'s customers in admin',function(){$u=User::factory()->create();$t=Tenant::create(['type'=>'CARRIER','legal_name'=>'Test Carrier','slug'=>'test-carrier-cm','status'=>'ACTIVE','country_code'=>'CM','currency'=>'XAF','primary_locale'=>'en','settings'=>[]]);$other=Tenant::create(['type'=>'CARRIER','legal_name'=>'Other Carrier','slug'=>'other-carrier-cm','status'=>'ACTIVE','country_code'=>'CM','currency'=>'XAF','primary_locale'=>'en','settings'=>[]]);TenantMembership::create(['tenant_id'=>$t->id,'user_id'=>$u->id,'role_code'=>'CLAIMS_MANAGER','status'=>'ACTIVE']);expect($u->canAccessPanel(app(\Filament\PanelRegistry::class)->get('admin')))->toBeTrue();$mine=\App\Models\Party::create(['type'=>'PERSON','display_name'=>'Mine Customer','status'=>'ACTIVE']);$theirs=\App\Models\Party::create(['type'=>'PERSON','display_name'=>'Theirs Customer','status'=>'ACTIVE']);\App\Models\TenantCustomer::create(['tenant_id'=>$t->id,'party_id'=>$mine->id,'customer_number'=>'C-MINE','status'=>'ACTIVE']);\App\Models\TenantCustomer::create(['tenant_id'=>$other->id,'party_id'=>$theirs->id,'customer_number'=>'C-THEIRS','status'=>'ACTIVE']);app(\App\Domain\Tenancy\TenantContext::class)->set($t->id);expect(\App\Filament\Admin\Resources\Parties\PartyResource::getEloquentQuery()->pluck('display_name')->all())->toBe(['Mine Customer']);expect(\App\Filament\Admin\Resources\Customers\CustomerResource::getEloquentQuery()->pluck('customer_number')->all())->toBe(['C-MINE']);});
test('claims manager on the platform tenant can access platform administration',function(){$u=User::factory()->create();$t=Tenant::create(['type'=>'PLATFORM','legal_name'=>'OpesInsure','slug'=>'opesinsure-cm','status'=>'ACTIVE','country_code'=>'CM','currency'=>'XAF','primary_locale'=>'en','settings'=>[]]);TenantMembership::create(['tenant_id'=>$t->id,'user_id'=>$u->id,'role_code'=>'CLAIMS_MANAGER','status'=>'ACTIVE']);expect($u->canAccessPanel(app(\Filament\PanelRegistry::class)->get('admin')))->toBeTrue();});
test('system administrator can access platform administration',function(){$u=User::factory()->create();$t=Tenant::create(['type'=>'PLATFORM','legal_name'=>'OpesInsure','slug'=>'opesinsure','status'=>'ACTIVE','country_code'=>'CM','currency'=>'XAF','primary_locale'=>'en','settings'=>[]]);TenantMembership::create(['tenant_id'=>$t->id,'user_id'=>$u->id,'role_code'=>'SYSTEM_ADMIN','status'=>'ACTIVE']);expect($u->canAccessPanel(app(\Filament\PanelRegistry::class)->get('admin')))->toBeTrue();});
