#!/usr/bin/env node
/**
 * Regenerates src/lib/vendor/pdfjs.ts from the pinned pdfjs-dist devDependency.
 *
 * The WebView PDF fallback (app/documents/view.tsx) must not load pdf.js from a
 * CDN: that fails offline and trusts a third-party host. Instead the legacy
 * (widest WebView support) minified library and worker are inlined as strings
 * in the JS bundle, so an OTA update ships them and upgrades them.
 *
 * Usage: npm install (pdfjs-dist is pinned in devDependencies), then
 *   node scripts/vendor-pdfjs.mjs
 * Keep pdfjs-dist >= 4.2.67 (CVE-2024-4367).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const dist = join(root, "node_modules", "pdfjs-dist");
const { version } = JSON.parse(readFileSync(join(dist, "package.json"), "utf8"));
const [major, minor, patch] = version.split(".").map(Number);
if (major < 4 || (major === 4 && (minor < 2 || (minor === 2 && patch < 67)))) {
  throw new Error(`pdfjs-dist ${version} is vulnerable to CVE-2024-4367; pin >= 4.2.67`);
}
const lib = readFileSync(join(dist, "legacy", "build", "pdf.min.mjs"), "utf8");
const worker = readFileSync(join(dist, "legacy", "build", "pdf.worker.min.mjs"), "utf8");

const out = `/* eslint-disable */
// GENERATED by scripts/vendor-pdfjs.mjs from pdfjs-dist@${version} (legacy build).
// Do not edit. pdf.js is Copyright Mozilla Foundation, Apache License 2.0.
export const PDFJS_VERSION = ${JSON.stringify(version)};
export const PDFJS_LIB_SOURCE: string = ${JSON.stringify(lib)};
export const PDFJS_WORKER_SOURCE: string = ${JSON.stringify(worker)};
`;
mkdirSync(join(root, "src", "lib", "vendor"), { recursive: true });
writeFileSync(join(root, "src", "lib", "vendor", "pdfjs.ts"), out);
console.log(`wrote src/lib/vendor/pdfjs.ts (pdfjs-dist ${version}, ${Math.round(out.length / 1024)} KB)`);
