<?php
namespace App\Filament\Admin\Resources\Parties;
use App\Filament\Admin\Resources\Parties\Pages;use App\Models\Party;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Infolists;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class PartyResource extends Resource
{
protected static?string$model=Party::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedIdentification;protected static string|\UnitEnum|null$navigationGroup='Customers & partners';protected static?string$navigationLabel='People & organizations';protected static?int$navigationSort=20;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Canonical identity')->columnSpanFull()->description('One identity is reused across authorized tenant relationships.')->columns(2)->schema([Forms\Components\Select::make('type')->options(['PERSON'=>'Person','ORGANIZATION'=>'Organization'])->required()->native(false)->live(),Forms\Components\TextInput::make('display_name')->required()->maxLength(160),Forms\Components\TextInput::make('phone_e164')->label('Mobile number')->tel()->regex('/^\+[1-9]\d{7,14}$/'),Forms\Components\TextInput::make('email')->email()->maxLength(190),Forms\Components\DatePicker::make('date_of_birth')->maxDate(now()->subYears(18))->visible(fn($get)=>$get('type')==='PERSON'),Forms\Components\TextInput::make('registration_number')->visible(fn($get)=>$get('type')==='ORGANIZATION'),Forms\Components\Select::make('identifier_type')->options(['NATIONAL_ID'=>'National identity card','PASSPORT'=>'Passport','RCCM'=>'RCCM registration'])->native(false),Forms\Components\TextInput::make('identifier_value')->password()->revealable()->helperText('Encrypted at rest; only a masked value remains visible.'),Forms\Components\TextInput::make('identifier_country')->default('CM')->length(2)])]);}
public static function infolist(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Canonical identity')->columnSpanFull()->columns(2)->schema([Infolists\Components\TextEntry::make('type')->badge(),Infolists\Components\TextEntry::make('display_name')->label('Display name'),Infolists\Components\TextEntry::make('legal_identity.date_of_birth')->label('Date of birth')->date()->placeholder('—')->visible(fn(Party$record)=>$record->type==='PERSON'),Infolists\Components\TextEntry::make('legal_identity.registration_number')->label('Registration number')->placeholder('—')->visible(fn(Party$record)=>$record->type==='ORGANIZATION'),Infolists\Components\TextEntry::make('status')->badge()->color(fn(string$state)=>$state==='ACTIVE'?'success':'gray'),Infolists\Components\TextEntry::make('created_at')->label('Created')->dateTime()]),\Filament\Schemas\Components\Section::make('Contacts')->columnSpanFull()->schema([Infolists\Components\RepeatableEntry::make('contacts')->hiddenLabel()->table([Infolists\Components\RepeatableEntry\TableColumn::make('Type'),Infolists\Components\RepeatableEntry\TableColumn::make('Value')])->schema([Infolists\Components\TextEntry::make('type')->badge(),Infolists\Components\TextEntry::make('normalized_value')])->placeholder('No contacts recorded.')]),\Filament\Schemas\Components\Section::make('Identifiers')->columnSpanFull()->schema([Infolists\Components\RepeatableEntry::make('identifiers')->hiddenLabel()->table([Infolists\Components\RepeatableEntry\TableColumn::make('Type'),Infolists\Components\RepeatableEntry\TableColumn::make('Country'),Infolists\Components\RepeatableEntry\TableColumn::make('Value')])->schema([Infolists\Components\TextEntry::make('type')->badge(),Infolists\Components\TextEntry::make('country_code'),Infolists\Components\TextEntry::make('masked_value')])->placeholder('No identifiers recorded.')])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('display_name')->searchable()->sortable(),Tables\Columns\TextColumn::make('type')->badge(),Tables\Columns\TextColumn::make('contacts.normalized_value')->label('Contacts')->limitList(2)->bulleted(),Tables\Columns\TextColumn::make('identifiers.masked_value')->label('Identity')->limitList(1),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>$state==='ACTIVE'?'success':'gray')])->filters([Tables\Filters\SelectFilter::make('type')->options(['PERSON'=>'Person','ORGANIZATION'=>'Organization'])])->recordActions([Actions\ViewAction::make()])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No canonical identities')->emptyStateDescription('Create a person or organization once, then attach authorized customer or partner relationships.')->emptyStateIcon(Heroicon::OutlinedIdentification);}
public static function getPages():array{return['index'=>Pages\ListParties::route('/'),'create'=>Pages\CreateParty::route('/create'),'view'=>Pages\ViewParty::route('/{record}')];}}
