<?php
namespace App\Filament\Admin\Resources\Quotes;
use App\Domain\Tenancy\TenantContext;use App\Filament\Admin\Resources\Quotes\Pages;use App\Models\Quote;use BackedEnum;use Filament\Actions;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
final class QuoteResource extends Resource{protected static?string$model=Quote::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedScale;protected static string|\UnitEnum|null$navigationGroup='Sales workspace';protected static?int$navigationSort=41;public static function getEloquentQuery():Builder{return \App\Application\WebExperiences\PortalScope::narrowTable(parent::getEloquentQuery()->where('tenant_id',app(TenantContext::class)->id()),'quotes')->withCount('offers');}public static function form(Schema$s):Schema{return$s->components([]);}
    public static function infolist(Schema $s): Schema { return $s->components(\App\Filament\Shared\Components\RecordShell::detailTabs('quote', self::overview(), null, true, ['financial'])); }
    /** Overview tab (CoreRecordOverview pattern). */
    public static function overview(): array { $o = \App\Filament\Shared\Components\CoreRecordOverview::class; return [
        $o::section('quote', [$o::text('quote_number', 'number')->copyable(), $o::status(), $o::text('party.display_name', 'customer'), $o::text('line_code', 'line')->badge(), $o::text('channel')->badge(), $o::text('version')]),
        $o::section('lifecycle', [$o::date('submitted_at', 'submitted', true), $o::date('rated_at', 'rated', true), $o::date('expires_at', 'expires', true), $o::date('accepted_at', 'accepted', true), $o::date('declined_at', 'declined', true), $o::text('decline_reason_code', 'decline_reason')]),
    ]; }
    public static function table(Table$t):Table{return \App\Filament\Shared\Concerns\ListScreen::apply($t->columns([Tables\Columns\TextColumn::make('id')->label('Quote')->copyable()->limit(12),Tables\Columns\TextColumn::make('party.display_name')->label('Customer')->searchable(),Tables\Columns\TextColumn::make('line_code')->badge(),Tables\Columns\TextColumn::make('channel')->badge(),Tables\Columns\TextColumn::make('offers_count')->label('Offers'),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'OFFERED','ACCEPTED'=>'success','REFERRED'=>'warning','EXPIRED','CANCELLED'=>'danger',default=>'info'}),Tables\Columns\TextColumn::make('expires_at')->dateTime()])->recordActions([Actions\ViewAction::make()])->emptyStateHeading('No quotes yet')->emptyStateDescription('Submitted quotes appear here with ranked carrier offers and transparent price breakdowns.')->emptyStateIcon(Heroicon::OutlinedScale),'quotes');}public static function getPages():array{return['index'=>Pages\ListQuotes::route('/'),'view'=>Pages\ViewQuote::route('/{record}')];}}
