<?php
namespace App\Interfaces\Http\Controllers\Api\V1\Commissions;

use App\Application\Audit\AuditWriter; use App\Domain\Commissions\CommissionCalculator; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;

final class CommissionController
{
    public function createRule(Request $r,AuditWriter $audit){$d=$r->validate(['carrier_id'=>'required|uuid|exists:carriers,id','product_id'=>'nullable|uuid|exists:insurance_products,id','partner_id'=>'nullable|uuid|exists:partners,id','effective_from'=>'required|date','effective_until'=>'nullable|date|after:effective_from','basis_points'=>'required|integer|min:0|max:10000','vesting_days'=>'required|integer|min:0|max:365','holdback_basis_points'=>'required|integer|min:0|max:10000','conditions'=>'sometimes|array']);$v=(DB::table('commission_rule_versions')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where(['carrier_id'=>$d['carrier_id'],'product_id'=>$d['product_id']??null,'partner_id'=>$d['partner_id']??null])->max('version')??0)+1;$canonical=json_encode($d,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);$id=(string)Str::uuid();DB::table('commission_rule_versions')->insert([...$d,'id'=>$id,'tenant_id'=>app(\App\Domain\Tenancy\TenantContext::class)->id(),'created_by'=>$r->user()->id,'version'=>$v,'status'=>'DRAFT','conditions'=>json_encode($d['conditions']??[]),'rule_hash'=>hash('sha256',$canonical),'created_at'=>now(),'updated_at'=>now()]);$audit->record('commission.rule.created','commission_rule_version',$id,['version'=>$v]);return response()->json(['data'=>['id'=>$id,'version'=>$v,'status'=>'DRAFT']],201);}
    public function approveRule(Request $r,string $rule,AuditWriter $audit){$d=$r->validate(['reason'=>'required|string|min:20|max:2000']);$existing=DB::table('commission_rule_versions')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$rule)->where('status','DRAFT')->first();abort_unless($existing,409,'Only a draft commission rule can be activated.');abort_if($existing->created_by===$r->user()->id,403,'The maker of a commission rule cannot approve it.');$updated=DB::table('commission_rule_versions')->where('id',$rule)->where('status','DRAFT')->update(['status'=>'ACTIVE','updated_at'=>now()]);abort_unless($updated,409,'Only a draft commission rule can be activated.');$audit->record('commission.rule.activated','commission_rule_version',$rule,[],'RULE_APPROVED');return response()->json(['data'=>['id'=>$rule,'status'=>'ACTIVE']]);}
    public function accrue(Request $r,CommissionCalculator $calculator,AuditWriter $audit){$d=$r->validate(['policy_id'=>'required|uuid|exists:policies,id','partner_id'=>'required|uuid|exists:partners,id','rule_version_id'=>'required|uuid|exists:commission_rule_versions,id']);$policy=DB::table('policies')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$d['policy_id'])->where('status','ACTIVE')->first();abort_unless($policy,422,'An active tenant policy is required.');abort_if(DB::table('commission_accruals')->where('tenant_id',$policy->tenant_id)->where(['policy_id'=>$policy->id,'partner_id'=>$d['partner_id']])->exists(),409,'Commission already accrued for this policy and partner.');$rule=DB::table('commission_rule_versions')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$d['rule_version_id'])->where('status','ACTIVE')->first();abort_unless($rule,422,'An active commission rule is required.');$calc=$calculator->calculate($policy->premium_minor,$rule->basis_points,$rule->holdback_basis_points);$id=(string)Str::uuid();DB::transaction(function()use($id,$d,$policy,$rule,$calc,$audit){DB::table('commission_accruals')->insert(['id'=>$id,'tenant_id'=>$policy->tenant_id,'policy_id'=>$policy->id,'partner_id'=>$d['partner_id'],'rule_version_id'=>$rule->id,'rule_version'=>(string)$rule->version,'amount_minor'=>$calc->grossMinor,'vested_minor'=>0,'paid_minor'=>0,'clawed_back_minor'=>0,'currency'=>$policy->currency,'status'=>'ACCRUED','vests_at'=>now()->addDays($rule->vesting_days),'created_at'=>now(),'updated_at'=>now()]);DB::table('commission_movements')->insert(['id'=>(string)Str::uuid(),'commission_accrual_id'=>$id,'type'=>'ACCRUAL','amount_minor'=>$calc->netAccruedMinor,'currency'=>$policy->currency,'reason_code'=>'POLICY_ISSUED','occurred_at'=>now(),'metadata'=>json_encode(['gross_minor'=>$calc->grossMinor,'holdback_minor'=>$calc->holdbackMinor])]);$audit->record('commission.accrued','commission_accrual',$id,['amount_minor'=>$calc->grossMinor]);});return response()->json(['data'=>['id'=>$id,'gross_minor'=>$calc->grossMinor,'holdback_minor'=>$calc->holdbackMinor,'status'=>'ACCRUED']],201);}
    public function vest(string $accrual,AuditWriter $audit){$row=DB::table('commission_accruals')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$accrual)->where('status','ACCRUED')->lockForUpdate()->first();abort_unless($row,409,'Accrual is not eligible for vesting.');abort_if(now()->lessThan($row->vests_at),409,'Commission vesting date has not been reached.');$amount=$row->amount_minor-$row->clawed_back_minor;DB::transaction(function()use($row,$amount,$audit){DB::table('commission_accruals')->where('id',$row->id)->update(['vested_minor'=>$amount,'status'=>'VESTED','updated_at'=>now()]);DB::table('commission_movements')->insert(['id'=>(string)Str::uuid(),'commission_accrual_id'=>$row->id,'type'=>'VESTING','amount_minor'=>$amount,'currency'=>$row->currency,'reason_code'=>'VESTING_DATE_REACHED','occurred_at'=>now(),'metadata'=>'{}']);$audit->record('commission.vested','commission_accrual',$row->id,['amount_minor'=>$amount]);});return response()->json(['data'=>['id'=>$accrual,'vested_minor'=>$amount,'status'=>'VESTED']]);}
    public function clawback(Request $r,string $accrual,AuditWriter $audit){$d=$r->validate(['amount_minor'=>'required|integer|min:1','reason_code'=>'required|string|max:64','notes'=>'required|string|min:20|max:2000']);$row=DB::table('commission_accruals')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('id',$accrual)->lockForUpdate()->first();abort_unless($row,404);abort_if($row->clawed_back_minor+$d['amount_minor']>$row->amount_minor,422,'Clawback exceeds the accrued amount.');DB::transaction(function()use($row,$d,$r,$audit){DB::table('commission_accruals')->where('id',$row->id)->update(['clawed_back_minor'=>$row->clawed_back_minor+$d['amount_minor'],'status'=>'CLAWED_BACK','updated_at'=>now()]);DB::table('commission_movements')->insert(['id'=>(string)Str::uuid(),'commission_accrual_id'=>$row->id,'type'=>'CLAWBACK','amount_minor'=>-$d['amount_minor'],'currency'=>$row->currency,'reason_code'=>$d['reason_code'],'actor_id'=>$r->user()->id,'occurred_at'=>now(),'metadata'=>json_encode(['notes'=>$d['notes']])]);$audit->record('commission.clawed_back','commission_accrual',$row->id,['amount_minor'=>$d['amount_minor']],$d['reason_code']);});return response()->json(['data'=>['id'=>$accrual,'status'=>'CLAWED_BACK']]);}
    public function balance(string $partner){$rows=DB::table('commission_accruals')->where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where('partner_id',$partner)->selectRaw("currency, SUM(amount_minor-clawed_back_minor) as earned_minor, SUM(vested_minor-paid_minor) as available_minor, SUM(paid_minor) as paid_minor")->groupBy('currency')->get();return response()->json(['data'=>$rows]);}
}
