<?php
declare(strict_types=1); namespace App\Application\FinancialDistribution;
use App\Application\{Audit\AuditWriter,Events\OutboxWriter}; use App\Models\{Bordereau,BordereauItem,Policy,User}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
final class BordereauService { public function __construct(private AuditWriter$audit,private OutboxWriter$outbox,private DistributionEventWriter$events){}
 public function prepare(array$d,User$actor):Bordereau{return DB::transaction(function()use($d,$actor){if($e=Bordereau::where('tenant_id',$d['tenant_id'])->where('idempotency_key',$d['idempotency_key'])->first())return$e;DB::statement('SELECT pg_advisory_xact_lock(hashtext(?))',[implode(':',[$d['tenant_id'],$d['carrier_id'],$d['type'],$d['period_start'],$d['period_end']])]);$explicit=array_values(array_unique($d['policy_ids']??[]));unset($d['policy_ids']);$policies=Policy::where('tenant_id',$d['tenant_id'])->where('carrier_id',$d['carrier_id'])->when($explicit!==[],fn($q)=>$q->whereIn('id',$explicit),fn($q)=>$q->whereBetween('issued_at',[$d['period_start'],$d['period_end'].' 23:59:59']))->lockForUpdate()->get();if($explicit!==[]&&$policies->count()!==count($explicit))throw ValidationException::withMessages(['policy_ids'=>__('wave6.policy_selection_invalid')]);$payload=[];$gross=0;$commission=0;foreach($policies as$p){$c=(int)DB::table('commission_accruals')->where('tenant_id',$d['tenant_id'])->where('policy_id',$p->id)->sum('amount_minor');$payload[]=[$p->id,$p->premium_minor,$c];$gross+=$p->premium_minor;$commission+=$c;}$b=Bordereau::create([...$d,'bordereau_number'=>'BOR-'.now()->format('Ymd').'-'.strtoupper(Str::random(8)),'status'=>'DRAFT','item_count'=>count($payload),'gross_premium_minor'=>$gross,'commission_minor'=>$commission,'content_hash'=>hash('sha256',json_encode($payload,JSON_THROW_ON_ERROR)),'prepared_by'=>$actor->id]);foreach($payload as[$policy,$premium,$c])BordereauItem::create(['bordereau_id'=>$b->id,'policy_id'=>$policy,'transaction_type'=>'NEW_BUSINESS','premium_minor'=>$premium,'commission_minor'=>$c,'currency'=>$d['currency'],'effective_at'=>now()]);$this->audit->record('bordereau.prepared','bordereau',$b->id,['item_count'=>$b->item_count]);return$b->load('items');});}
 public function approve(Bordereau$b,User$actor):Bordereau{return$this->move($b,'DRAFT','APPROVED','APPROVED',$actor,['approved_by'=>$actor->id,'approved_at'=>now()],true);}
 public function submit(Bordereau$b,User$actor):Bordereau{return$this->move($b,'APPROVED','SUBMITTED','SUBMITTED_TO_CARRIER',$actor,['submitted_by'=>$actor->id,'submitted_at'=>now()]);}
 public function acknowledge(Bordereau$b,string$reference,User$actor):Bordereau{return$this->move($b,'SUBMITTED','ACKNOWLEDGED','CARRIER_ACKNOWLEDGED',$actor,['carrier_reference'=>$reference,'acknowledged_at'=>now()]);}
 public function reject(Bordereau$b,string$reason,User$actor):Bordereau{return$this->move($b,'SUBMITTED','REJECTED','CARRIER_REJECTED',$actor,['rejection_reason'=>$reason]);}
 private function move(Bordereau$b,string$from,string$to,string$reason,User$actor,array$attrs,bool$separate=false):Bordereau{return DB::transaction(function()use($b,$from,$to,$reason,$actor,$attrs,$separate){$b=Bordereau::lockForUpdate()->findOrFail($b->id);if($b->status!==$from||($separate&&$b->prepared_by===$actor->id))throw ValidationException::withMessages(['bordereau'=>__('wave6.invalid_transition')]);$b->update(['status'=>$to,...$attrs]);$this->events->write($b->tenant_id,'BORDEREAU',$b->id,$from,$to,$reason,$actor);$this->outbox->record('bordereau.'.strtolower($to),'bordereau',$b->id,['bordereau_id'=>$b->id]);return$b->refresh();});}
}
