<?php
declare(strict_types=1); namespace App\Application\FinancialDistribution;
use App\Application\{Audit\AuditWriter,Bordereaux\BordereauItemSource,Events\OutboxWriter}; use App\Models\{Bordereau,BordereauItem,Policy,User}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
/**
 * REQ-STL-002 / REQ-DUP-008 — the ONE carrier bordereau service (broker -> carrier premium/claim/... bordereau).
 * Every route family (bordereaux/*, the deprecated broker/bordereaux/* and carrier/bordereaux/{b}/decision aliases)
 * goes through it. Items per type come from App\Application\Bordereaux\BordereauItemSource.
 * Not the reinsurance treaty bordereau (App\Application\Reinsurance\TreatyBordereauService).
 */
final class BordereauService { public function __construct(private AuditWriter$audit,private OutboxWriter$outbox,private DistributionEventWriter$events,private BordereauItemSource$sources){}
 public function prepare(array$d,User$actor):Bordereau{return DB::transaction(function()use($d,$actor){if($e=Bordereau::where('tenant_id',$d['tenant_id'])->where('idempotency_key',$d['idempotency_key'])->first())return$e->load('items');DB::statement('SELECT pg_advisory_xact_lock(hashtext(?))',[implode(':',[$d['tenant_id'],$d['carrier_id'],$d['type'],$d['period_start'],$d['period_end']])]);$explicit=array_values(array_unique($d['policy_ids']??[]));unset($d['policy_ids']);if($explicit!==[]&&Policy::where('tenant_id',$d['tenant_id'])->where('carrier_id',$d['carrier_id'])->whereIn('id',$explicit)->count()!==count($explicit))throw ValidationException::withMessages(['policy_ids'=>__('wave6.policy_selection_invalid')]);
  $items=$this->sources->items($d['tenant_id'],$d['carrier_id'],$d['type'],(string)$d['period_start'],(string)$d['period_end'],$d['currency'],$explicit);$hash=array_map(fn($i)=>[$i['source_type'],$i['source_id'],$i['amount_minor'],$i['commission_minor']],$items);
  $b=Bordereau::create([...$d,'bordereau_number'=>'BOR-'.now()->format('Ymd').'-'.strtoupper(Str::random(8)),'status'=>'DRAFT','item_count'=>count($items),'gross_premium_minor'=>array_sum(array_column($items,'premium_minor')),'commission_minor'=>array_sum(array_column($items,'commission_minor')),'total_amount_minor'=>array_sum(array_column($items,'amount_minor')),'content_hash'=>hash('sha256',json_encode($hash,JSON_THROW_ON_ERROR)),'prepared_by'=>$actor->id]);
  foreach($items as$i)BordereauItem::create([...$i,'bordereau_id'=>$b->id,'currency'=>$d['currency']]);$this->audit->record('bordereau.prepared','bordereau',$b->id,['type'=>$b->type,'item_count'=>$b->item_count]);$this->outbox->record('bordereau.prepared','bordereau',$b->id,['bordereau_id'=>$b->id,'type'=>$b->type,'item_count'=>$b->item_count]);return$b->load('items');});}
 public function approve(Bordereau$b,User$actor):Bordereau{return$this->move($b,'DRAFT','APPROVED','APPROVED','bordereau.approved',$actor,['approved_by'=>$actor->id,'approved_at'=>now()],true);}
 /** The preparer may not submit either (the former broker rule, now applied on every route). */
 public function submit(Bordereau$b,User$actor,?string$notes=null):Bordereau{return$this->move($b,'APPROVED','SUBMITTED','SUBMITTED_TO_CARRIER','bordereau.submitted',$actor,['submitted_by'=>$actor->id,'submitted_at'=>now()],true,$notes);}
 public function acknowledge(Bordereau$b,string$reference,User$actor,?string$notes=null):Bordereau{return$this->move($b,'SUBMITTED','ACKNOWLEDGED','CARRIER_ACKNOWLEDGED','bordereau.acknowledged',$actor,['carrier_reference'=>$reference,'acknowledged_at'=>now()],false,$notes);}
 public function reject(Bordereau$b,string$reason,User$actor,?string$reference=null):Bordereau{return$this->move($b,'SUBMITTED','REJECTED','CARRIER_REJECTED','bordereau.rejected',$actor,array_filter(['rejection_reason'=>$reason,'carrier_reference'=>$reference]),false,$reason);}
 private function move(Bordereau$b,string$from,string$to,string$reason,string$event,User$actor,array$attrs,bool$separate=false,?string$notes=null):Bordereau{return DB::transaction(function()use($b,$from,$to,$reason,$event,$actor,$attrs,$separate,$notes){$b=Bordereau::lockForUpdate()->findOrFail($b->id);if($b->status!==$from||($separate&&$b->prepared_by===$actor->id))throw ValidationException::withMessages(['bordereau'=>__('wave6.invalid_transition')]);$b->update(['status'=>$to,...$attrs]);$this->events->write($b->tenant_id,'BORDEREAU',$b->id,$from,$to,$reason,$actor);$this->audit->record($event,'bordereau',$b->id,array_filter(['from'=>$from,'to'=>$to,'notes'=>$notes]));$this->outbox->record($event,'bordereau',$b->id,['bordereau_id'=>$b->id]);return$b->refresh();});}
}
