<?php
declare(strict_types=1); namespace App\Application\FinancialDistribution;
use App\Application\{Audit\AuditWriter,Events\OutboxWriter}; use App\Models\{Policy,SettlementBatch,User}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
final class CarrierSettlementService { public function __construct(private AuditWriter$audit,private OutboxWriter$outbox,private DistributionEventWriter$events){}
 public function prepare(array$d,User$actor):SettlementBatch{return DB::transaction(function()use($d,$actor){if($e=SettlementBatch::where('tenant_id',$d['tenant_id'])->where('idempotency_key',$d['idempotency_key'])->first())return$e;DB::statement('SELECT pg_advisory_xact_lock(hashtext(?))',[implode(':',[$d['tenant_id'],$d['carrier_id'],$d['period_start'],$d['period_end'],$d['currency']])]);$policies=Policy::where('tenant_id',$d['tenant_id'])->where('carrier_id',$d['carrier_id'])->where('status','ACTIVE')->where('currency',$d['currency'])->whereBetween('issued_at',[$d['period_start'],$d['period_end'].' 23:59:59'])->whereNotNull('payment_intent_id')->lockForUpdate()->get();$items=[];$net=0;foreach($policies as$p){$commission=(int)DB::table('commission_accruals')->where('policy_id',$p->id)->sum('amount_minor');$due=$p->premium_minor-$commission;if($due<0)throw ValidationException::withMessages(['settlement'=>__('wave6.negative_settlement')]);$net+=$due;$items[]=[$p,$commission,$due];}$hash=hash('sha256',json_encode(array_map(fn($x)=>[$x[0]->id,$x[1],$x[2]],$items),JSON_THROW_ON_ERROR));$b=SettlementBatch::create([...$d,'settlement_number'=>'SET-'.now()->format('Ymd').'-'.strtoupper(Str::random(8)),'net_amount_minor'=>$net,'status'=>'DRAFT','prepared_by'=>$actor->id,'content_hash'=>$hash]);foreach($items as[$p,$commission,$due])DB::table('settlement_items')->insert(['id'=>(string)Str::uuid(),'settlement_batch_id'=>$b->id,'policy_id'=>$p->id,'payment_intent_id'=>$p->payment_intent_id,'gross_premium_minor'=>$p->premium_minor,'commission_minor'=>$commission,'tax_minor'=>0,'adjustment_minor'=>0,'net_due_minor'=>$due,'currency'=>$p->currency,'status'=>'INCLUDED','created_at'=>now(),'updated_at'=>now()]);$this->audit->record('carrier_settlement.prepared','settlement_batch',$b->id,['net_amount_minor'=>$net]);return$b;});}
 public function approve(SettlementBatch$b,User$actor,?string$notes=null):SettlementBatch{return DB::transaction(function()use($b,$actor,$notes){$s=$this->move($b,'DRAFT','APPROVED','APPROVED',$actor,['approved_by'=>$actor->id,'approved_at'=>now()],true);/* settlement_approvals was previously written only by the legacy controller. The events trail records the transition, but not the stage, the deciding actor's reasoning, or a per-stage decision record, so the governed path adopts it rather than leaving it to rot. */DB::table('settlement_approvals')->insert(['id'=>(string)Str::uuid(),'settlement_batch_id'=>$s->id,'stage'=>'FINANCE_APPROVAL','decision'=>'APPROVED','actor_id'=>$actor->id,'notes'=>$notes?:__('wave6.settlement_approved_default_note'),'decided_at'=>now()]);return$s;});}
 public function submit(SettlementBatch$b,User$actor):SettlementBatch{return$this->move($b,'APPROVED','SUBMITTED','BANK_SUBMITTED',$actor,['submitted_at'=>now()]);}
 public function markPaid(SettlementBatch$b,string$reference,User$actor):SettlementBatch{return$this->move($b,'SUBMITTED','PAID','BANK_CONFIRMED',$actor,['paid_at'=>now(),'bank_reference'=>$reference]);}
 public function fail(SettlementBatch$b,string$reason,User$actor):SettlementBatch{return$this->move($b,'SUBMITTED','FAILED','BANK_FAILED',$actor,['failure_reason'=>$reason]);}
 public function reverse(SettlementBatch$b,string$reason,User$actor):SettlementBatch{return$this->move($b,'PAID','REVERSED',$reason,$actor,['failure_reason'=>$reason]);}
 private function move(SettlementBatch$b,string$from,string$to,string$reason,User$actor,array$attrs,bool$separate=false):SettlementBatch{return DB::transaction(function()use($b,$from,$to,$reason,$actor,$attrs,$separate){$b=SettlementBatch::lockForUpdate()->findOrFail($b->id);/* Batch 10-4: ledger-calculated batches follow App\Application\Settlements\SettlementService's lifecycle. */if(($b->calculation_basis??'POLICY')!=='POLICY'||$b->status!==$from||($separate&&$b->prepared_by===$actor->id))throw ValidationException::withMessages(['settlement'=>__('wave6.invalid_transition')]);$b->update(['status'=>$to,...$attrs]);$this->events->write($b->tenant_id,'CARRIER_SETTLEMENT',$b->id,$from,$to,$reason,$actor);$this->outbox->record('carrier.settlement.'.strtolower($to),'settlement_batch',$b->id,['settlement_id'=>$b->id]);return$b->refresh();});}
}
