<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('claims', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('claim_number'); $table->foreignId('policy_id')->constrained('policies'); $table->timestampTz('loss_at'); $table->timestampTz('reported_at'); $table->foreignId('reported_by_party_id')->constrained('parties'); $table->string('claim_type'); $table->unsignedBigInteger('cause_of_loss_id')->nullable(); $table->char('currency',3); $table->string('status')->default('DRAFT'); $table->foreignId('assigned_to')->nullable()->constrained('users'); $table->unsignedBigInteger('catastrophe_event_id')->nullable(); $table->text('description')->nullable(); $table->timestampsTz(); $table->unique(['tenant_id','claim_number']); $table->index(['policy_id','status']); $table->index('loss_at'); });
        Schema::create('claim_parties', function (Blueprint $table) { $table->id(); $table->foreignId('claim_id')->constrained('claims'); $table->foreignId('party_id')->constrained('parties'); $table->string('role_type'); $table->string('relationship_to_loss')->nullable(); $table->boolean('is_injured')->default(false); $table->boolean('is_deceased')->default(false); });
        Schema::create('claim_coverage_assessments', function (Blueprint $table) { $table->id(); $table->foreignId('claim_id')->constrained('claims'); $table->foreignId('coverage_id')->constrained('coverages'); $table->foreignId('policy_version_id')->constrained('policy_versions'); $table->boolean('coverage_at_loss'); $table->string('reason_code')->nullable(); $table->decimal('available_limit',20,4)->nullable(); $table->decimal('reserved_amount',20,4)->default(0); $table->decimal('deductible',20,4)->default(0); $table->char('currency',3); $table->jsonb('assessment_snapshot_json'); $table->foreignId('assessed_by')->constrained('users'); $table->timestampTz('assessed_at')->useCurrent(); });
        Schema::create('claim_reserves', function (Blueprint $table) { $table->id(); $table->foreignId('claim_id')->constrained('claims'); $table->foreignId('coverage_id')->nullable()->constrained('coverages'); $table->string('reserve_type'); $table->char('currency',3); $table->decimal('current_amount',20,4)->default(0); $table->string('status')->default('OPEN'); });
        Schema::create('claim_reserve_movements', function (Blueprint $table) { $table->id(); $table->foreignId('claim_reserve_id')->constrained('claim_reserves'); $table->string('movement_type'); $table->decimal('previous_amount',20,4); $table->decimal('movement_amount',20,4); $table->decimal('new_amount',20,4); $table->text('reason'); $table->foreignId('created_by')->constrained('users'); $table->foreignId('approved_by')->nullable()->constrained('users'); $table->timestampTz('created_at')->useCurrent(); });
        Schema::create('claim_decisions', function (Blueprint $table) { $table->id(); $table->foreignId('claim_id')->constrained('claims'); $table->string('decision'); $table->decimal('approved_amount',20,4)->default(0); $table->char('currency',3); $table->string('reason_code')->nullable(); $table->foreignId('decision_by')->constrained('users'); $table->string('authority_reference')->nullable(); $table->timestampTz('decision_at')->useCurrent(); });
        Schema::create('recoveries', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('claim_id')->constrained('claims'); $table->string('recovery_type'); $table->foreignId('counterparty_party_id')->constrained('parties'); $table->decimal('expected_amount',20,4); $table->decimal('received_amount',20,4)->default(0); $table->char('currency',3); $table->string('status')->default('EXPECTED'); $table->timestampTz('opened_at')->useCurrent(); $table->timestampTz('closed_at')->nullable(); });
        Schema::create('provider_profiles', function (Blueprint $table) { $table->foreignId('organization_id')->primary()->constrained('organizations'); $table->string('provider_type'); $table->string('credential_status')->default('PROSPECT'); $table->string('status')->default('PROSPECT'); });
        Schema::create('provider_networks', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('insurer_id')->constrained('organizations'); $table->string('code'); $table->string('name'); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('DRAFT'); $table->unique(['insurer_id','code']); });
        Schema::create('provider_contracts', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('insurer_id')->constrained('organizations'); $table->foreignId('provider_id')->constrained('organizations'); $table->foreignId('network_id')->nullable()->constrained('provider_networks'); $table->string('contract_number'); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->jsonb('billing_terms_json')->nullable(); $table->jsonb('settlement_terms_json')->nullable(); $table->string('status')->default('DRAFT'); });
        Schema::create('preauthorizations', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('preauth_number'); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('member_party_id')->constrained('parties'); $table->foreignId('provider_id')->constrained('organizations'); $table->unsignedBigInteger('service_id'); $table->decimal('requested_amount',20,4); $table->decimal('approved_amount',20,4)->nullable(); $table->char('currency',3); $table->text('clinical_justification')->nullable(); $table->string('status')->default('DRAFT'); $table->timestampTz('requested_at')->useCurrent(); $table->timestampTz('decided_at')->nullable(); $table->timestampTz('valid_until')->nullable(); $table->unique(['tenant_id','preauth_number']); });
        Schema::create('provider_claims', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('provider_claim_number'); $table->foreignId('provider_id')->constrained('organizations'); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('member_party_id')->constrained('parties'); $table->foreignId('preauthorization_id')->nullable()->constrained('preauthorizations'); $table->decimal('amount_billed',20,4); $table->decimal('amount_allowed',20,4)->nullable(); $table->decimal('member_responsibility',20,4)->nullable(); $table->decimal('insurer_payable',20,4)->nullable(); $table->char('currency',3); $table->string('status')->default('DRAFT'); $table->timestampTz('submitted_at')->nullable(); $table->unique(['tenant_id','provider_claim_number']); });
        Schema::create('reinsurance_treaties', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('cedant_id')->constrained('organizations'); $table->string('treaty_number'); $table->string('treaty_type'); $table->char('currency',3); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('DRAFT'); $table->decimal('retention_amount',20,4)->nullable(); $table->decimal('capacity_amount',20,4)->nullable(); $table->jsonb('terms_json')->nullable(); $table->unique(['cedant_id','treaty_number']); });
        Schema::create('risk_cessions', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('policy_risk_id')->constrained('policy_risks'); $table->foreignId('treaty_id')->nullable()->constrained('reinsurance_treaties'); $table->unsignedBigInteger('facultative_placement_id')->nullable(); $table->decimal('gross_exposure',20,4); $table->decimal('retained_exposure',20,4); $table->decimal('ceded_exposure',20,4); $table->char('currency',3); $table->string('status')->default('CALCULATED'); $table->timestampTz('calculated_at')->useCurrent(); });
        Schema::create('coinsurance_arrangements', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('lead_insurer_id')->constrained('organizations'); $table->string('status')->default('DRAFT'); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); });
    }

    public function down(): void
    {
        // Reverse in dependency-safe order in production migrations.
        // Scaffold intentionally avoids destructive blanket drops.
    }
};
