<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('insurance_products', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('insurer_id')->constrained('organizations'); $table->string('code'); $table->string('name'); $table->unsignedBigInteger('product_family_id'); $table->string('product_type'); $table->foreignId('owner_user_id')->nullable()->constrained('users'); $table->string('status')->default('DRAFT'); $table->timestampsTz(); $table->unique(['insurer_id','code']); });
        Schema::create('product_versions', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('product_id')->constrained('insurance_products'); $table->unsignedInteger('version_number'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('DRAFT'); $table->timestampTz('submitted_at')->nullable(); $table->timestampTz('approved_at')->nullable(); $table->foreignId('approved_by')->nullable()->constrained('users'); $table->timestampTz('published_at')->nullable(); $table->jsonb('configuration_snapshot_json')->nullable(); $table->unique(['product_id','version_number']); });
        Schema::create('product_regulatory_mappings', function (Blueprint $table) { $table->id(); $table->foreignId('product_version_id')->constrained('product_versions'); $table->foreignId('insurance_branch_id')->constrained('insurance_branches'); $table->string('relationship_type'); $table->unique(['product_version_id','insurance_branch_id','relationship_type'], 'product_reg_map_unique'); });
        Schema::create('product_plans', function (Blueprint $table) { $table->id(); $table->foreignId('product_version_id')->constrained('product_versions'); $table->string('code'); $table->string('name'); $table->text('description')->nullable(); $table->string('status')->default('ACTIVE'); $table->unique(['product_version_id','code']); });
        Schema::create('coverages', function (Blueprint $table) { $table->id(); $table->string('code')->unique(); $table->string('name_en'); $table->string('name_fr'); $table->string('coverage_category'); $table->string('status')->default('ACTIVE'); });
        Schema::create('product_coverages', function (Blueprint $table) { $table->id(); $table->foreignId('product_plan_id')->constrained('product_plans'); $table->foreignId('coverage_id')->constrained('coverages'); $table->boolean('mandatory')->default(false); $table->boolean('default_selected')->default(false); $table->jsonb('limit_definition_json')->nullable(); $table->jsonb('deductible_definition_json')->nullable(); $table->string('premium_rule_reference')->nullable(); $table->jsonb('conditions_json')->nullable(); });
        Schema::create('question_definitions', function (Blueprint $table) { $table->id(); $table->string('code')->unique(); $table->string('question_type'); $table->string('label_en'); $table->string('label_fr'); $table->text('help_text_en')->nullable(); $table->text('help_text_fr')->nullable(); $table->jsonb('validation_json')->nullable(); $table->foreignId('options_domain_id')->nullable()->constrained('master_data_domains'); $table->string('status')->default('ACTIVE'); });
        Schema::create('product_questions', function (Blueprint $table) { $table->id(); $table->foreignId('product_version_id')->constrained('product_versions'); $table->foreignId('question_id')->constrained('question_definitions'); $table->unsignedInteger('sequence'); $table->jsonb('required_rule_json')->nullable(); $table->jsonb('visibility_rule_json')->nullable(); });
        Schema::create('tariff_versions', function (Blueprint $table) { $table->id(); $table->foreignId('product_version_id')->constrained('product_versions'); $table->unsignedInteger('version_number'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('DRAFT'); $table->foreignId('approved_by')->nullable()->constrained('users'); $table->unique(['product_version_id','version_number']); });
        Schema::create('rating_rules', function (Blueprint $table) { $table->id(); $table->foreignId('tariff_version_id')->constrained('tariff_versions'); $table->unsignedInteger('priority')->default(100); $table->string('rating_method'); $table->jsonb('condition_json')->nullable(); $table->jsonb('calculation_json'); $table->text('description')->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('eligibility_rules', function (Blueprint $table) { $table->id(); $table->foreignId('product_version_id')->constrained('product_versions'); $table->unsignedInteger('priority')->default(100); $table->jsonb('expression_json'); $table->string('outcome'); $table->string('reason_code')->nullable(); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('underwriting_rules', function (Blueprint $table) { $table->id(); $table->foreignId('product_version_id')->constrained('product_versions'); $table->unsignedInteger('priority')->default(100); $table->jsonb('condition_json'); $table->string('decision'); $table->string('reason_code')->nullable(); $table->string('authority_type')->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('insurer_broker_agreements', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('insurer_id')->constrained('organizations'); $table->foreignId('broker_id')->constrained('organizations'); $table->string('agreement_number')->nullable(); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('DRAFT'); $table->jsonb('payment_terms_json')->nullable(); $table->jsonb('settlement_terms_json')->nullable(); });
        Schema::create('agreement_product_authorizations', function (Blueprint $table) { $table->id(); $table->foreignId('agreement_id')->constrained('insurer_broker_agreements'); $table->foreignId('product_id')->constrained('insurance_products'); $table->boolean('may_quote')->default(true); $table->boolean('may_bind')->default(false); $table->boolean('may_collect_premium')->default(false); $table->boolean('may_issue_documents')->default(false); $table->boolean('may_service_policy')->default(true); $table->boolean('may_assist_claims')->default(true); $table->string('status')->default('ACTIVE'); });
        Schema::create('quotes', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('quote_number'); $table->foreignId('customer_party_id')->constrained('parties'); $table->foreignId('insurer_id')->constrained('organizations'); $table->foreignId('broker_id')->nullable()->constrained('organizations'); $table->foreignId('product_version_id')->constrained('product_versions'); $table->foreignId('plan_id')->nullable()->constrained('product_plans'); $table->char('currency',3)->default('XAF'); $table->string('status')->default('DRAFT'); $table->timestampTz('valid_from')->nullable(); $table->timestampTz('valid_until')->nullable(); $table->unsignedBigInteger('pricing_snapshot_id')->nullable(); $table->foreignId('created_by')->constrained('users'); $table->timestampTz('presented_at')->nullable(); $table->timestampTz('accepted_at')->nullable(); $table->timestampsTz(); $table->unique(['tenant_id','quote_number']); });
        Schema::create('quote_risks', function (Blueprint $table) { $table->id(); $table->foreignId('quote_id')->constrained('quotes'); $table->string('risk_type'); $table->string('risk_entity_type')->nullable(); $table->unsignedBigInteger('risk_entity_id')->nullable(); $table->jsonb('risk_snapshot_json'); });
        Schema::create('pricing_snapshots', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->decimal('base_premium',20,4)->default(0); $table->decimal('coverage_premium',20,4)->default(0); $table->decimal('loadings',20,4)->default(0); $table->decimal('discounts',20,4)->default(0); $table->decimal('net_premium',20,4)->default(0); $table->decimal('taxes',20,4)->default(0); $table->decimal('levies',20,4)->default(0); $table->decimal('fees',20,4)->default(0); $table->decimal('gross_premium',20,4)->default(0); $table->char('currency',3); $table->foreignId('tariff_version_id')->nullable()->constrained('tariff_versions'); $table->jsonb('rating_inputs_json')->nullable(); $table->jsonb('rating_outputs_json')->nullable(); $table->string('external_reference')->nullable(); $table->timestampTz('created_at')->useCurrent(); });
    }

    public function down(): void
    {
        // Reverse in dependency-safe order in production migrations.
        // Scaffold intentionally avoids destructive blanket drops.
    }
};
