<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('vehicle_manufacturers', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->string('name'); $table->char('country_code',2)->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('vehicle_makes', function (Blueprint $table) { $table->id(); $table->foreignId('manufacturer_id')->nullable()->constrained('vehicle_manufacturers'); $table->string('code')->unique(); $table->string('name'); $table->char('country_code',2)->nullable(); $table->string('cameroon_presence_status')->nullable(); $table->string('market_priority')->default('NORMAL'); $table->string('status')->default('ACTIVE'); });
        Schema::create('vehicle_models', function (Blueprint $table) { $table->id(); $table->foreignId('make_id')->constrained('vehicle_makes'); $table->string('code'); $table->string('name'); $table->unsignedBigInteger('vehicle_class_id')->nullable(); $table->unsignedBigInteger('default_body_type_id')->nullable(); $table->string('status')->default('ACTIVE'); $table->unique(['make_id','code']); });
        Schema::create('vehicle_generations', function (Blueprint $table) { $table->id(); $table->foreignId('model_id')->constrained('vehicle_models'); $table->string('name'); $table->unsignedSmallInteger('start_year')->nullable(); $table->unsignedSmallInteger('end_year')->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('vehicle_variants', function (Blueprint $table) { $table->id(); $table->foreignId('generation_id')->constrained('vehicle_generations'); $table->string('name'); $table->string('engine_description')->nullable(); $table->unsignedBigInteger('powertrain_id')->nullable(); $table->unsignedBigInteger('transmission_id')->nullable(); $table->unsignedBigInteger('drive_type_id')->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('vehicles', function (Blueprint $table) {
            $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('owner_party_id')->constrained('parties'); $table->foreignId('make_id')->constrained('vehicle_makes'); $table->foreignId('model_id')->constrained('vehicle_models'); $table->foreignId('generation_id')->nullable()->constrained('vehicle_generations'); $table->foreignId('variant_id')->nullable()->constrained('vehicle_variants'); $table->unsignedSmallInteger('model_year'); $table->unsignedBigInteger('body_type_id'); $table->unsignedBigInteger('vehicle_class_id'); $table->unsignedBigInteger('usage_type_id'); $table->unsignedBigInteger('powertrain_id'); $table->unsignedBigInteger('transmission_id')->nullable(); $table->unsignedBigInteger('drive_type_id')->nullable(); $table->string('condition_code'); $table->string('registration_number')->nullable()->index(); $table->string('vin')->nullable()->index(); $table->string('engine_number')->nullable(); $table->unsignedInteger('engine_capacity_cc')->nullable(); $table->decimal('power_kw',12,4)->nullable(); $table->unsignedInteger('seat_count')->nullable(); $table->decimal('payload_kg',12,3)->nullable(); $table->decimal('gross_vehicle_weight_kg',12,3)->nullable(); $table->decimal('declared_value',20,4); $table->decimal('market_value',20,4)->nullable(); $table->decimal('purchase_price',20,4)->nullable(); $table->char('currency',3)->default('XAF'); $table->date('first_registration_date')->nullable(); $table->date('import_date')->nullable(); $table->char('country_of_origin',2)->nullable(); $table->string('status')->default('ACTIVE'); $table->timestampsTz();
        });
        Schema::create('properties', function (Blueprint $table) {
            $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('owner_party_id')->constrained('parties'); $table->unsignedBigInteger('property_type_id'); $table->unsignedBigInteger('occupancy_type_id'); $table->unsignedBigInteger('construction_type_id')->nullable(); $table->unsignedBigInteger('roof_type_id')->nullable(); $table->foreignId('address_id')->constrained('addresses'); $table->unsignedSmallInteger('year_built')->nullable(); $table->decimal('floor_area_sqm',14,3)->nullable(); $table->unsignedSmallInteger('number_of_floors')->nullable(); $table->unsignedSmallInteger('number_of_rooms')->nullable(); $table->decimal('building_value',20,4); $table->decimal('contents_value',20,4)->nullable(); $table->decimal('stock_value',20,4)->nullable(); $table->decimal('equipment_value',20,4)->nullable(); $table->char('currency',3)->default('XAF'); $table->jsonb('security_features_json')->nullable(); $table->jsonb('fire_protection_json')->nullable(); $table->string('status')->default('ACTIVE'); $table->timestampsTz();
        });
        Schema::create('regulatory_regimes', function (Blueprint $table) { $table->id(); $table->string('code')->unique(); $table->string('name'); $table->string('jurisdiction'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('ACTIVE'); });
        Schema::create('insurance_branches', function (Blueprint $table) { $table->id(); $table->foreignId('regime_id')->constrained('regulatory_regimes'); $table->unsignedSmallInteger('branch_number')->nullable(); $table->string('code'); $table->string('name_en'); $table->string('name_fr'); $table->string('category'); $table->foreignId('parent_id')->nullable()->constrained('insurance_branches'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('ACTIVE'); $table->unique(['regime_id','code']); });
        Schema::create('insurer_authorizations', function (Blueprint $table) { $table->id(); $table->foreignId('insurer_organization_id')->constrained('organizations'); $table->foreignId('regime_id')->constrained('regulatory_regimes'); $table->string('authorization_reference')->nullable(); $table->string('authorization_status'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('source_reference')->nullable(); $table->timestampTz('verified_at')->nullable(); });
        Schema::create('insurer_authorized_branches', function (Blueprint $table) { $table->id(); $table->foreignId('insurer_authorization_id')->constrained('insurer_authorizations'); $table->foreignId('insurance_branch_id')->constrained('insurance_branches'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('ACTIVE'); });
    }

    public function down(): void
    {
        // Reverse in dependency-safe order in production migrations.
        // Scaffold intentionally avoids destructive blanket drops.
    }
};
