<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('proposals', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('proposal_number'); $table->foreignId('quote_id')->nullable()->constrained('quotes'); $table->foreignId('customer_party_id')->constrained('parties'); $table->foreignId('product_version_id')->constrained('product_versions'); $table->string('status')->default('DRAFT'); $table->timestampTz('submitted_at')->nullable(); $table->jsonb('declarations_snapshot_json')->nullable(); $table->unsignedBigInteger('signature_document_id')->nullable(); $table->unique(['tenant_id','proposal_number']); });
        Schema::create('underwriting_cases', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('case_number'); $table->foreignId('proposal_id')->constrained('proposals'); $table->foreignId('assigned_to')->nullable()->constrained('users'); $table->string('status')->default('OPEN'); $table->decimal('risk_score',12,4)->nullable(); $table->string('recommended_decision')->nullable(); $table->string('final_decision')->nullable(); $table->text('decision_reason')->nullable(); $table->timestampTz('opened_at')->useCurrent(); $table->timestampTz('decided_at')->nullable(); $table->unique(['tenant_id','case_number']); });
        Schema::create('underwriting_referrals', function (Blueprint $table) { $table->id(); $table->foreignId('underwriting_case_id')->constrained('underwriting_cases'); $table->foreignId('referred_by')->constrained('users'); $table->foreignId('referred_to')->nullable()->constrained('users'); $table->string('authority_type')->nullable(); $table->decimal('required_amount',20,4)->nullable(); $table->char('currency',3)->nullable(); $table->text('reason'); $table->string('status')->default('REFERRED'); $table->string('decision')->nullable(); $table->text('decision_reason')->nullable(); $table->timestampTz('referred_at')->useCurrent(); $table->timestampTz('decided_at')->nullable(); });
        Schema::create('policies', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('policy_number'); $table->foreignId('insurer_id')->constrained('organizations'); $table->foreignId('broker_id')->nullable()->constrained('organizations'); $table->foreignId('product_id')->constrained('insurance_products'); $table->foreignId('product_version_id')->constrained('product_versions'); $table->foreignId('plan_id')->nullable()->constrained('product_plans'); $table->foreignId('policyholder_party_id')->constrained('parties'); $table->char('currency',3)->default('XAF'); $table->timestampTz('start_at'); $table->timestampTz('end_at'); $table->string('status')->default('DRAFT'); $table->string('issuance_mode'); $table->foreignId('original_policy_id')->nullable()->constrained('policies'); $table->foreignId('renewed_from_policy_id')->nullable()->constrained('policies'); $table->timestampTz('issued_at')->nullable(); $table->timestampTz('activated_at')->nullable(); $table->timestampsTz(); $table->unique(['insurer_id','policy_number']); });
        Schema::create('policy_versions', function (Blueprint $table) { $table->id(); $table->foreignId('policy_id')->constrained('policies'); $table->unsignedInteger('version_number'); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->string('change_type'); $table->string('source_type'); $table->unsignedBigInteger('source_id')->nullable(); $table->jsonb('snapshot_json'); $table->timestampTz('created_at')->useCurrent(); $table->unique(['policy_id','version_number']); });
        Schema::create('policy_parties', function (Blueprint $table) { $table->id(); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('party_id')->constrained('parties'); $table->string('role_type'); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); });
        Schema::create('policy_risks', function (Blueprint $table) { $table->id(); $table->foreignId('policy_id')->constrained('policies'); $table->string('risk_type'); $table->string('risk_entity_type')->nullable(); $table->unsignedBigInteger('risk_entity_id')->nullable(); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->jsonb('snapshot_json'); });
        Schema::create('policy_coverages', function (Blueprint $table) { $table->id(); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('coverage_id')->constrained('coverages'); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); $table->decimal('limit_amount',20,4)->nullable(); $table->decimal('deductible_amount',20,4)->nullable(); $table->decimal('premium_amount',20,4)->default(0); $table->char('currency',3)->default('XAF'); $table->string('status')->default('ACTIVE'); });
        Schema::create('policy_limits', function (Blueprint $table) { $table->id(); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('coverage_id')->constrained('coverages'); $table->string('limit_type'); $table->decimal('original_limit',20,4); $table->decimal('reserved_amount',20,4)->default(0); $table->decimal('consumed_amount',20,4)->default(0); $table->decimal('remaining_amount',20,4); $table->char('currency',3); $table->timestampTz('effective_from'); $table->timestampTz('effective_until')->nullable(); });
        Schema::create('endorsements', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('endorsement_number'); $table->foreignId('policy_id')->constrained('policies'); $table->string('endorsement_type'); $table->timestampTz('requested_at')->useCurrent(); $table->timestampTz('effective_at'); $table->string('status')->default('DRAFT'); $table->decimal('premium_delta',20,4)->default(0); $table->char('currency',3)->default('XAF'); $table->text('reason')->nullable(); $table->timestampTz('issued_at')->nullable(); $table->unique(['tenant_id','endorsement_number']); });
        Schema::create('renewals', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('policy_id')->constrained('policies'); $table->timestampTz('renewal_date'); $table->string('status')->default('NOT_DUE'); $table->foreignId('renewal_quote_id')->nullable()->constrained('quotes'); $table->foreignId('renewed_policy_id')->nullable()->constrained('policies'); $table->timestampTz('notice_sent_at')->nullable(); });
    }

    public function down(): void
    {
        // Reverse in dependency-safe order in production migrations.
        // Scaffold intentionally avoids destructive blanket drops.
    }
};
