<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('files', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('storage_provider'); $table->string('storage_key'); $table->string('original_filename'); $table->string('mime_type'); $table->unsignedBigInteger('size_bytes'); $table->string('sha256',64)->index(); $table->string('encryption_status')->default('ENCRYPTED'); $table->foreignId('uploaded_by')->nullable()->constrained('users'); $table->timestampTz('uploaded_at')->useCurrent(); });
        Schema::create('document_types', function (Blueprint $table) { $table->id(); $table->string('canonical_code')->unique(); $table->string('family_code'); $table->string('name_en'); $table->string('name_fr'); $table->string('default_origin')->nullable(); $table->string('security_level')->default('CUSTOMER_PRIVATE'); $table->string('verification_mode')->default('NONE'); $table->string('status')->default('ACTIVE'); });
        Schema::create('document_templates', function (Blueprint $table) { $table->id(); $table->foreignId('document_type_id')->constrained('document_types'); $table->string('owner_type'); $table->unsignedBigInteger('owner_id')->nullable(); $table->string('language'); $table->string('status')->default('DRAFT'); });
        Schema::create('document_template_versions', function (Blueprint $table) { $table->id(); $table->foreignId('template_id')->constrained('document_templates'); $table->unsignedInteger('version_number'); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->jsonb('content_definition'); $table->jsonb('style_definition')->nullable(); $table->jsonb('signature_configuration_json')->nullable(); $table->jsonb('verification_configuration_json')->nullable(); $table->string('status')->default('DRAFT'); $table->foreignId('approved_by')->nullable()->constrained('users'); $table->timestampTz('published_at')->nullable(); $table->unique(['template_id','version_number']); });
        Schema::create('documents', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('document_number'); $table->foreignId('document_type_id')->constrained('document_types'); $table->foreignId('template_version_id')->nullable()->constrained('document_template_versions'); $table->string('source_type'); $table->unsignedBigInteger('source_id'); $table->string('origin'); $table->foreignId('issuer_party_id')->nullable()->constrained('parties'); $table->foreignId('recipient_party_id')->nullable()->constrained('parties'); $table->string('language')->default('fr'); $table->string('status')->default('GENERATED'); $table->string('security_level'); $table->foreignId('file_id')->constrained('files'); $table->string('hash_sha256',64); $table->string('verification_token')->nullable()->unique(); $table->timestampTz('issued_at')->nullable(); $table->timestampTz('expires_at')->nullable(); $table->foreignId('supersedes_document_id')->nullable()->constrained('documents'); $table->timestampTz('created_at')->useCurrent(); $table->unique(['tenant_id','document_number']); $table->index(['source_type','source_id']); });
        Schema::create('cases', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('case_number'); $table->string('case_type'); $table->string('source_type')->nullable(); $table->unsignedBigInteger('source_id')->nullable(); $table->foreignId('owner_user_id')->nullable()->constrained('users'); $table->string('priority')->default('NORMAL'); $table->string('status')->default('OPEN'); $table->timestampTz('opened_at')->useCurrent(); $table->timestampTz('due_at')->nullable(); $table->timestampTz('closed_at')->nullable(); $table->string('resolution_code')->nullable(); $table->text('summary')->nullable(); $table->unique(['tenant_id','case_number']); });
        Schema::create('tasks', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('case_id')->nullable()->constrained('cases'); $table->string('source_type'); $table->unsignedBigInteger('source_id'); $table->string('task_type'); $table->foreignId('assigned_to')->constrained('users'); $table->string('priority')->default('NORMAL'); $table->string('status')->default('OPEN'); $table->timestampTz('due_at'); $table->timestampTz('completed_at')->nullable(); $table->index(['assigned_to','status','due_at']); });
        Schema::create('correspondences', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('source_type'); $table->unsignedBigInteger('source_id'); $table->string('channel'); $table->string('direction'); $table->foreignId('sender_party_id')->nullable()->constrained('parties'); $table->foreignId('sender_user_id')->nullable()->constrained('users'); $table->foreignId('recipient_party_id')->nullable()->constrained('parties'); $table->string('recipient_address')->nullable(); $table->string('subject')->nullable(); $table->text('body_summary')->nullable(); $table->foreignId('document_id')->nullable()->constrained('documents'); $table->timestampTz('sent_at')->nullable(); $table->string('delivery_status')->default('PENDING'); $table->string('external_reference')->nullable(); });
        Schema::create('regulatory_rules', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('regime_id')->constrained('regulatory_regimes'); $table->string('code'); $table->string('title'); $table->string('source_reference')->nullable(); $table->timestampTz('effective_from')->nullable(); $table->timestampTz('effective_until')->nullable(); $table->string('status')->default('DRAFT'); $table->text('summary')->nullable(); $table->unique(['regime_id','code']); });
        Schema::create('audit_events', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->uuid('correlation_id')->index(); $table->foreignId('actor_user_id')->nullable()->constrained('users'); $table->foreignId('actor_party_id')->nullable()->constrained('parties'); $table->string('action'); $table->string('entity_type'); $table->unsignedBigInteger('entity_id'); $table->jsonb('before_json')->nullable(); $table->jsonb('after_json')->nullable(); $table->text('reason')->nullable(); $table->string('ip_address')->nullable(); $table->text('user_agent')->nullable(); $table->string('session_id')->nullable(); $table->timestampTz('occurred_at')->useCurrent(); $table->index(['entity_type','entity_id','occurred_at']); });
        Schema::create('outbox_events', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('event_type'); $table->string('aggregate_type'); $table->unsignedBigInteger('aggregate_id'); $table->jsonb('payload_json'); $table->timestampTz('occurred_at')->useCurrent(); $table->timestampTz('published_at')->nullable(); $table->unsignedInteger('attempt_count')->default(0); $table->string('status')->default('PENDING'); $table->index(['status','occurred_at']); });
    }

    public function down(): void
    {
        // Reverse in dependency-safe order in production migrations.
        // Scaffold intentionally avoids destructive blanket drops.
    }
};
