<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('financial_obligations', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('obligation_number'); $table->string('obligation_type'); $table->foreignId('debtor_party_id')->constrained('parties'); $table->foreignId('creditor_party_id')->constrained('parties'); $table->string('source_type'); $table->unsignedBigInteger('source_id'); $table->char('currency',3); $table->decimal('original_amount',20,4); $table->decimal('paid_amount',20,4)->default(0); $table->decimal('outstanding_amount',20,4); $table->timestampTz('due_at')->nullable(); $table->string('status')->default('DUE'); $table->timestampsTz(); $table->unique(['tenant_id','obligation_number']); $table->index(['source_type','source_id']); });
        Schema::create('payments', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('payment_reference'); $table->foreignId('payer_party_id')->constrained('parties'); $table->foreignId('payee_party_id')->constrained('parties'); $table->unsignedBigInteger('payment_method_id'); $table->char('currency',3); $table->decimal('amount',20,4); $table->string('status')->default('CREATED'); $table->string('provider_reference')->nullable()->index(); $table->string('external_transaction_id')->nullable(); $table->timestampTz('initiated_at')->useCurrent(); $table->timestampTz('paid_at')->nullable(); $table->timestampTz('reconciled_at')->nullable(); $table->unique(['tenant_id','payment_reference']); });
        Schema::create('payment_allocations', function (Blueprint $table) { $table->id(); $table->foreignId('payment_id')->constrained('payments'); $table->foreignId('financial_obligation_id')->constrained('financial_obligations'); $table->decimal('allocated_amount',20,4); $table->timestampTz('allocated_at')->useCurrent(); $table->foreignId('created_by')->constrained('users'); });
        Schema::create('refunds', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('refund_number'); $table->foreignId('source_payment_id')->constrained('payments'); $table->foreignId('beneficiary_party_id')->constrained('parties'); $table->string('reason_code'); $table->char('currency',3); $table->decimal('amount',20,4); $table->string('status')->default('REQUESTED'); $table->foreignId('requested_by')->constrained('users'); $table->foreignId('approved_by')->nullable()->constrained('users'); $table->timestampTz('paid_at')->nullable(); $table->unique(['tenant_id','refund_number']); });
        Schema::create('commission_entries', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->foreignId('policy_id')->constrained('policies'); $table->foreignId('payment_id')->nullable()->constrained('payments'); $table->foreignId('recipient_party_id')->constrained('parties'); $table->unsignedBigInteger('commission_rule_id')->nullable(); $table->decimal('basis_amount',20,4); $table->decimal('rate',9,6)->nullable(); $table->decimal('amount',20,4); $table->char('currency',3); $table->string('status')->default('CALCULATED'); $table->timestampTz('earned_at')->nullable(); $table->timestampTz('payable_at')->nullable(); $table->timestampTz('paid_at')->nullable(); });
        Schema::create('gl_accounts', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('code'); $table->string('name'); $table->string('account_type'); $table->foreignId('parent_id')->nullable()->constrained('gl_accounts'); $table->char('currency',3)->nullable(); $table->string('status')->default('ACTIVE'); $table->unique(['tenant_id','code']); });
        Schema::create('accounting_events', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('event_type'); $table->string('source_type'); $table->unsignedBigInteger('source_id'); $table->char('currency',3); $table->decimal('amount',20,4); $table->timestampTz('event_at'); $table->string('status')->default('PENDING'); $table->index(['source_type','source_id']); });
        Schema::create('journals', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants'); $table->string('journal_number'); $table->foreignId('accounting_event_id')->nullable()->constrained('accounting_events'); $table->date('posting_date'); $table->string('status')->default('DRAFT'); $table->text('description')->nullable(); $table->foreignId('created_by')->constrained('users'); $table->foreignId('approved_by')->nullable()->constrained('users'); $table->timestampTz('posted_at')->nullable(); $table->unique(['tenant_id','journal_number']); });
        Schema::create('journal_lines', function (Blueprint $table) { $table->id(); $table->foreignId('journal_id')->constrained('journals'); $table->foreignId('gl_account_id')->constrained('gl_accounts'); $table->foreignId('branch_id')->nullable()->constrained('organization_branches'); $table->unsignedBigInteger('cost_center_id')->nullable(); $table->char('currency',3); $table->decimal('debit',20,4)->default(0); $table->decimal('credit',20,4)->default(0); $table->text('description')->nullable(); });
    }

    public function down(): void
    {
        // Reverse in dependency-safe order in production migrations.
        // Scaffold intentionally avoids destructive blanket drops.
    }
};
