<?php
namespace App\Filament\Admin\Resources\Memberships;
use App\Application\Identity\MembershipService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\Memberships\Pages;use App\Models\TenantMembership;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Notifications\Notification;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class MembershipResource extends Resource
{
protected static?string$model=TenantMembership::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedUserGroup;protected static?string$navigationLabel='Access & roles';protected static?int$navigationSort=13;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Organization access')->columns(2)->schema([Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload()->required(),Forms\Components\Select::make('user_id')->relationship('user','full_name')->searchable()->preload()->required(),Forms\Components\Select::make('branch_id')->relationship('branch','name')->searchable()->preload(),Forms\Components\Select::make('role_code')->options(\App\Application\Identity\RoleCatalogue::LABELS)->required()->native(false)->live(),Forms\Components\Select::make('carrier_id')->label('Insurer')->options(fn()=>\App\Models\Carrier::with('party')->get()->mapWithKeys(fn($c)=>[$c->id=>($c->party?->display_name??$c->cima_code)])->all())->searchable()->helperText('Insurer roles only see this carrier\'s data.')->visible(fn($get)=>in_array($get('role_code'),\App\Application\Identity\RoleCatalogue::CARRIER_ROLES,true))->required(fn($get)=>in_array($get('role_code'),\App\Application\Identity\RoleCatalogue::CARRIER_ROLES,true)),Forms\Components\Select::make('status')->options(['ACTIVE'=>'Active','SUSPENDED'=>'Suspended','REVOKED'=>'Revoked'])->required()->native(false)->disabled(fn(?TenantMembership$r)=>$r?->status==='REVOKED')]),\Filament\Schemas\Components\Section::make('Fine-grained roles')->schema([Forms\Components\Select::make('roles')->relationship('roles','code')->multiple()->preload()->searchable()])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('user.full_name')->label('User')->searchable()->description(fn(TenantMembership$m)=>$m->user?->email??$m->user?->phone_e164),Tables\Columns\TextColumn::make('tenant.legal_name')->label('Organization')->searchable(),Tables\Columns\TextColumn::make('branch.name')->label('Branch')->placeholder('All branches'),Tables\Columns\TextColumn::make('role_code')->label('Primary role')->badge(),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'ACTIVE'=>'success','SUSPENDED'=>'warning','REVOKED'=>'danger',default=>'gray'})])->filters([Tables\Filters\SelectFilter::make('status')->options(['ACTIVE'=>'Active','SUSPENDED'=>'Suspended','REVOKED'=>'Revoked'])])->recordActions([Actions\EditAction::make(),Actions\Action::make('revoke')->label('Revoke access')->icon(Heroicon::OutlinedNoSymbol)->color('danger')->requiresConfirmation()->schema([Forms\Components\Textarea::make('reason')->required()->minLength(10)])->visible(fn(TenantMembership$m)=>$m->status!=='REVOKED'&&$m->user_id!==auth()->id())->action(function(TenantMembership$m,array$data){if(ServiceValidation::run(fn()=>app(MembershipService::class)->revoke($m,auth()->user(),$data['reason']))===null)return;Notification::make()->title('Access revoked')->success()->send();})])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No access assignments')->emptyStateDescription('Invite a colleague or assign an existing user to an organization.')->emptyStateIcon(Heroicon::OutlinedUserGroup);}
public static function getPages():array{return['index'=>Pages\ListMemberships::route('/'),'create'=>Pages\CreateMembership::route('/create'),'edit'=>Pages\EditMembership::route('/{record}/edit')];}}
