<?php
namespace App\Filament\Admin\Resources\Devices;
use App\Application\Identity\AccountSecurityService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\Devices\Pages;use App\Models\UserDevice;use BackedEnum;use Filament\Actions;use Filament\Notifications\Notification;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class DeviceResource extends Resource
{
protected static?string$model=UserDevice::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedComputerDesktop;protected static?string$navigationLabel='Trusted devices';protected static?int$navigationSort=15;
public static function form(Schema$s):Schema{return$s->components([]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('user.full_name')->label('User')->searchable(),Tables\Columns\TextColumn::make('name')->placeholder('Unnamed device'),Tables\Columns\TextColumn::make('platform')->badge(),Tables\Columns\IconColumn::make('trusted_at')->label('Trusted')->boolean(fn(UserDevice$d)=>$d->trusted_at!==null&&$d->revoked_at===null),Tables\Columns\TextColumn::make('last_seen_at')->dateTime()->since(),Tables\Columns\TextColumn::make('revoked_at')->dateTime()->placeholder('Active')])->recordActions([Actions\Action::make('revoke')->color('danger')->requiresConfirmation()->visible(fn(UserDevice$d)=>$d->revoked_at===null)->action(function(UserDevice$d){if(ServiceValidation::run(fn()=>app(AccountSecurityService::class)->revokeDevice($d,auth()->user()))===null)return;Notification::make()->title('Device and sessions revoked')->success()->send();})])->emptyStateHeading('No registered devices')->emptyStateDescription('Devices appear after a successful authenticated session.')->emptyStateIcon(Heroicon::OutlinedComputerDesktop);}
public static function canCreate():bool{return false;}public static function getPages():array{return['index'=>Pages\ListDevices::route('/')];}}
