<?php
namespace App\Filament\Admin\Resources\Customers;
use App\Application\Customers\CustomerService;use App\Filament\Admin\Concerns\ServiceValidation;use App\Filament\Admin\Resources\Customers\Pages;use App\Models\TenantCustomer;use BackedEnum;use Filament\Actions;use Filament\Forms;use Filament\Infolists;use Filament\Notifications\Notification;use Filament\Resources\Resource;use Filament\Schemas\Schema;use Filament\Support\Icons\Heroicon;use Filament\Tables;use Filament\Tables\Table;
final class CustomerResource extends Resource
{
protected static?string$model=TenantCustomer::class;protected static string|BackedEnum|null$navigationIcon=Heroicon::OutlinedUsers;protected static string|\UnitEnum|null$navigationGroup='Customers & partners';protected static?int$navigationSort=21;
public static function form(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Customer relationship')->columnSpanFull()->columns(2)->schema([Forms\Components\Select::make('tenant_id')->relationship('tenant','legal_name')->searchable()->preload()->required(),Forms\Components\Select::make('party_id')->relationship('party','display_name')->searchable()->preload()->required(),Forms\Components\TextInput::make('segment')->maxLength(64),Forms\Components\TextInput::make('external_reference')->maxLength(100)])]);}
public static function infolist(Schema$s):Schema{return$s->components([\Filament\Schemas\Components\Section::make('Customer relationship')->columnSpanFull()->columns(2)->schema([Infolists\Components\TextEntry::make('customer_number')->label('Customer number')->copyable(),Infolists\Components\TextEntry::make('status')->badge()->color(fn(string$state)=>match($state){'ACTIVE'=>'success','SUSPENDED'=>'warning',default=>'gray'}),Infolists\Components\TextEntry::make('party.display_name')->label('Customer'),Infolists\Components\TextEntry::make('tenant.legal_name')->label('Organization'),Infolists\Components\TextEntry::make('private_metadata.segment')->label('Segment')->placeholder('—'),Infolists\Components\TextEntry::make('private_metadata.external_reference')->label('External reference')->placeholder('—'),Infolists\Components\TextEntry::make('created_at')->label('Registered')->dateTime()])]);}
public static function table(Table$t):Table{return$t->columns([Tables\Columns\TextColumn::make('customer_number')->searchable()->copyable(),Tables\Columns\TextColumn::make('party.display_name')->label('Customer')->searchable()->sortable(),Tables\Columns\TextColumn::make('tenant.legal_name')->label('Organization')->searchable(),Tables\Columns\TextColumn::make('status')->badge()->color(fn(string$state)=>match($state){'ACTIVE'=>'success','SUSPENDED'=>'warning',default=>'gray'}),Tables\Columns\TextColumn::make('created_at')->dateTime()->sortable()])->filters([Tables\Filters\SelectFilter::make('status')->options(['ACTIVE'=>'Active','SUSPENDED'=>'Suspended','ARCHIVED'=>'Archived'])])->recordActions([Actions\ViewAction::make(),Actions\Action::make('status')->label(fn(TenantCustomer$c)=>$c->status==='ACTIVE'?'Suspend':'Reactivate')->visible(fn(TenantCustomer$c)=>$c->status!=='ARCHIVED')->requiresConfirmation()->schema([Forms\Components\Select::make('reason')->options(['CUSTOMER_REQUEST'=>'Customer request','COMPLIANCE_HOLD'=>'Compliance hold','RESTORED_AFTER_REVIEW'=>'Restored after review'])->required(),Forms\Components\Textarea::make('notes')->required()->minLength(10)])->action(function(TenantCustomer$c,array$data){if(ServiceValidation::run(fn()=>app(CustomerService::class)->transition($c,$c->status==='ACTIVE'?'SUSPENDED':'ACTIVE',$data['reason'],$data['notes'],auth()->user()))===null)return;Notification::make()->title('Customer status updated')->success()->send();})])->toolbarActions([Actions\CreateAction::make()])->emptyStateHeading('No customers')->emptyStateDescription('Create a customer relationship from a verified canonical identity.')->emptyStateIcon(Heroicon::OutlinedUsers);}
public static function getPages():array{return['index'=>Pages\ListCustomers::route('/'),'create'=>Pages\CreateCustomer::route('/create'),'view'=>Pages\ViewCustomer::route('/{record}')];}}
