<?php
namespace App\Interfaces\Http\Controllers\Api\V1\BrokerOperations;use App\Application\Audit\AuditWriter;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class BrokerOperationsController{
/** REQ-DUP-008 deprecated alias of POST bordereaux: broker scope requires an explicit policy selection; maps the legacy body onto the one BordereauService. */
public function createBordereau(Request$r,\App\Application\FinancialDistribution\BordereauService$bordereaux){if(is_string($r->input('type')))$r->merge(['type'=>\App\Application\FinancialDistribution\ReinsuranceReference::bordereauType($r->input('type'))]);$d=$r->validate(['carrier_id'=>'required|uuid|exists:carriers,id','type'=>['required',\App\Application\FinancialDistribution\ReinsuranceReference::bordereauTypeRule()],'period_start'=>'required|date','period_end'=>'required|date|after_or_equal:period_start','currency'=>'nullable|string|size:3','idempotency_key'=>'nullable|string|max:100','policy_ids'=>'required|array|min:1|max:5000','policy_ids.*'=>'uuid|exists:policies,id']);$tenant=app(\App\Domain\Tenancy\TenantContext::class)->id();$b=$bordereaux->prepare([...$d,'tenant_id'=>$tenant,'currency'=>strtoupper($d['currency']??(string)(DB::table('policies')->whereIn('id',$d['policy_ids'])->value('currency')??'XAF')),'idempotency_key'=>$d['idempotency_key']??$r->header('Idempotency-Key')??(string)Str::uuid()],$r->user());return response()->json(['data'=>['id'=>$b->id,'bordereau_number'=>$b->bordereau_number,'item_count'=>$b->item_count,'gross_premium_minor'=>$b->gross_premium_minor,'commission_minor'=>$b->commission_minor]],201);}
/** REQ-DUP-008 deprecated alias of POST bordereaux/{bordereau}/submit (same service; notes kept in the audit trail). */
public function submitBordereau(Request$r,string$bordereau,\App\Application\FinancialDistribution\BordereauService$bordereaux){$d=$r->validate(['notes'=>'required|string|min:20|max:2000']);$row=\App\Models\Bordereau::where('tenant_id',app(\App\Domain\Tenancy\TenantContext::class)->id())->where(['id'=>$bordereau,'status'=>'APPROVED'])->first();abort_unless($row,409,'Only an approved bordereau can be submitted.');abort_if($row->prepared_by===$r->user()->id,403,'The preparer of a bordereau cannot submit it.');$b=$bordereaux->submit($row,$r->user(),$d['notes']);return response()->json(['data'=>['id'=>$b->id,'status'=>$b->status]]);}
/** REQ-DUP-010 deprecated alias of POST renewals/seed: same RenewalService sweep, legacy body (days_ahead) and response (created = new work items). */
public function seedRenewals(Request$r,\App\Application\Policies\RenewalService$renewals){$d=$r->validate(['days_ahead'=>'required|integer|min:1|max:180']);$x=$renewals->sweep(\App\Models\Tenant::findOrFail(app(\App\Domain\Tenancy\TenantContext::class)->id()),(int)$d['days_ahead'],$r->user());return response()->json(['data'=>['created'=>$x['work_items_created']]]);}}
